ALTER TABLE android_unknown_permissions
  ADD COLUMN IF NOT EXISTS triage_status ENUM(
    'UNREVIEWED','PROVISIONAL','CONFIRMED','REJECTED','DEPRECATED',
    'REVIEW_REQUIRED_ANDROID_DRIFT','REVIEW_REQUIRED_OEM',
    'ESCALATED_RESEARCH'
  ) NOT NULL DEFAULT 'UNREVIEWED',
  ADD COLUMN IF NOT EXISTS triage_reason_code VARCHAR(64) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS triage_notes TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS triage_reviewer VARCHAR(128) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS triage_updated_at_utc DATETIME DEFAULT NULL;

ALTER TABLE android_unknown_permissions
  ADD COLUMN IF NOT EXISTS is_ghost_aosp TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ghost_baseline_version VARCHAR(32) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS ghost_first_seen_at_utc DATETIME DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS ghost_last_seen_at_utc DATETIME DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS resolved_as ENUM('AOSP','GMS','OEM','APP_DEFINED','THIRD_PARTY_SDK') DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS resolved_in_baseline VARCHAR(32) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS resolution_timestamp_utc DATETIME DEFAULT NULL;
