from __future__ import annotations

import pytest


@pytest.mark.parametrize(
    ("script_path", "argv", "expected_terms"),
    [
        (
            "scripts/db/report_dynamic_deep_audit.py",
            (),
            (
                "deep audit over dynamic evidence quality",
                "--package",
                "--overlay-reanalyse-strings",
            ),
        ),
        (
            "scripts/db/report_dynamic_domain_context.py",
            (),
            (
                "domain-context",
                "--package",
            ),
        ),
        (
            "scripts/db/report_dynamic_service_context.py",
            (),
            (
                "service/provider context",
                "--package",
            ),
        ),
        (
            "scripts/db/report_dynamic_service_signals.py",
            (),
            ("dynamic privacy/security/context signals",),
        ),
        (
            "scripts/db/report_dynamic_unresolved_domains.py",
            (),
            (
                "unresolved",
                "--package",
            ),
        ),
        (
            "scripts/db/report_dynamic_legacy_corpus.py",
            (),
            (
                "legacy",
                "dynamic evidence",
            ),
        ),
        (
            "scripts/db/report_dynamic_lineage_audit.py",
            (),
            ("dynamic evidence lineage",),
        ),
        (
            "scripts/db/report_dynamic_interaction_phases.py",
            (),
            ("interaction phases",),
        ),
        (
            "scripts/db/report_dynamic_paper_exports.py",
            (),
            ("paper-facing exports",),
        ),
        (
            "scripts/db/report_pcap_observer_audit.py",
            (),
            ("pcap observer audit",),
        ),
        (
            "scripts/db/report_static_string_dynamic_corroboration.py",
            (),
            (
                "corroboration",
                "--output-dir",
                "--package",
                "--overlay-latest-static",
                "--overlay-reanalyse-strings",
            ),
        ),
        (
            "scripts/db/report_dynamic_hidden_patterns.py",
            (),
            ("hidden-pattern exports",),
        ),
        (
            "scripts/db/report_static_deep_audit.py",
            (),
            ("deep audit over static evidence quality",),
        ),
        (
            "scripts/db/report_dynamic_pcap_behavior_ml.py",
            (),
            (
                "read-only behavioral analysis over dynamic pcap-derived features.",
                "--recompute-exact-tls",
            ),
        ),
        (
            "scripts/db/report_multimodal_static_dynamic_ml.py",
            (),
            (
                "read-only fused static + dynamic + pcap analysis",
                "--recompute-exact-tls",
            ),
        ),
        (
            "scripts/db/report_dynamic_live_operational_state.py",
            (),
            ("read-only live operational state report for the dynamic cohort queue.",),
        ),
        (
            "scripts/db/report_dynamic_tls_fingerprint_audit.py",
            (),
            (
                "read-only audit of tls fingerprint population",
                "--recompute-top-values",
            ),
        ),
        (
            "scripts/db/report_dynamic_readiness_audit.py",
            (),
            (
                "--output-dir",
                "dynamic readiness",
            ),
        ),
        (
            "scripts/db/report_artifact_registry_static_dangling.py",
            (),
            (
                "dangling static",
                "--output-dir",
            ),
        ),
        (
            "scripts/db/report_artifact_registry_static_detached.py",
            (),
            (
                "--json",
                "detached",
            ),
        ),
        (
            "scripts/db/report_artifact_registry_static_session_retirement.py",
            (),
            ("static_session_retirement",),
        ),
        (
            "scripts/db/report_artifact_registry_static_legacy_overlap.py",
            (),
            ("static_legacy_overlap",),
        ),
        (
            "scripts/db/backfill_static_report_findings_fidelity.py",
            (),
            ("--apply",),
        ),
        (
            "scripts/db/report_dynamic_domain_ml_context.py",
            (),
            (),
        ),
        (
            "scripts/db/backfill_dynamic_service_context.py",
            (),
            (),
        ),
        (
            "scripts/db/backfill_dynamic_service_signals.py",
            (),
            (),
        ),
        (
            "scripts/db/phase_b1_join_key_normalization.py",
            (),
            (),
        ),
        (
            "scripts/db/phase_b1_join_key_normalization.py",
            ("report",),
            (),
        ),
        (
            "scripts/db/phase_b1_join_key_normalization.py",
            ("apply",),
            (),
        ),
        (
            "scripts/db/phase_b1_session_stamp_backlog.py",
            (),
            (),
        ),
        (
            "scripts/db/phase_b1_session_stamp_backlog.py",
            ("report",),
            (),
        ),
        (
            "scripts/db/phase_b1_session_stamp_backlog.py",
            ("apply",),
            (),
        ),
        (
            "scripts/db/schema_version_width_hotfix.py",
            (),
            (),
        ),
        (
            "scripts/db/schema_version_width_hotfix.py",
            ("report",),
            (),
        ),
        (
            "scripts/db/schema_version_width_hotfix.py",
            ("apply",),
            (),
        ),
        (
            "scripts/db/prune_artifact_registry_dynamic_detached.py",
            (),
            (
                "--apply",
                "dynamic",
            ),
        ),
        (
            "scripts/db/prune_artifact_registry_dangling.py",
            (),
            (
                "--apply",
                "--sample-ids",
            ),
        ),
        (
            "scripts/db/backfill_artifact_registry_session_stamp.py",
            (),
            (
                "--apply",
                "--json",
            ),
        ),
        (
            "scripts/db/dedupe_artifact_registry_static_dep_snapshots.py",
            (),
            (),
        ),
        (
            "scripts/db/prune_artifact_registry_static_detached.py",
            (),
            (
                "--apply",
                "static",
            ),
        ),
        (
            "scripts/db/prune_artifact_registry_static_legacy_sessions.py",
            (),
            ("session-stamp",),
        ),
        (
            "scripts/db/backfill_artifact_registry_typed_linkage.py",
            (),
            ("--apply",),
        ),
        (
            "scripts/db/report_artifact_registry_typed_linkage_audit.py",
            (),
            ("--json",),
        ),
        (
            "scripts/db/report_dynamic_static_alignment.py",
            (),
            ("--exact-target-readiness",),
        ),
        (
            "scripts/db/report_apk_lineage_availability.py",
            (),
            (
                "--only-gaps",
                "--design-checks",
                "lineage",
            ),
        ),
        (
            "scripts/db/report_dynamic_static_recovery_plan.py",
            (),
            (
                "recovery",
                "--package",
                "--write-receipt",
                "--old-root-policy",
            ),
        ),
        (
            "scripts/db/report_static_analysis_targets.py",
            (),
            (
                "--only-actionable",
                "target queue",
            ),
        ),
        (
            "scripts/db/report_dynamic_static_pairing_eligibility.py",
            (),
            (
                "--old-root-policy",
                "eligibility",
            ),
        ),
        (
            "scripts/db/report_current_corpus_preflight.py",
            (),
            (
                "--only-current-bytes",
                "--status",
                "preflight",
            ),
        ),
        (
            "scripts/db/report_package_lineage_workbench.py",
            (),
            (
                "--package",
                "--only-actionable",
                "--hash-limit",
                "--show-paths",
                "workbench",
            ),
        ),
        (
            "scripts/db/backfill_apk_sets_from_receipts.py",
            (),
            (
                "--apply",
                "install-set",
            ),
        ),
        (
            "scripts/db/backfill_apk_set_links.py",
            (),
            (
                "--apply",
                "apk_set_id",
            ),
        ),
        (
            "scripts/db/normalize_evidence_hash_collation.py",
            (),
            ("--apply",),
        ),
        (
            "scripts/db/check_evidence_latest_write_posture.py",
            (),
            ("since-hours",),
        ),
        (
            "scripts/db/check_evidence_storage_posture.py",
            (),
            ("evidence",),
        ),
        (
            "scripts/db/check_static_run_governance_posture.py",
            (),
            ("governance",),
        ),
        (
            "scripts/db/verify_static_session_id_rollout.py",
            (),
            ("--explain",),
        ),
        (
            "scripts/db/report_external_tracker_context.py",
            (),
            (
                "--session",
                "tracker context",
            ),
        ),
        (
            "scripts/db/refresh_external_sdk_tracker_intel.py",
            (),
            (),
        ),
        (
            "scripts/db/report_canonical_schema_map.py",
            (),
            (),
        ),
    ],
)
def test_db_report_help_contracts(
    assert_safe_script_help,
    script_path: str,
    argv: tuple[str, ...],
    expected_terms: tuple[str, ...],
) -> None:
    out = assert_safe_script_help(script_path, *argv, timeout=20).lower()
    assert out.startswith("usage:")
    for term in expected_terms:
        assert term in out
