#!/usr/bin/env python3
"""Audit static-analysis report output families without pruning anything."""

from __future__ import annotations

import argparse
import csv
import json
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Iterable


@dataclass(frozen=True)
class Family:
    name: str
    path: Path
    pattern: str
    classification: str
    recommendation: str


def _timestamp() -> str:
    return datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")


def _iter_matching_files(root: Path, pattern: str) -> Iterable[Path]:
    if not root.exists():
        return ()
    return root.rglob(pattern)


def _family_stats(family: Family) -> dict[str, object]:
    count = 0
    bytes_total = 0
    oldest: float | None = None
    newest: float | None = None
    sample_paths: list[str] = []
    for path in _iter_matching_files(family.path, family.pattern):
        if not path.is_file():
            continue
        try:
            stat = path.stat()
        except OSError:
            continue
        count += 1
        bytes_total += int(stat.st_size)
        oldest = stat.st_mtime if oldest is None else min(oldest, stat.st_mtime)
        newest = stat.st_mtime if newest is None else max(newest, stat.st_mtime)
        if len(sample_paths) < 5:
            sample_paths.append(str(path))
    return {
        "name": family.name,
        "path": str(family.path),
        "exists": family.path.exists(),
        "pattern": family.pattern,
        "file_count": count,
        "bytes": bytes_total,
        "oldest_mtime_utc": _format_mtime(oldest),
        "newest_mtime_utc": _format_mtime(newest),
        "classification": family.classification,
        "recommendation": family.recommendation,
        "sample_paths": sample_paths,
    }


def _format_mtime(value: float | None) -> str | None:
    if value is None:
        return None
    return datetime.fromtimestamp(value, UTC).isoformat()


def _session_breakdown(archive_root: Path) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    if not archive_root.exists():
        return rows
    for session_dir in sorted(path for path in archive_root.iterdir() if path.is_dir()):
        count = 0
        bytes_total = 0
        for path in session_dir.rglob("*.json"):
            if not path.is_file():
                continue
            try:
                stat = path.stat()
            except OSError:
                continue
            count += 1
            bytes_total += int(stat.st_size)
        rows.append(
            {
                "session": session_dir.name,
                "path": str(session_dir),
                "json_files": count,
                "bytes": bytes_total,
            }
        )
    rows.sort(key=lambda row: int(row["bytes"]), reverse=True)
    return rows


def _write_csv(path: Path, rows: list[dict[str, object]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row.get(field, "") for field in fieldnames})


def _write_generation_map(path: Path, family_rows: list[dict[str, object]]) -> None:
    by_name = {str(row["name"]): row for row in family_rows}

    def count(name: str) -> str:
        row = by_name.get(name) or {}
        return f"{row.get('file_count', 0)} files / {row.get('bytes', 0)} bytes"

    lines = [
        "# Static Report Output Generation Map",
        "",
        "This is a read-only audit of static-analysis report outputs.",
        "",
        "## Generation Paths",
        "",
        "- `scan_report.finish_report_after_analysis` calls `save_report()` once per scanned APK artifact when persistence is enabled.",
        "- `save_report()` writes canonical JSON under `data/static_analysis/reports/latest` and/or `data/static_analysis/reports/archive/<session>` depending on `SCYTALEDROID_STATIC_REPORT_JSON_MODE`.",
        "- `save_report()` can also call `save_html_report()` for optional human HTML mirrors under `output/reports/static`, controlled by `SCYTALEDROID_STATIC_HTML_MODE`.",
        "- Publication study reports are separate derived outputs under `output/reports/static_exposure_privacy/<timestamp>` and are generated by the Reporting subsystem, not the static scan loop.",
        "",
        "## Current Counts",
        "",
        f"- Legacy latest HTML mirror: {count('legacy_static_html_latest')}",
        f"- Legacy archive HTML mirror: {count('legacy_static_html_archive')}",
        f"- Canonical latest JSON mirror: {count('canonical_static_json_latest')}",
        f"- Canonical archive JSON evidence: {count('canonical_static_json_archive')}",
        f"- Static report cache: {count('static_report_cache')}",
        f"- Study static exposure reports: {count('study_static_exposure_reports')}",
        "",
        "## Safe Interpretation",
        "",
        "- HTML mirrors are derived views and can be regenerated from JSON; they are now disabled by default.",
        "- `latest` JSON is a content-addressed convenience mirror, not session-scoped evidence.",
        "- `archive/<session>` JSON is the run-scoped evidence family and needs session retirement checks before pruning.",
        "- `_cache/package_index_v*.json` is rebuildable cache.",
        "",
        "## Recommended Next Step",
        "",
        "Build a session-retirement report for `data/static_analysis/reports/archive/<session>` that checks DB/static handoff/report references before pruning older full-scan sessions.",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def _families(repo_root: Path) -> list[Family]:
    return [
        Family(
            "legacy_static_html_latest",
            repo_root / "output" / "reports" / "static" / "latest",
            "*.html",
            "derived_latest_html_mirror",
            "Safe to prune when JSON/DB evidence exists; disabled by default after this audit pass.",
        ),
        Family(
            "legacy_static_html_archive",
            repo_root / "output" / "reports" / "static" / "archive",
            "*.html",
            "derived_archive_html_mirror",
            "Optional human mirror; keep only if intentionally exported for review.",
        ),
        Family(
            "legacy_static_analysis_html",
            repo_root / "output" / "reports" / "static_analysis",
            "*.html",
            "legacy_or_orphaned_html",
            "Legacy static HTML location; safe prune candidate after spot-check.",
        ),
        Family(
            "canonical_static_json_latest",
            repo_root / "data" / "static_analysis" / "reports" / "latest",
            "*.json",
            "latest_json_mirror",
            "Do not prune blindly; candidate for dedupe after archive/session reconciliation.",
        ),
        Family(
            "canonical_static_json_archive",
            repo_root / "data" / "static_analysis" / "reports" / "archive",
            "*.json",
            "run_scoped_json_evidence",
            "Retain unless a session-level retirement report proves it is superseded.",
        ),
        Family(
            "static_report_cache",
            repo_root / "data" / "static_analysis" / "reports" / "_cache",
            "*.json",
            "rebuildable_cache",
            "Safe to remove if stale; can be rebuilt by build_report_package_index.",
        ),
        Family(
            "study_static_exposure_reports",
            repo_root / "output" / "reports" / "static_exposure_privacy",
            "*",
            "publication_derived_report",
            "Keep current candidate report; prune accidental or superseded timestamps by receipt.",
        ),
    ]


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Read-only audit of static-analysis report output families."
    )
    parser.add_argument("--repo-root", type=Path, default=Path.cwd())
    parser.add_argument("--output-dir", type=Path, default=None)
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    out_dir = args.output_dir or repo_root / "output" / "audit" / "static_report_output_audit" / _timestamp()
    out_dir.mkdir(parents=True, exist_ok=True)

    family_rows = [_family_stats(family) for family in _families(repo_root)]
    session_rows = _session_breakdown(repo_root / "data" / "static_analysis" / "reports" / "archive")
    prune_rows = [
        row
        for row in family_rows
        if row["classification"]
        in {
            "derived_latest_html_mirror",
            "derived_archive_html_mirror",
            "legacy_or_orphaned_html",
            "rebuildable_cache",
            "latest_json_mirror",
        }
        and int(row["file_count"]) > 0
    ]

    summary = {
        "generated_at": datetime.now(UTC).isoformat(),
        "repo_root": str(repo_root),
        "output_dir": str(out_dir),
        "families": family_rows,
        "archive_session_count": len(session_rows),
        "top_archive_sessions_by_bytes": session_rows[:25],
        "high_roi_findings": [
            "Per-APK HTML is a derived human mirror, not canonical evidence.",
            "Canonical per-APK JSON is the large report family and needs session-aware retirement, not bulk deletion.",
            "Publication study reports are separate derived workspaces and should be pruned by timestamp/contract.",
        ],
    }

    (out_dir / "summary.json").write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    _write_csv(
        out_dir / "path_families.csv",
        family_rows,
        [
            "name",
            "path",
            "exists",
            "pattern",
            "file_count",
            "bytes",
            "oldest_mtime_utc",
            "newest_mtime_utc",
            "classification",
            "recommendation",
        ],
    )
    _write_csv(
        out_dir / "archive_sessions.csv",
        session_rows,
        ["session", "path", "json_files", "bytes"],
    )
    _write_csv(
        out_dir / "prune_candidates.csv",
        prune_rows,
        ["name", "path", "file_count", "bytes", "classification", "recommendation"],
    )
    _write_generation_map(out_dir / "generation_map.md", family_rows)

    total_files = sum(int(row["file_count"]) for row in family_rows)
    total_bytes = sum(int(row["bytes"]) for row in family_rows)
    print(f"Audit written: {out_dir}")
    print(f"Report-family files: {total_files}")
    print(f"Report-family bytes: {total_bytes}")
    for row in family_rows:
        print(
            f"- {row['name']}: {row['file_count']} files, {row['bytes']} bytes, "
            f"{row['classification']}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
