"""SQL for database convenience views (reporting/consumption)."""

from __future__ import annotations

from .views_admin import (
    CREATE_V_ARTIFACT_REGISTRY_INTEGRITY,
    CREATE_V_CURRENT_ARTIFACT_REGISTRY,
)
from .views_bridge import (
    CREATE_V_RUN_IDENTITY,
    CREATE_V_RUN_OVERVIEW,
)
from .views_dynamic import (
    CREATE_V_PAPER_DYNAMIC_COHORT_V1,
    CREATE_V_RUNTIME_DYNAMIC_COHORT_STATUS_V1,
    CREATE_VW_DYNLOAD_HOTSPOTS,
)
from .views_inventory import (
    CREATE_VW_LATEST_APK_PER_PACKAGE,
)
from .views_permission import (
    CREATE_V_WEB_PERMISSION_INTEL_CURRENT,
    CREATE_VW_LATEST_PERMISSION_RISK,
    CREATE_VW_PERMISSION_AUDIT_LATEST,
)
from .views_static import (
    CREATE_V_MASVS_MATRIX,
    CREATE_V_STATIC_HANDOFF_V1,
    CREATE_V_STATIC_MASVS_FINDINGS_V1,
    CREATE_V_STATIC_MASVS_MATRIX_V1,
    CREATE_V_STATIC_MASVS_SESSION_SUMMARY_V1,
    CREATE_V_STATIC_RISK_SURFACES_V1,
    CREATE_VW_STATIC_FINDING_SURFACES_LATEST,
    CREATE_VW_STATIC_MODULE_COVERAGE,
    CREATE_VW_STATIC_RISK_SURFACES_LATEST,
    CREATE_VW_STORAGE_SURFACE_RISK,
)
from .views_web import (
    CREATE_V_WEB_APP_COMPONENT_ACL,
    CREATE_V_WEB_APP_COMPONENT_SUMMARY,
    CREATE_V_WEB_APP_COMPONENTS,
    CREATE_V_WEB_APP_DIRECTORY,
    CREATE_V_WEB_APP_FINDINGS,
    CREATE_V_WEB_APP_MASVS_LATEST_V1,
    CREATE_V_WEB_APP_PERMISSION_SUMMARY,
    CREATE_V_WEB_APP_PERMISSIONS,
    CREATE_V_WEB_APP_REPORT_SUMMARY,
    CREATE_V_WEB_APP_SESSIONS,
    CREATE_V_WEB_APP_STATIC_HANDOFF_READINESS_V1,
    CREATE_V_WEB_APP_STRING_SAMPLES,
    CREATE_V_WEB_APP_STRING_SUMMARY,
    CREATE_V_WEB_RUNTIME_RUN_DETAIL,
    CREATE_V_WEB_RUNTIME_RUN_INDEX,
    CREATE_V_WEB_STATIC_DYNAMIC_APP_SUMMARY,
    CREATE_V_WEB_STATIC_SESSION_HEALTH,
)

__all__ = [
    "CREATE_VW_LATEST_APK_PER_PACKAGE",
    "CREATE_VW_STATIC_RISK_SURFACES_LATEST",
    "CREATE_VW_STATIC_FINDING_SURFACES_LATEST",
    "CREATE_VW_STATIC_MODULE_COVERAGE",
    "CREATE_VW_STORAGE_SURFACE_RISK",
    "CREATE_V_MASVS_MATRIX",
    "CREATE_V_STATIC_HANDOFF_V1",
    "CREATE_V_STATIC_MASVS_FINDINGS_V1",
    "CREATE_V_STATIC_MASVS_MATRIX_V1",
    "CREATE_V_STATIC_MASVS_SESSION_SUMMARY_V1",
    "CREATE_V_STATIC_RISK_SURFACES_V1",
    "CREATE_VW_DYNLOAD_HOTSPOTS",
    "CREATE_V_RUNTIME_DYNAMIC_COHORT_STATUS_V1",
    "CREATE_V_PAPER_DYNAMIC_COHORT_V1",
    "CREATE_V_WEB_APP_DIRECTORY",
    "CREATE_V_WEB_RUNTIME_RUN_INDEX",
    "CREATE_V_WEB_RUNTIME_RUN_DETAIL",
    "CREATE_V_WEB_STATIC_SESSION_HEALTH",
    "CREATE_V_WEB_APP_SESSIONS",
    "CREATE_V_WEB_APP_FINDINGS",
    "CREATE_V_WEB_APP_PERMISSIONS",
    "CREATE_V_WEB_APP_PERMISSION_SUMMARY",
    "CREATE_V_WEB_APP_STRING_SUMMARY",
    "CREATE_V_WEB_APP_STRING_SAMPLES",
    "CREATE_V_WEB_APP_COMPONENTS",
    "CREATE_V_WEB_APP_COMPONENT_SUMMARY",
    "CREATE_V_WEB_APP_COMPONENT_ACL",
    "CREATE_V_WEB_APP_REPORT_SUMMARY",
    "CREATE_V_WEB_STATIC_DYNAMIC_APP_SUMMARY",
    "CREATE_V_WEB_APP_MASVS_LATEST_V1",
    "CREATE_V_WEB_APP_STATIC_HANDOFF_READINESS_V1",
    "CREATE_VW_LATEST_PERMISSION_RISK",
    "CREATE_VW_PERMISSION_AUDIT_LATEST",
    "CREATE_V_WEB_PERMISSION_INTEL_CURRENT",
    "CREATE_V_RUN_OVERVIEW",
    "CREATE_V_RUN_IDENTITY",
    "CREATE_V_ARTIFACT_REGISTRY_INTEGRITY",
    "CREATE_V_CURRENT_ARTIFACT_REGISTRY",
]
