"""Canonical event names for structured logs."""

RUN_START = "run.start"
RUN_END = "run.end"
RUN_ABORT_REQUESTED = "run.abort_requested"
RUN_PHASE = "run.phase"
STAGE_START = "stage.start"
STAGE_END = "stage.end"
REPORT_SAVED = "report.saved"
PERSIST_START = "persist.start"
PERSIST_APP = "persist.app"
PERSIST_END = "persist.end"
POLICY_FILTER = "policy.filter"
ARTIFACT_SAVED = "acquisition.artifact.saved"
ARTIFACT_SKIPPED = "acquisition.artifact.skipped"
DB_PERSIST = "db.persist"
DB_ERROR = "db.error"
ERROR_RUNTIME = "error.runtime"
ERROR_ADB = "adb.error"
