"""Shared domain-context classification rules for dynamic evidence interpretation."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


COMMON_TWO_PART_SUFFIXES = {
    "co.uk",
    "org.uk",
    "gov.uk",
    "ac.uk",
    "com.au",
    "net.au",
    "org.au",
    "edu.au",
    "co.jp",
    "com.br",
}


@dataclass(frozen=True)
class DomainReference:
    package_name_scope: str
    domain_pattern: str
    match_type: str
    owner_class: str
    role_class: str
    confidence: str
    classification_basis: str
    source_label: str = "repo_seed"
    source_url: str | None = None
    notes: str | None = None


def _norm_text(value: object) -> str:
    return str(value or "").strip()


def normalize_domain(value: Any) -> str:
    raw = _norm_text(value).lower()
    if not raw:
        return ""
    raw = raw.strip(" \t\r\n\"'()[]{}<>").rstrip(").,;")
    if raw.startswith("*."):
        raw = raw[2:]
    if "://" in raw:
        raw = raw.split("://", 1)[1]
    raw = raw.split("/", 1)[0].split("?", 1)[0].split("#", 1)[0]
    if ":" in raw:
        host, maybe_port = raw.rsplit(":", 1)
        if maybe_port.isdigit():
            raw = host
    if "." not in raw or ".." in raw:
        return ""
    allowed = set("abcdefghijklmnopqrstuvwxyz0123456789.-")
    if any(ch not in allowed for ch in raw):
        return ""
    return raw.strip(".-")


def root_domain(host: str) -> str:
    text = normalize_domain(host)
    if "." not in text:
        return text
    parts = [part for part in text.split(".") if part]
    if len(parts) < 2:
        return text
    tail = ".".join(parts[-2:])
    if len(parts) >= 3 and tail in COMMON_TWO_PART_SUFFIXES:
        return ".".join(parts[-3:])
    return tail


def suffix_match(domain: str, suffix: str) -> bool:
    return domain == suffix or domain.endswith(f".{suffix}")


def default_domain_references() -> tuple[DomainReference, ...]:
    return (
        DomainReference("", "a1.api.bbc.com", "EXACT", "first_party", "publisher_api", "high", "curated_exact"),
        DomainReference(
            "", "bbc-global-app.api.bbc.com", "EXACT", "first_party", "publisher_api", "high", "curated_exact"
        ),
        DomainReference("", "idcta.api.bbc.com", "EXACT", "first_party", "identity_api", "high", "curated_exact"),
        DomainReference("", "ichef.bbci.co.uk", "EXACT", "first_party", "content_delivery", "high", "curated_exact"),
        DomainReference(
            "bbc.mobile.news.ww",
            "www.bbc.com",
            "EXACT",
            "first_party",
            "publisher_content",
            "high",
            "curated_exact",
            source_url="https://www.bbc.com/",
        ),
        DomainReference(
            "bbc.mobile.news.ww",
            "mybbc-analytics.files.bbci.co.uk",
            "EXACT",
            "first_party",
            "publisher_collection",
            "high",
            "curated_exact",
            source_url="https://bbc.github.io/echo-docs/",
            notes="BBC Echo analytics assets are served from this hostname; retain as first-party analytics/publisher collection context.",
        ),
        DomainReference(
            "bbc.mobile.news.ww",
            "map-remote-config.files.bbci.co.uk",
            "EXACT",
            "first_party",
            "sdk_configuration",
            "medium",
            "curated_exact",
            source_url="https://www.bbc.com/",
            notes="BBC-observed remote-config hostname retained as package-scoped configuration delivery.",
        ),
        DomainReference(
            "bbc.mobile.news.ww",
            "static.files.bbci.co.uk",
            "EXACT",
            "first_party",
            "static_asset_delivery",
            "medium",
            "curated_exact",
            source_url="https://www.bbc.com/",
        ),
        DomainReference(
            "bbc.mobile.news.ww",
            "bbcx-internal.com",
            "SUFFIX",
            "first_party",
            "publisher_api",
            "medium",
            "curated_suffix",
            source_url="https://www.bbc.com",
            notes="Observed in current BBC News runtime traffic as a likely first-party live/app API endpoint.",
        ),
        DomainReference(
            "com.espn.score_center",
            "fan.api.espn.com",
            "EXACT",
            "first_party",
            "publisher_api",
            "high",
            "curated_exact",
            source_url="https://www.espn.com/",
        ),
        DomainReference(
            "com.espn.score_center",
            "pinpoint.espn.com",
            "EXACT",
            "first_party",
            "publisher_collection",
            "medium",
            "curated_exact",
            source_url="https://www.espn.com/",
        ),
        DomainReference(
            "com.espn.score_center",
            "espn.api.edge.bamgrid.com",
            "EXACT",
            "first_party",
            "publisher_api",
            "medium",
            "curated_exact",
            source_url="https://thewaltdisneycompany.com/news/espn-subscription-streaming-service-launches-april-12/",
        ),
        DomainReference(
            "com.espn.score_center",
            "espn.connections.edge.bamgrid.com",
            "EXACT",
            "first_party",
            "publisher_api",
            "medium",
            "curated_exact",
            source_url="https://thewaltdisneycompany.com/news/espn-subscription-streaming-service-launches-april-12/",
        ),
        DomainReference("", "www.cnn.com", "EXACT", "first_party", "publisher_content", "high", "curated_exact"),
        DomainReference(
            "", "collector.cdp.cnn.com", "EXACT", "first_party", "publisher_collection", "medium", "curated_exact"
        ),
        DomainReference("", "zion.api.cnn.io", "EXACT", "first_party", "publisher_api", "medium", "curated_exact"),
        DomainReference(
            "com.cnn.mobile.android.phone",
            "politics-explorer-tiles-static.cnn.io",
            "EXACT",
            "first_party",
            "content_delivery",
            "medium",
            "curated_exact",
            source_url="https://www.codeandtheory.com/things-we-make/cnn-magic-wall-reinventing-an-iconic-media-star",
            notes="CNN-observed static tile hostname retained as first-party content delivery for politics/magic-wall style assets.",
        ),
        DomainReference(
            "com.cnn.mobile.android.phone",
            "ix.cnn.io",
            "EXACT",
            "first_party",
            "content_delivery",
            "medium",
            "curated_exact",
            source_url="https://ix.cnn.io/dailygraphics/graphics/20200306-us-covid19/parent.html",
            notes="CNN-owned interactive/dailygraphics hostname observed in current runtime traffic; treat as first-party content delivery for interactive assets.",
        ),
        DomainReference(
            "com.facebook.katana",
            "graph.facebook.com",
            "EXACT",
            "first_party",
            "social_graph_api",
            "high",
            "curated_exact",
        ),
        DomainReference(
            "com.facebook.orca",
            "graph.facebook.com",
            "EXACT",
            "first_party",
            "social_graph_api",
            "high",
            "curated_exact",
        ),
        DomainReference(
            "com.facebook.orca",
            "messenger.com",
            "SUFFIX",
            "first_party",
            "messaging_platform_api",
            "high",
            "curated_suffix",
            source_url="https://www.messenger.com/",
        ),
        DomainReference(
            "com.facebook.katana",
            "lookaside.facebook.com",
            "EXACT",
            "first_party",
            "content_delivery",
            "medium",
            "curated_exact",
            source_url="https://developers.facebook.com/docs/games/instant-games/sdk/fbinstant8.0/",
            notes="Meta developer docs reference lookaside.facebook.com for hosted resources; observed in current Facebook runtime traffic as a content/resource host.",
        ),
        DomainReference(
            "com.facebook.katana",
            "mobile.facebook.com",
            "EXACT",
            "first_party",
            "social_graph_api",
            "medium",
            "curated_exact",
            source_url="https://developers.facebook.com/documentation/development/terms-and-policies/automated-data-collection",
            notes="Package-scoped Facebook application/web surface observed in current runtime traffic; treat as first-party social graph access for the Facebook app.",
        ),
        DomainReference(
            "com.facebook.katana",
            "web.facebook.com",
            "EXACT",
            "first_party",
            "social_graph_api",
            "medium",
            "curated_exact",
            source_url="https://developers.facebook.com/documentation/development/terms-and-policies/automated-data-collection",
            notes="Package-scoped Facebook application/web surface observed in current runtime traffic; treat as first-party social graph access for the Facebook app.",
        ),
        DomainReference(
            "com.facebook.katana",
            "www.facebook.com",
            "EXACT",
            "first_party",
            "social_graph_api",
            "medium",
            "curated_exact",
            source_url="https://developers.facebook.com/documentation/development/terms-and-policies/automated-data-collection",
            notes="Package-scoped Facebook application/web surface observed in current runtime traffic; treat as first-party social graph access for the Facebook app.",
        ),
        DomainReference(
            "com.facebook.katana",
            "b-www.facebook.com",
            "EXACT",
            "first_party",
            "social_graph_api",
            "medium",
            "curated_exact",
            source_url="https://developers.facebook.com/documentation/development/terms-and-policies/automated-data-collection",
            notes="Package-scoped Facebook web-surface hostname observed in current runtime traffic; retained as first-party social graph/web access for the Facebook app.",
        ),
        DomainReference(
            "com.facebook.katana",
            "gateway.facebook.com",
            "EXACT",
            "first_party",
            "social_graph_api",
            "medium",
            "curated_exact",
            source_url="https://developers.facebook.com/docs/graph-api/",
            notes="Package-scoped Facebook gateway hostname observed in current runtime traffic; retained as first-party social graph/platform control traffic.",
        ),
        DomainReference(
            "com.facebook.katana",
            "genai-graph.facebook.com",
            "EXACT",
            "first_party",
            "social_graph_api",
            "medium",
            "curated_exact",
            source_url="https://developers.facebook.com/documentation/ads-commerce/marketing-api/creative/generative-ai-features",
            notes="Package-scoped Meta generative-AI graph hostname observed in current runtime traffic; retained under first-party social graph/platform API semantics.",
        ),
        DomainReference(
            "com.facebook.katana",
            "z-m-gateway.facebook.com",
            "EXACT",
            "first_party",
            "social_graph_api",
            "medium",
            "curated_exact",
            source_url="https://developers.facebook.com/docs/graph-api/",
            notes="Package-scoped Facebook gateway hostname observed in current runtime traffic; retained as first-party social graph/platform control traffic.",
        ),
        DomainReference(
            "com.facebook.katana",
            "graph-fallback.facebook.com",
            "EXACT",
            "first_party",
            "social_graph_api",
            "medium",
            "curated_exact",
            source_url="https://developers.facebook.com/docs/graph-api/",
            notes="Package-scoped Facebook fallback graph hostname observed in current runtime traffic; retained as first-party social graph access.",
        ),
        DomainReference(
            "com.facebook.katana",
            "b-api.facebook.com",
            "EXACT",
            "first_party",
            "social_graph_api",
            "medium",
            "curated_exact",
            source_url="https://developers.facebook.com/docs/graph-api/",
            notes="Package-scoped Facebook API hostname observed in current app runtime traffic.",
        ),
        DomainReference(
            "com.facebook.katana",
            "mqtt-mini.facebook.com",
            "EXACT",
            "first_party",
            "realtime_messaging",
            "medium",
            "curated_exact",
            source_url="https://developers.facebook.com/docs/messenger-platform/",
            notes="Package-scoped Facebook realtime transport hostname observed in current app runtime traffic.",
        ),
        DomainReference(
            "com.instagram.android",
            "graph.facebook.com",
            "EXACT",
            "first_party",
            "social_graph_api",
            "high",
            "curated_exact",
        ),
        DomainReference(
            "com.whatsapp",
            "graph.whatsapp.com",
            "EXACT",
            "first_party",
            "messaging_platform_api",
            "high",
            "curated_exact",
            source_url="https://developers.facebook.com/docs/whatsapp/cloud-api/",
            notes="WhatsApp-owned graph endpoint observed in current-build runtime traffic; classified as first-party messaging platform API.",
        ),
        DomainReference(
            "com.whatsapp",
            "api.whatsapp.net",
            "EXACT",
            "first_party",
            "messaging_platform_api",
            "high",
            "curated_exact",
            source_url="https://developers.facebook.com/docs/whatsapp/cloud-api/",
            notes="WhatsApp API endpoint observed in current-build runtime traffic; classified as first-party messaging platform API.",
        ),
        DomainReference(
            "com.whatsapp",
            "acs.whatsapp.com",
            "EXACT",
            "first_party",
            "messaging_platform_api",
            "medium",
            "curated_exact",
            source_url="https://developers.facebook.com/documentation/business-messaging/whatsapp/overview",
            notes="WhatsApp application control/service hostname observed in current-build runtime traffic; treated as first-party messaging platform control/API traffic.",
        ),
        DomainReference(
            "com.whatsapp",
            "v.whatsapp.net",
            "EXACT",
            "first_party",
            "realtime_call_transport",
            "medium",
            "curated_exact",
            source_url="https://www.whatsapp.com/security/",
            notes="Dominant runtime call/video transport hostname observed during connected WhatsApp calling activity.",
        ),
        DomainReference(
            "com.instagram.android",
            "v.whatsapp.net",
            "EXACT",
            "first_party",
            "realtime_call_transport",
            "medium",
            "curated_exact",
            source_url="https://www.whatsapp.com/security/",
            notes="Package-scoped Meta/WhatsApp transport hostname observed during Instagram runtime traffic.",
        ),
        DomainReference(
            "com.facebook.orca",
            "v.whatsapp.net",
            "EXACT",
            "first_party",
            "realtime_call_transport",
            "medium",
            "curated_exact",
            source_url="https://www.whatsapp.com/security/",
            notes="Package-scoped Meta/WhatsApp transport hostname observed during Messenger runtime traffic.",
        ),
        DomainReference(
            "com.whatsapp",
            "g.whatsapp.net",
            "EXACT",
            "first_party",
            "realtime_messaging",
            "medium",
            "curated_exact",
            source_url="https://www.whatsapp.com/security/",
            notes="WhatsApp realtime transport/signaling hostname observed during current-build messaging traffic.",
        ),
        DomainReference(
            "com.whatsapp",
            "mmg.whatsapp.net",
            "EXACT",
            "first_party",
            "media_delivery",
            "medium",
            "curated_exact",
            source_url="https://developers.facebook.com/docs/whatsapp/cloud-api/reference/media",
            notes="WhatsApp media-delivery hostname observed in current-build runtime traffic.",
        ),
        DomainReference(
            "com.whatsapp",
            "scontent.whatsapp.net",
            "EXACT",
            "first_party",
            "content_delivery",
            "medium",
            "curated_exact",
            source_url="https://www.whatsapp.com/security/",
            notes="WhatsApp first-party content/media delivery hostname observed in current-build runtime traffic.",
        ),
        DomainReference(
            "com.whatsapp",
            "static.whatsapp.net",
            "EXACT",
            "first_party",
            "static_asset_delivery",
            "medium",
            "curated_exact",
            source_url="https://www.whatsapp.com/security/",
            notes="WhatsApp static asset delivery hostname observed in current-build runtime traffic.",
        ),
        DomainReference(
            "com.whatsapp",
            "cdn.whatsapp.net",
            "SUFFIX",
            "first_party",
            "content_delivery",
            "medium",
            "curated_suffix",
            source_url="https://www.whatsapp.com/security/",
            notes="WhatsApp CDN hostname family used for current-build media/content delivery.",
        ),
        DomainReference("", "graph.facebook.com", "EXACT", "third_party", "social_graph_api", "medium", "curated_exact"),
        DomainReference(
            "com.facebook.katana",
            "b-graph.facebook.com",
            "EXACT",
            "first_party",
            "social_graph_api",
            "medium",
            "curated_exact",
            source_url="https://developers.facebook.com/docs/graph-api/",
            notes="Graph-service variant inferred from hostname pattern and official Graph API documentation.",
        ),
        DomainReference(
            "",
            "b-graph.facebook.com",
            "EXACT",
            "third_party",
            "social_graph_api",
            "medium",
            "curated_exact",
            source_url="https://developers.facebook.com/docs/graph-api/",
            notes="Graph-service variant inferred from hostname pattern and official Graph API documentation.",
        ),
        DomainReference(
            "com.facebook.katana",
            "connect.facebook.net",
            "EXACT",
            "first_party",
            "identity_api",
            "medium",
            "curated_exact",
            source_url="https://developers.facebook.com/docs/javascript/quickstart/",
            notes="Meta JavaScript SDK / Pixel bootstrap host.",
        ),
        DomainReference(
            "",
            "connect.facebook.net",
            "EXACT",
            "third_party",
            "identity_api",
            "medium",
            "curated_exact",
            source_url="https://developers.facebook.com/docs/javascript/quickstart/",
            notes="Meta JavaScript SDK / Pixel bootstrap host.",
        ),
        DomainReference(
            "com.facebook.katana",
            "edge-mqtt.facebook.com",
            "EXACT",
            "first_party",
            "realtime_messaging",
            "high",
            "curated_exact",
        ),
        DomainReference(
            "com.facebook.orca",
            "edge-mqtt.facebook.com",
            "EXACT",
            "first_party",
            "realtime_messaging",
            "high",
            "curated_exact",
        ),
        DomainReference(
            "com.instagram.android",
            "edge-mqtt.facebook.com",
            "EXACT",
            "first_party",
            "realtime_messaging",
            "high",
            "curated_exact",
        ),
        DomainReference(
            "",
            "edge-mqtt.facebook.com",
            "EXACT",
            "third_party",
            "realtime_messaging",
            "medium",
            "curated_exact",
        ),
        DomainReference(
            "com.facebook.orca",
            "chat-e2ee-mini.facebook.com",
            "EXACT",
            "first_party",
            "messaging_e2ee",
            "high",
            "curated_exact",
        ),
        DomainReference(
            "com.facebook.katana",
            "chat-e2ee-mini.facebook.com",
            "EXACT",
            "first_party",
            "messaging_e2ee",
            "medium",
            "curated_exact",
        ),
        DomainReference(
            "",
            "chat-e2ee-mini.facebook.com",
            "EXACT",
            "third_party",
            "messaging_e2ee",
            "medium",
            "curated_exact",
        ),
        DomainReference(
            "com.facebook.katana",
            "payments-graph.facebook.com",
            "EXACT",
            "first_party",
            "payments_api",
            "high",
            "curated_exact",
        ),
        DomainReference(
            "com.instagram.android",
            "payments-graph.facebook.com",
            "EXACT",
            "first_party",
            "payments_api",
            "high",
            "curated_exact",
        ),
        DomainReference(
            "",
            "payments-graph.facebook.com",
            "EXACT",
            "third_party",
            "payments_api",
            "medium",
            "curated_exact",
        ),
        DomainReference("", "urbanairship.com", "SUFFIX", "third_party", "engagement_push", "high", "curated_suffix"),
        DomainReference("", "chartbeat.net", "SUFFIX", "third_party", "analytics_measurement", "high", "curated_suffix"),
        DomainReference(
            "", "scorecardresearch.com", "SUFFIX", "third_party", "audience_measurement", "high", "curated_suffix"
        ),
        DomainReference(
            "",
            "piano.io",
            "SUFFIX",
            "third_party",
            "subscription_paywall",
            "high",
            "curated_suffix",
            source_url="https://piano.io/marketing/product/ad-revenue-insights-dynamic-paywall",
        ),
        DomainReference(
            "", "permutive.app", "SUFFIX", "third_party", "audience_personalization", "high", "curated_suffix"
        ),
        DomainReference(
            "",
            "permutive.com",
            "SUFFIX",
            "third_party",
            "audience_personalization",
            "high",
            "curated_suffix",
            source_url="https://permutive.com/",
        ),
        DomainReference(
            "",
            "rlcdn.com",
            "SUFFIX",
            "third_party",
            "identity_sync",
            "high",
            "curated_suffix",
            source_url="https://docs.liveramp.com/identity/en/implementing-liveramp-s-cookie-sync-tag.html",
        ),
        DomainReference(
            "",
            "dianomi.com",
            "SUFFIX",
            "third_party",
            "adtech_monetization",
            "high",
            "curated_suffix",
            source_url="https://www.dianomi.com/who-we-help/publishers/",
        ),
        DomainReference(
            "",
            "amazon-adsystem.com",
            "SUFFIX",
            "third_party",
            "adtech_monetization",
            "medium",
            "curated_suffix",
            source_url="https://advertising.amazon.com/",
        ),
        DomainReference(
            "",
            "media-amazon.com",
            "SUFFIX",
            "third_party",
            "content_delivery",
            "medium",
            "curated_suffix",
            source_url="https://webservices.amazon.com/paapi5/documentation/images.html",
            notes="Amazon Product Advertising API image examples use m.media-amazon.com image URLs; classify generic observations as Amazon-hosted media delivery unless a package-scoped mapping overrides it.",
        ),
        DomainReference(
            "",
            "infosecworldusa.com",
            "SUFFIX",
            "third_party",
            "conference_site_content",
            "medium",
            "curated_suffix",
            source_url="https://www.infosecworldusa.com/",
            notes="Observed from Facebook external navigation; classify as third-party conference site content, not Facebook infrastructure.",
        ),
        DomainReference(
            "",
            "swoogo.com",
            "SUFFIX",
            "third_party",
            "event_platform_assets",
            "medium",
            "curated_suffix",
            source_url="https://swoogo.events/platform/",
            notes="Swoogo event-management asset host observed alongside InfoSec World external-page traffic.",
        ),
        DomainReference(
            "",
            "steampowered.com",
            "SUFFIX",
            "third_party",
            "external_storefront_content",
            "high",
            "curated_suffix",
            source_url="https://store.steampowered.com/about/",
            notes="Observed from Facebook external navigation to Steam storefront content.",
        ),
        DomainReference(
            "",
            "steamstatic.com",
            "SUFFIX",
            "third_party",
            "static_asset_delivery",
            "medium",
            "curated_suffix",
            source_url="https://store.steampowered.com/privacy_agreement/",
            notes="Steam static/CDN host observed with Steam storefront traffic.",
        ),
        DomainReference(
            "com.guardian",
            "media-amazon.com",
            "SUFFIX",
            "third_party",
            "ad_creative_delivery",
            "medium",
            "curated_suffix",
            source_url="https://advertising.amazon.com/solutions/products/sponsored-products-across-retailers",
            notes="Observed in Guardian runtime traffic as Amazon-hosted media delivery alongside other ad-tech endpoints; treat conservatively as ad creative delivery.",
        ),
        DomainReference(
            "com.guardian",
            "a9.amazon.dev",
            "SUFFIX",
            "third_party",
            "adtech_monetization",
            "medium",
            "curated_suffix",
            source_url="https://advertising.amazon.com/",
            notes="Observed in Guardian runtime traffic under adsqtungsten.a9.amazon.dev; retain as Amazon ad-tech infrastructure.",
        ),
        DomainReference(
            "com.guardian",
            "unagi-na.amazon.com",
            "EXACT",
            "third_party",
            "ad_measurement",
            "low",
            "curated_exact",
            source_url="https://advertising.amazon.com/",
            notes="Observed in Guardian runtime traffic with other Amazon advertising hosts; classify conservatively as Amazon-owned ad measurement/edge context.",
        ),
        DomainReference(
            "com.guardian",
            "tq-tungsten.com",
            "SUFFIX",
            "third_party",
            "ad_measurement",
            "medium",
            "curated_suffix",
            source_url="https://advertising.amazon.com/",
            notes="Observed in Guardian runtime traffic with adsqtungsten/a9.amazon.dev hosts; treat as advertising measurement edge infrastructure.",
        ),
        DomainReference("", "doubleclick.net", "SUFFIX", "third_party", "adtech_monetization", "high", "curated_suffix"),
        DomainReference(
            "",
            "fwmrm.net",
            "SUFFIX",
            "third_party",
            "adtech_video_monetization",
            "high",
            "curated_suffix",
            source_url="https://www.freewheel.com/",
        ),
        DomainReference(
            "", "googlesyndication.com", "SUFFIX", "third_party", "adtech_monetization", "high", "curated_suffix"
        ),
        DomainReference(
            "",
            "googletagservices.com",
            "SUFFIX",
            "third_party",
            "tag_delivery",
            "high",
            "curated_suffix",
            source_url="https://support.google.com/admanager/answer/181073?hl=en",
        ),
        DomainReference(
            "",
            "imasdk.googleapis.com",
            "EXACT",
            "third_party",
            "adtech_monetization",
            "medium",
            "curated_exact",
            source_url="https://developers.google.com/interactive-media-ads",
        ),
        DomainReference(
            "bbc.mobile.news.ww",
            "creative-assets.everesttech.net",
            "EXACT",
            "third_party",
            "ad_creative_delivery",
            "medium",
            "curated_exact",
            source_url="https://experienceleague.adobe.com/en/docs/core-services/interface/data-collection/cookies/advertising",
            notes="BBC-observed Adobe Advertising asset hostname retained as third-party ad creative delivery.",
        ),
        DomainReference(
            "",
            "firebaselogging-pa.googleapis.com",
            "EXACT",
            "third_party",
            "google_api_platform",
            "medium",
            "curated_exact",
            source_url="https://firebase.google.com/docs/perf-mon/get-started-web",
        ),
        DomainReference(
            "",
            "firebaselogging.googleapis.com",
            "EXACT",
            "third_party",
            "google_api_platform",
            "medium",
            "curated_exact",
            source_url="https://firebase.google.com/docs/analytics",
            notes="Firebase logging endpoint classification inferred from hostname naming and official Firebase analytics platform documentation.",
        ),
        DomainReference(
            "",
            "firebaseremoteconfig.googleapis.com",
            "EXACT",
            "third_party",
            "google_api_platform",
            "medium",
            "curated_exact",
            source_url="https://firebase.google.com/docs/remote-config",
            notes="Firebase Remote Config endpoint classification inferred from hostname naming and official Firebase Remote Config documentation.",
        ),
        DomainReference(
            "",
            "time.google.com",
            "EXACT",
            "third_party",
            "google_infrastructure",
            "medium",
            "curated_exact",
            source_url="https://developers.google.com/time",
        ),
        DomainReference(
            "",
            "whoami.akamai.net",
            "EXACT",
            "third_party",
            "network_diagnostics",
            "medium",
            "curated_exact",
            source_url="https://www.akamai.com/blog/developers/introducing-new-whoami-tool-dns-resolver-information",
            notes="Akamai diagnostic hostname used for resolver and edge information; classify as infrastructure rather than app first-party traffic.",
        ),
        DomainReference(
            "",
            "gpp-decoder.dianomi.workers.dev",
            "EXACT",
            "third_party",
            "adtech_monetization",
            "medium",
            "curated_exact",
            source_url="https://www.dianomi.com/",
            notes="Dianomi-hosted worker endpoint classification inferred from observed CNN runtime traffic and the hostname's Dianomi-specific subdomain.",
        ),
        DomainReference(
            "", "googlevideo.com", "SUFFIX", "third_party", "embedded_media_delivery", "medium", "curated_suffix"
        ),
        DomainReference("", "gstatic.com", "SUFFIX", "third_party", "google_infrastructure", "medium", "curated_suffix"),
        DomainReference(
            "",
            "litix.io",
            "SUFFIX",
            "third_party",
            "video_analytics_measurement",
            "medium",
            "curated_suffix",
            source_url="https://www.mux.com/docs/core/content-security-policy",
        ),
        DomainReference(
            "",
            "mediamelon.com",
            "SUFFIX",
            "third_party",
            "video_qoe_analytics",
            "high",
            "curated_suffix",
            source_url="https://docs.mediamelon.com/mediamelon",
            notes="Observed as register.mediamelon.com during CNN video playback; MediaMelon SmartSight is a streaming analytics/QoE platform.",
        ),
        DomainReference(
            "", "appsflyersdk.com", "SUFFIX", "third_party", "attribution_measurement", "high", "curated_suffix"
        ),
        DomainReference(
            "", "optimizely.com", "SUFFIX", "third_party", "experimentation_personalization", "high", "curated_suffix"
        ),
        DomainReference("", "doubleverify.com", "SUFFIX", "third_party", "ad_verification", "high", "curated_suffix"),
        DomainReference(
            "",
            "adsafeprotected.com",
            "SUFFIX",
            "third_party",
            "ad_verification",
            "high",
            "curated_suffix",
            source_url="https://integralads.com/innovation/",
        ),
        DomainReference(
            "",
            "brightline.tv",
            "SUFFIX",
            "third_party",
            "interactive_ctv_advertising",
            "high",
            "curated_suffix",
            source_url="https://brightline.tv/",
        ),
        DomainReference("", "2mdn.net", "SUFFIX", "third_party", "ad_creative_delivery", "high", "curated_suffix"),
        DomainReference("", "demdex.net", "SUFFIX", "third_party", "audience_identity", "high", "curated_suffix"),
        DomainReference("", "adobedtm.com", "SUFFIX", "third_party", "tag_delivery", "high", "curated_suffix"),
        DomainReference("", "admaster.cc", "SUFFIX", "third_party", "ad_measurement", "medium", "curated_suffix"),
        DomainReference(
            "",
            "newrelic.com",
            "SUFFIX",
            "third_party",
            "analytics_measurement",
            "medium",
            "curated_suffix",
            source_url="https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/configure-settings/",
        ),
        DomainReference(
            "",
            "bugsnag.com",
            "SUFFIX",
            "third_party",
            "crash_reporting",
            "high",
            "curated_suffix",
            source_url="https://developer.smartbear.com/bugsnag/docs/reporting-events-and-sessions",
            notes="Bugsnag documents error-reporting and session APIs under bugsnag.com / bugsnag.smartbear.com subdomains.",
        ),
        DomainReference(
            "",
            "vtwenty.com",
            "SUFFIX",
            "third_party",
            "audience_measurement",
            "medium",
            "curated_suffix",
            source_url="https://www.netify.ai/resources/domains/vtwenty.com",
            notes="Secondary source for hostname ownership; aligns with Nielsen DCR measurement materials.",
        ),
        DomainReference(
            "",
            "adtrafficquality.google",
            "SUFFIX",
            "third_party",
            "ad_measurement",
            "medium",
            "curated_suffix",
            source_url="https://support.google.com/google-ads/answer/2616016?hl=en",
        ),
        DomainReference(
            "",
            "flashtalking.com",
            "SUFFIX",
            "third_party",
            "ad_creative_delivery",
            "high",
            "curated_suffix",
            source_url="https://www.flashtalking.com/primary-ad-serving",
        ),
        DomainReference(
            "", "the-ozone-project.com", "SUFFIX", "third_party", "adtech_monetization", "high", "curated_suffix"
        ),
        DomainReference(
            "com.zhiliaoapp.musically",
            "config.mtp.sag.us-ashburn-1.oci.oraclecloud.com",
            "EXACT",
            "third_party",
            "hosted_backend_infrastructure",
            "medium",
            "curated_exact",
            source_url="https://newsroom.tiktok.com/en-us/delivering-on-our-us-data-governance",
            notes="TikTok-observed Oracle Cloud hostname. TikTok publicly describes routing US user traffic to Oracle Cloud Infrastructure; keep ownership third-party/shared infrastructure.",
        ),
        DomainReference(
            "",
            "oraclecloud.com",
            "SUFFIX",
            "third_party",
            "cloud_infrastructure",
            "medium",
            "curated_suffix",
            source_url="https://docs.cloud.oracle.com/",
        ),
        DomainReference(
            "bbc.mobile.news.ww", "bbc.com", "SUFFIX", "first_party", "first_party_misc", "medium", "package_root_hint"
        ),
        DomainReference(
            "bbc.mobile.news.ww",
            "bbc.co.uk",
            "SUFFIX",
            "first_party",
            "identity_api",
            "medium",
            "curated_suffix",
            source_url="https://www.bbc.com",
        ),
        DomainReference(
            "bbc.mobile.news.ww", "bbci.co.uk", "SUFFIX", "first_party", "first_party_misc", "medium", "package_root_hint"
        ),
        DomainReference(
            "com.cnn.mobile.android.phone", "cnn.com", "SUFFIX", "first_party", "first_party_misc", "medium", "package_root_hint"
        ),
        DomainReference(
            "com.cnn.mobile.android.phone", "cnn.io", "SUFFIX", "first_party", "first_party_misc", "medium", "package_root_hint"
        ),
        DomainReference(
            "com.cnn.mobile.android.phone",
            "audience.cnn.com",
            "EXACT",
            "first_party",
            "publisher_collection",
            "medium",
            "curated_exact",
            source_url="https://commercial.cnn.com/our-solutions/audience-insights/",
            notes="CNN first-party audience/insights hostname observed during app runtime traffic.",
        ),
        DomainReference(
            "com.cnn.mobile.android.phone",
            "smetrics.cnn.com",
            "EXACT",
            "first_party",
            "publisher_collection",
            "medium",
            "curated_exact",
            source_url="https://experienceleague.adobe.com/en/docs/analytics/implementation/vars/config-vars/trackingserver",
            notes="CNN first-party metrics hostname; smetrics-style hosts are commonly used as first-party analytics collection endpoints.",
        ),
        DomainReference(
            "com.cnn.mobile.android.phone",
            "ngtv.io",
            "SUFFIX",
            "first_party",
            "streaming_delivery",
            "medium",
            "curated_suffix",
            source_url="https://www.netify.ai/resources/hostnames/freeview.ngtv.io",
            notes="CNN/WB Discovery streaming-delivery hostname observed during app runtime traffic.",
        ),
        DomainReference(
            "com.cnn.mobile.android.phone",
            "discomax.com",
            "SUFFIX",
            "first_party",
            "streaming_platform_api",
            "medium",
            "curated_suffix",
            source_url="https://www.max.com/",
        ),
        DomainReference(
            "com.cnn.mobile.android.phone",
            "warnermediacdn.com",
            "SUFFIX",
            "first_party",
            "content_delivery",
            "medium",
            "curated_suffix",
            source_url="https://www.max.com/",
        ),
        DomainReference(
            "com.cnn.mobile.android.phone",
            "adobe.com",
            "SUFFIX",
            "third_party",
            "identity_api",
            "medium",
            "curated_suffix",
            source_url="https://experienceleague.adobe.com/en/docs/pass/authentication/home",
        ),
        DomainReference(
            "com.cnn.mobile.android.phone",
            "turner.com",
            "SUFFIX",
            "first_party",
            "content_delivery",
            "medium",
            "curated_suffix",
            source_url="https://www.cnn.com",
        ),
        DomainReference(
            "",
            "config.mapbox.com",
            "EXACT",
            "third_party",
            "sdk_configuration",
            "medium",
            "curated_exact",
            source_url="https://docs.mapbox.com/api/guides/",
        ),
        DomainReference(
            "",
            "api.mapbox.com",
            "EXACT",
            "third_party",
            "geospatial_api",
            "medium",
            "curated_exact",
            source_url="https://docs.mapbox.com/api/guides/",
            notes="Mapbox documents api.mapbox.com as the base path for its web services APIs; classify as third-party geospatial API context when observed in CNN runtime traffic.",
        ),
        DomainReference(
            "",
            "cloudflare.com",
            "SUFFIX",
            "third_party",
            "static_asset_delivery",
            "medium",
            "curated_suffix",
            source_url="https://cdnjs.com/about",
        ),
        DomainReference(
            "",
            "ampproject.org",
            "SUFFIX",
            "third_party",
            "content_delivery",
            "medium",
            "curated_suffix",
            source_url="https://developers.google.com/amp/cache/overview",
        ),
        DomainReference(
            "",
            "smartadserver.com",
            "SUFFIX",
            "third_party",
            "identity_sync",
            "medium",
            "curated_suffix",
            source_url="https://equativ.com/",
        ),
        DomainReference(
            "com.espn.score_center",
            "espn.com",
            "SUFFIX",
            "first_party",
            "first_party_misc",
            "medium",
            "package_root_hint",
            source_url="https://www.espn.com/",
        ),
        DomainReference(
            "com.espn.score_center",
            "bamgrid.com",
            "SUFFIX",
            "first_party",
            "first_party_misc",
            "medium",
            "package_root_hint",
            source_url="https://thewaltdisneycompany.com/news/espn-subscription-streaming-service-launches-april-12/",
        ),
        DomainReference(
            "com.facebook.katana", "facebook.com", "SUFFIX", "first_party", "first_party_misc", "medium", "package_root_hint"
        ),
        DomainReference(
            "com.facebook.katana",
            "fb.com",
            "SUFFIX",
            "first_party",
            "platform_shortlink_or_deep_link",
            "medium",
            "curated_suffix",
            source_url="https://developers.facebook.com/",
            notes="Package-scoped Meta/Facebook shortlink root observed in Facebook static endpoint samples.",
        ),
        DomainReference(
            "com.facebook.katana", "fbcdn.net", "SUFFIX", "first_party", "first_party_misc", "medium", "package_root_hint"
        ),
        DomainReference(
            "com.facebook.orca",
            "fbcdn.net",
            "SUFFIX",
            "first_party",
            "content_delivery",
            "medium",
            "curated_suffix",
            source_url="https://research.facebook.com/blog/2016/4/the-evolution-of-advanced-caching-in-the-facebook-cdn/",
            notes="Package-scoped Meta CDN mapping for Messenger-observed fbcdn.net media/static hosts.",
        ),
        DomainReference(
            "com.facebook.katana",
            "facebook.net",
            "SUFFIX",
            "first_party",
            "first_party_misc",
            "medium",
            "package_root_hint",
            source_url="https://developers.facebook.com/",
        ),
        DomainReference(
            "com.facebook.orca",
            "facebook.net",
            "SUFFIX",
            "first_party",
            "first_party_misc",
            "medium",
            "package_root_hint",
            source_url="https://developers.facebook.com/",
        ),
        DomainReference(
            "com.facebook.orca",
            "privacy-gateway.cloudflare.com",
            "SUFFIX",
            "third_party",
            "privacy_gateway",
            "medium",
            "curated_suffix",
            source_url="https://developers.cloudflare.com/privacy-gateway/",
            notes="Package-scoped Messenger privacy-gateway hostname; keep separate from generic Cloudflare CDN classification.",
        ),
        DomainReference(
            "com.instagram.android",
            "facebook.net",
            "SUFFIX",
            "first_party",
            "first_party_misc",
            "medium",
            "package_root_hint",
            source_url="https://developers.facebook.com/",
        ),
        DomainReference(
            "com.instagram.android",
            "fbcdn.net",
            "SUFFIX",
            "first_party",
            "content_delivery",
            "medium",
            "curated_suffix",
            source_url="https://www.netify.ai/resources/cdn/meta-cdn",
            notes="Package-scoped Meta CDN mapping for Instagram-observed fbcdn.net and FNA content-delivery hosts.",
        ),
        DomainReference(
            "com.instagram.android",
            "instagram.com",
            "SUFFIX",
            "first_party",
            "social_graph_api",
            "high",
            "curated_suffix",
            source_url="https://developers.facebook.com/docs/instagram-platform/",
        ),
        DomainReference(
            "com.instagram.android",
            "meta.com",
            "SUFFIX",
            "first_party",
            "platform_corporate_or_account_surface",
            "medium",
            "curated_suffix",
            source_url="https://developers.facebook.com/",
            notes="Package-scoped Meta platform/corporate root observed in Instagram static endpoint samples.",
        ),
        DomainReference(
            "com.instagram.android",
            "cdninstagram.com",
            "SUFFIX",
            "first_party",
            "content_delivery",
            "medium",
            "curated_suffix",
            source_url="https://developers.facebook.com/docs/instagram-platform/",
        ),
        DomainReference(
            "com.whatsapp",
            "whatsapp.com",
            "SUFFIX",
            "first_party",
            "first_party_misc",
            "medium",
            "package_root_hint",
            source_url="https://www.whatsapp.com/security/",
        ),
        DomainReference(
            "com.whatsapp",
            "whatsapp.net",
            "SUFFIX",
            "first_party",
            "first_party_misc",
            "medium",
            "package_root_hint",
            source_url="https://www.whatsapp.com/security/",
        ),
        DomainReference("", "facebook.com", "SUFFIX", "third_party", "social_graph_api", "medium", "curated_suffix"),
        DomainReference("", "facebook.net", "SUFFIX", "third_party", "social_graph_api", "medium", "curated_suffix"),
        DomainReference("", "fbcdn.net", "SUFFIX", "third_party", "content_delivery", "low", "curated_suffix"),
        DomainReference(
            "",
            "zoom.us",
            "SUFFIX",
            "third_party",
            "realtime_call_transport",
            "medium",
            "curated_suffix",
            source_url="https://developers.zoom.us/docs/meeting-sdk/",
            notes="Zoom-hosted meeting and webinar transport observed in current Facebook interactive evidence; keep generic so external meeting-link traffic is classified outside the Zoom app too.",
        ),
        DomainReference(
            "",
            "giphy.com",
            "SUFFIX",
            "third_party",
            "content_delivery",
            "medium",
            "curated_suffix",
            source_url="https://developers.giphy.com/docs/api/",
            notes="GIPHY-hosted GIF and sticker media delivery observed inside social app runtime traffic.",
        ),
        DomainReference(
            "com.facebook.katana",
            "cdninstagram.com",
            "SUFFIX",
            "first_party",
            "content_delivery",
            "medium",
            "curated_suffix",
            source_url="https://developers.facebook.com/docs/instagram-platform/instagram-api-with-instagram-login/get-started",
            notes="Package-scoped first-party content mapping for Instagram CDN traffic observed inside the Facebook app.",
        ),
        DomainReference(
            "com.guardian",
            "guardianapps.co.uk",
            "SUFFIX",
            "first_party",
            "publisher_api",
            "high",
            "curated_suffix",
            source_url="https://github.com/guardian/frontend",
            notes="The Guardian frontend repository documents api.nextgen.guardianapps.co.uk as the app Ajax URL; retain as package-scoped first-party API context.",
        ),
        DomainReference(
            "com.guardian",
            "ophan.theguardian.com",
            "EXACT",
            "first_party",
            "publisher_collection",
            "medium",
            "curated_exact",
            source_url="https://open-platform.theguardian.com/",
            notes="Guardian-owned Ophan telemetry endpoint observed during app runtime traffic.",
        ),
        DomainReference(
            "com.guardian",
            "ophan.co.uk",
            "SUFFIX",
            "first_party",
            "publisher_collection",
            "medium",
            "curated_suffix",
            source_url="https://open-platform.theguardian.com/",
            notes="Package-scoped Guardian Ophan telemetry alias observed as j.ophan.co.uk during app runtime traffic.",
        ),
        DomainReference(
            "com.guardian",
            "theguardian.com",
            "SUFFIX",
            "first_party",
            "publisher_content",
            "high",
            "curated_suffix",
            source_url="https://open-platform.theguardian.com/",
        ),
        DomainReference(
            "com.guardian",
            "guardianapis.com",
            "SUFFIX",
            "first_party",
            "publisher_api",
            "high",
            "curated_suffix",
            source_url="https://open-platform.theguardian.com/",
        ),
        DomainReference(
            "com.guardian",
            "guim.co.uk",
            "SUFFIX",
            "first_party",
            "content_delivery",
            "medium",
            "curated_suffix",
            source_url="https://www.theguardian.com/about",
        ),
        DomainReference(
            "com.guardian",
            "privacy-mgmt.com",
            "SUFFIX",
            "third_party",
            "consent_management",
            "high",
            "curated_suffix",
            source_url="https://developer.onetrust.com/onetrust/docs/introduction-to-cmp",
        ),
        DomainReference(
            "bbc.mobile.news.ww",
            "privacy-mgmt.com",
            "SUFFIX",
            "third_party",
            "consent_management",
            "medium",
            "curated_suffix",
            source_url="https://sourcepoint.com/",
            notes="Package-scoped BBC consent-management hostname observed in current runtime traffic.",
        ),
        DomainReference(
            "com.guardian",
            "braze.eu",
            "SUFFIX",
            "third_party",
            "engagement_push",
            "high",
            "curated_suffix",
            source_url="https://www.braze.com/docs/developer_guide/platform_integration_guides/android/",
        ),
        DomainReference(
            "com.guardian",
            "confiant-integrations.net",
            "SUFFIX",
            "third_party",
            "ad_security",
            "medium",
            "curated_suffix",
            source_url="https://www.confiant.com/",
        ),
        DomainReference(
            "com.guardian",
            "stats.mainroll.com",
            "EXACT",
            "third_party",
            "ad_measurement",
            "medium",
            "curated_exact",
            source_label="repo_seed_public_filter_list",
            source_url="https://easylist.to/easylist/easylist.txt",
            notes="Guardian-observed SNI-only endpoint. Live DNS resolves through CloudFront and HTTP(S) returns a 43-byte image/gif; EasyList blocks mainroll.com, so classify conservatively as ad-measurement pixel traffic.",
        ),
        DomainReference(
            "com.guardian",
            "3lift.com",
            "SUFFIX",
            "third_party",
            "programmatic_advertising",
            "medium",
            "curated_suffix",
            source_url="https://www.netify.ai/resources/domains/3lift.com",
            notes="Guardian-observed eb2.3lift.com traffic; 3lift.com is associated with TripleLift adtech.",
        ),
        DomainReference(
            "com.guardian",
            "rtb.adentifi.com",
            "EXACT",
            "third_party",
            "real_time_bidding",
            "medium",
            "curated_exact",
            source_url="https://www.netify.ai/resources/hostnames/rtb.adentifi.com",
            notes="Guardian-observed RTB hostname associated with AdTheorent advertising infrastructure.",
        ),
        DomainReference(
            "com.pinterest",
            "cdn-f.adsmoloco.com",
            "EXACT",
            "third_party",
            "ad_creative_delivery",
            "medium",
            "curated_exact",
            source_url="https://www.netify.ai/resources/hostnames/cdn-f.adsmoloco.com",
            notes="Pinterest-observed Moloco CDN/ad delivery hostname.",
        ),
        DomainReference(
            "",
            "crashlytics.com",
            "SUFFIX",
            "third_party",
            "crash_reporting",
            "high",
            "curated_suffix",
            source_url="https://firebase.google.com/docs/crashlytics",
        ),
        DomainReference(
            "",
            "adjust.com",
            "SUFFIX",
            "third_party",
            "attribution_measurement",
            "high",
            "curated_suffix",
            source_url="https://dev.adjust.com/en/sdk/android/",
        ),
        DomainReference(
            "com.twitter.android",
            "api.twitter.com",
            "EXACT",
            "first_party",
            "social_graph_api",
            "high",
            "curated_exact",
            source_url="https://docs.x.com/x-api/introduction",
        ),
        DomainReference(
            "com.twitter.android",
            "api-stream.twitter.com",
            "EXACT",
            "first_party",
            "social_graph_api",
            "high",
            "curated_exact",
            source_url="https://docs.x.com/x-api/introduction",
        ),
        DomainReference(
            "com.twitter.android",
            "api.x.com",
            "EXACT",
            "first_party",
            "social_graph_api",
            "high",
            "curated_exact",
            source_url="https://docs.x.com/x-api/introduction",
        ),
        DomainReference(
            "com.twitter.android",
            "analytics.twitter.com",
            "EXACT",
            "first_party",
            "analytics_measurement",
            "high",
            "curated_exact",
            source_url="https://docs.x.com/x-ads-api/analytics",
        ),
        DomainReference(
            "com.twitter.android",
            "chat-ws.x.com",
            "EXACT",
            "first_party",
            "realtime_engagement",
            "medium",
            "curated_exact",
            source_url="https://docs.x.com/x-api/introduction",
            notes="Observed current-build X runtime websocket endpoint; treat as first-party realtime engagement infrastructure.",
        ),
        DomainReference(
            "com.twitter.android",
            "x.com",
            "EXACT",
            "first_party",
            "social_graph_api",
            "medium",
            "curated_exact",
            source_url="https://docs.x.com/x-api/introduction",
        ),
        DomainReference(
            "com.twitter.android",
            "ads-api.x.com",
            "EXACT",
            "first_party",
            "ad_measurement",
            "medium",
            "curated_exact",
            source_url="https://docs.x.com/x-ads-api/introduction",
        ),
        DomainReference(
            "com.twitter.android",
            "probe.twitter.com",
            "EXACT",
            "first_party",
            "realtime_engagement",
            "medium",
            "curated_exact",
            source_url="https://www.netify.ai/resources/hostnames/probe.twitter.com",
            notes="Curated from observed X/Twitter runtime traffic and external hostname references indicating live-engagement/realtime probe behavior.",
        ),
        DomainReference(
            "com.twitter.android",
            "video-s.twimg.com",
            "EXACT",
            "first_party",
            "content_delivery",
            "high",
            "curated_exact",
            source_url="https://bugzilla.mozilla.org/show_bug.cgi?id=1977810",
            notes="Curated from observed X/Twitter runtime traffic and external webcompat evidence tying the hostname to Twitter/X video delivery.",
        ),
        DomainReference(
            "com.twitter.android",
            "twitter.com",
            "SUFFIX",
            "first_party",
            "social_graph_api",
            "medium",
            "package_root_hint",
            source_url="https://docs.x.com/x-api/introduction",
        ),
        DomainReference(
            "com.twitter.android",
            "twimg.com",
            "SUFFIX",
            "first_party",
            "content_delivery",
            "medium",
            "package_root_hint",
            source_url="https://developer.x.com/",
        ),
        DomainReference(
            "com.twitter.android",
            "x.com",
            "SUFFIX",
            "first_party",
            "first_party_misc",
            "medium",
            "package_root_hint",
            source_url="https://developer.x.com/",
        ),
        DomainReference(
            "com.linkedin.android",
            "static-akam.licdn.com",
            "EXACT",
            "first_party",
            "static_asset_delivery",
            "high",
            "curated_exact",
            source_url="https://www.linkedin.com/",
            notes="LinkedIn-observed static edge hostname retained as first-party static asset delivery.",
        ),
        DomainReference(
            "com.linkedin.android",
            "media.licdn.com",
            "EXACT",
            "first_party",
            "media_delivery",
            "high",
            "curated_exact",
            source_url="https://www.linkedin.com/",
            notes="LinkedIn-observed media edge hostname retained as first-party image/video delivery.",
        ),
        DomainReference(
            "com.linkedin.android",
            "dms.licdn.com",
            "EXACT",
            "first_party",
            "document_media_delivery",
            "medium",
            "curated_exact",
            source_url="https://www.linkedin.com/",
            notes="LinkedIn-observed document/media storage hostname retained as first-party content delivery.",
        ),
        DomainReference(
            "com.linkedin.android",
            "dms-akam.licdn.com",
            "EXACT",
            "first_party",
            "document_media_delivery",
            "medium",
            "curated_exact",
            source_url="https://www.linkedin.com/",
            notes="LinkedIn-observed Akamai-backed document/media edge hostname retained as first-party document/media delivery.",
        ),
        DomainReference(
            "com.linkedin.android",
            "static-cflr.licdn.com",
            "EXACT",
            "first_party",
            "static_asset_delivery",
            "medium",
            "curated_exact",
            source_url="https://www.linkedin.com/",
            notes="LinkedIn-observed Cloudflare-backed static edge hostname retained as first-party static asset delivery.",
        ),
        DomainReference(
            "com.linkedin.android",
            "static-fsly.licdn.com",
            "EXACT",
            "first_party",
            "static_asset_delivery",
            "medium",
            "curated_exact",
            source_url="https://www.linkedin.com/",
            notes="LinkedIn-observed Fastly-backed static edge hostname retained as first-party static asset delivery.",
        ),
        DomainReference(
            "com.linkedin.android",
            "pop-ltx1-lx.www.linkedin.com",
            "EXACT",
            "first_party",
            "content_delivery",
            "medium",
            "curated_exact",
            source_url="https://www.linkedin.com/",
            notes="LinkedIn-observed frontend edge hostname retained as first-party content delivery.",
        ),
        DomainReference(
            "com.linkedin.android",
            "pop-lva1-lx.www.linkedin.com",
            "EXACT",
            "first_party",
            "content_delivery",
            "medium",
            "curated_exact",
            source_url="https://www.linkedin.com/",
            notes="LinkedIn-observed frontend edge hostname retained as first-party content delivery.",
        ),
        DomainReference(
            "com.linkedin.android",
            "pop-lor1-lx.www.linkedin.com",
            "EXACT",
            "first_party",
            "content_delivery",
            "medium",
            "curated_exact",
            source_url="https://www.linkedin.com/",
            notes="LinkedIn-observed frontend edge hostname retained as first-party content delivery.",
        ),
        DomainReference(
            "com.linkedin.android",
            "perf.linkedin.com",
            "SUFFIX",
            "first_party",
            "performance_telemetry",
            "medium",
            "curated_suffix",
            source_url="https://www.linkedin.com/",
        ),
        DomainReference(
            "com.linkedin.android",
            "perf.linkedin-ei.com",
            "SUFFIX",
            "first_party",
            "performance_telemetry",
            "medium",
            "curated_suffix",
            source_url="https://www.linkedin.com/",
            notes="LinkedIn-observed performance/RUM host family, Cloudflare-backed in current runtime traffic.",
        ),
        DomainReference(
            "com.linkedin.android",
            "linkedin.com",
            "SUFFIX",
            "first_party",
            "social_graph_api",
            "high",
            "curated_suffix",
            source_url="https://www.linkedin.com/",
        ),
        DomainReference(
            "com.linkedin.android",
            "licdn.com",
            "SUFFIX",
            "first_party",
            "content_delivery",
            "medium",
            "curated_suffix",
            source_url="https://www.linkedin.com/",
        ),
        DomainReference(
            "com.linkedin.android",
            "protechts.net",
            "SUFFIX",
            "third_party",
            "bot_defense",
            "medium",
            "curated_suffix",
            source_url="https://www.humansecurity.com/",
            notes="Package-scoped LinkedIn bot-defense host family.",
        ),
        DomainReference(
            "com.linkedin.android",
            "xlgmedia.com",
            "SUFFIX",
            "third_party",
            "bot_defense",
            "medium",
            "curated_suffix",
            source_url="https://www.netify.ai/resources/domains/xlgmedia.com",
            notes="Observed during LinkedIn runtime traffic; Netify associates xlgmedia.com with HUMAN.",
        ),
        DomainReference(
            "com.linkedin.android",
            "ns1p.net",
            "SUFFIX",
            "third_party",
            "managed_dns_edge",
            "medium",
            "curated_suffix",
            source_url="https://www.ibm.com/products/ns1-connect",
        ),
        DomainReference(
            "com.pinterest",
            "pinterest.com",
            "SUFFIX",
            "first_party",
            "visual_discovery_api",
            "high",
            "curated_suffix",
            source_url="https://developers.pinterest.com/",
        ),
        DomainReference(
            "com.pinterest",
            "pinimg.com",
            "SUFFIX",
            "first_party",
            "content_delivery",
            "medium",
            "curated_suffix",
            source_url="https://developers.pinterest.com/",
        ),
        DomainReference(
            "com.pinterest",
            "recaptcha.net",
            "SUFFIX",
            "third_party",
            "bot_defense",
            "high",
            "curated_suffix",
            source_url="https://developers.google.com/recaptcha",
        ),
        DomainReference(
            "com.reddit.frontpage",
            "reddit.com",
            "SUFFIX",
            "first_party",
            "community_platform_api",
            "high",
            "curated_suffix",
            source_url="https://developers.reddit.com/docs/capabilities/server/reddit-api",
        ),
        DomainReference(
            "com.reddit.frontpage",
            "w3-reporting.reddit.com",
            "EXACT",
            "first_party",
            "first_party_telemetry_reporting",
            "medium",
            "curated_exact",
            source_url="https://www.reddit.com/policies/privacy-policy",
            notes="Observed during a current-build Reddit interactive feed/media capture; package-scoped so background app traffic is not relabeled as Reddit.",
        ),
        DomainReference(
            "com.reddit.frontpage",
            "alb.reddit.com",
            "EXACT",
            "first_party",
            "first_party_app_backend",
            "medium",
            "curated_exact",
            source_url="https://www.netify.ai/resources/hostnames/alb.reddit.com",
            notes="Observed during Reddit account/feed interactive capture; exact host retained separately from the broad reddit.com platform API suffix.",
        ),
        DomainReference(
            "com.reddit.frontpage",
            "redditforcommunity.com",
            "SUFFIX",
            "first_party",
            "community_moderator_resources",
            "medium",
            "curated_suffix",
            source_url="https://redditforcommunity.com/",
            notes="Reddit moderator/community resource root observed in Reddit static endpoint samples.",
        ),
        DomainReference(
            "com.reddit.frontpage",
            "redditspace.com",
            "SUFFIX",
            "first_party",
            "realtime_platform",
            "medium",
            "curated_suffix",
            source_url="https://www.netify.ai/resources/applications/reddit",
        ),
        DomainReference(
            "com.reddit.frontpage",
            "redd.it",
            "SUFFIX",
            "first_party",
            "content_delivery",
            "medium",
            "curated_suffix",
            source_url="https://www.netify.ai/resources/applications/reddit",
        ),
        DomainReference(
            "com.reddit.frontpage",
            "redditmedia.com",
            "SUFFIX",
            "first_party",
            "content_delivery",
            "medium",
            "curated_suffix",
            source_url="https://www.netify.ai/resources/applications/reddit",
        ),
        DomainReference(
            "com.reddit.frontpage",
            "redditstatic.com",
            "SUFFIX",
            "first_party",
            "static_asset_delivery",
            "medium",
            "curated_suffix",
            source_url="https://www.netify.ai/resources/applications/reddit",
        ),
        DomainReference(
            "com.reddit.frontpage",
            "devvit.net",
            "SUFFIX",
            "first_party",
            "reddit_developer_platform_webview",
            "high",
            "curated_suffix",
            source_url="https://developers.reddit.com/docs/capabilities/devvit-web/devvit_web_overview",
            notes="Observed in Reddit interactive PCAPs as webview.devvit.net/ad-cd-template-* webview content; Reddit documents Devvit Web as its web stack for Devvit apps.",
        ),
        DomainReference(
            "",
            "sng.link",
            "SUFFIX",
            "third_party",
            "attribution_deep_link",
            "medium",
            "curated_suffix",
            source_url="https://support.appsflyer.com/hc/en-us/articles/115005248543-OneLink-guide",
        ),
        DomainReference(
            "",
            "app.link",
            "SUFFIX",
            "third_party",
            "attribution_deep_link",
            "high",
            "curated_suffix",
            source_url="https://www.branch.io/deep-linking/",
        ),
        DomainReference(
            "",
            "impression.link",
            "SUFFIX",
            "third_party",
            "attribution_impression_tracking",
            "high",
            "curated_suffix",
            source_url="https://help.branch.io/marketer-hub/docs/ads-sans-faq",
        ),
        DomainReference(
            "",
            "boehringer-ingelheim.com",
            "SUFFIX",
            "third_party",
            "advertiser_landing_page",
            "medium",
            "curated_suffix",
            source_url="https://patient.boehringer-ingelheim.com/us/care-connect/",
        ),
        DomainReference(
            "com.snapchat.android",
            "snapchat.com",
            "SUFFIX",
            "first_party",
            "messaging_platform_api",
            "high",
            "curated_suffix",
            source_url="https://developers.snap.com/",
        ),
        DomainReference(
            "com.snapchat.android",
            "sc-cdn.net",
            "SUFFIX",
            "first_party",
            "content_delivery",
            "medium",
            "curated_suffix",
            source_url="https://developers.snap.com/",
        ),
        DomainReference(
            "org.thoughtcrime.securesms",
            "signal.org",
            "SUFFIX",
            "first_party",
            "encrypted_messaging_api",
            "high",
            "curated_suffix",
            source_url="https://signal.org/legal/",
        ),
        DomainReference(
            "org.thoughtcrime.securesms",
            "stun.cloudflare.com",
            "EXACT",
            "third_party",
            "stun_relay",
            "medium",
            "curated_exact",
            source_url="https://developers.cloudflare.com/realtime/turn/",
        ),
        DomainReference(
            "org.thoughtcrime.securesms",
            "turn.cloudflare.com",
            "EXACT",
            "third_party",
            "turn_relay",
            "medium",
            "curated_exact",
            source_url="https://developers.cloudflare.com/realtime/turn/",
        ),
        DomainReference(
            "",
            "firebaseinstallations.googleapis.com",
            "EXACT",
            "third_party",
            "installation_identity",
            "high",
            "curated_exact",
            source_url="https://firebase.google.com/docs/projects/manage-installations",
        ),
        DomainReference(
            "",
            "stun.l.google.com",
            "EXACT",
            "third_party",
            "stun_relay",
            "medium",
            "curated_exact",
            source_url="https://groups.google.com/g/discuss-webrtc/c/b-5alYpbxXw",
        ),
        DomainReference(
            "",
            "www.google.com",
            "EXACT",
            "third_party",
            "google_web",
            "medium",
            "curated_exact",
            source_url="https://www.google.com/",
        ),
        DomainReference(
            "",
            "googleapis.com",
            "SUFFIX",
            "third_party",
            "google_api_platform",
            "medium",
            "curated_suffix",
            source_url="https://developers.google.com/",
        ),
        DomainReference(
            "",
            "googleusercontent.com",
            "SUFFIX",
            "third_party",
            "content_delivery",
            "medium",
            "curated_suffix",
            source_url="https://www.netify.ai/resources/hostnames/play-lh.googleusercontent.com",
        ),
        DomainReference(
            "",
            "recaptcha.net",
            "SUFFIX",
            "third_party",
            "bot_defense",
            "high",
            "curated_suffix",
            source_url="https://developers.google.com/recaptcha",
        ),
        DomainReference(
            "",
            "appsflyer.com",
            "SUFFIX",
            "third_party",
            "attribution_measurement",
            "high",
            "curated_suffix",
            source_url="https://www.appsflyer.com/",
        ),
        DomainReference(
            "",
            "fpt.dfp.microsoft.com",
            "EXACT",
            "third_party",
            "device_fingerprinting",
            "high",
            "curated_exact",
            source_url="https://learn.microsoft.com/en-us/dynamics365/fraud-protection/df-web",
        ),
        DomainReference(
            "",
            "atdmt.com",
            "SUFFIX",
            "third_party",
            "adtech_monetization",
            "medium",
            "curated_suffix",
            source_url="https://learn.microsoft.com/en-us/xandr/bidders/creative-macro-check-service",
            notes="Microsoft/Xandr Atlas ad-serving and click-tracking infrastructure.",
        ),
        DomainReference(
            "com.zhiliaoapp.musically",
            "tiktok.com",
            "SUFFIX",
            "first_party",
            "social_video_platform",
            "high",
            "curated_suffix",
            source_url="https://developers.tiktok.com/doc/overview",
        ),
        DomainReference(
            "com.zhiliaoapp.musically",
            "tiktokcdn.com",
            "SUFFIX",
            "first_party",
            "content_delivery",
            "medium",
            "curated_suffix",
        ),
        DomainReference(
            "com.zhiliaoapp.musically",
            "tiktokcdn-us.com",
            "SUFFIX",
            "first_party",
            "content_delivery",
            "high",
            "package_root_hint",
        ),
        DomainReference(
            "com.zhiliaoapp.musically",
            "api16-normal-useast5.tiktokv.us",
            "EXACT",
            "first_party",
            "social_graph_api",
            "high",
            "curated_exact",
            source_url="https://www.netify.ai/resources/domains/tiktokv.us",
            notes="TikTok first-party API hostname observed in current dynamic captures.",
        ),
        DomainReference(
            "com.zhiliaoapp.musically",
            "aggr16-normal.tiktokv.us",
            "EXACT",
            "first_party",
            "performance_telemetry",
            "medium",
            "curated_exact",
            source_url="https://www.netify.ai/resources/domains/tiktokv.us",
            notes="TikTok first-party aggregation hostname observed repeatedly in dynamic captures.",
        ),
        DomainReference(
            "com.zhiliaoapp.musically",
            "aggr19-normal.tiktokv.us",
            "EXACT",
            "first_party",
            "performance_telemetry",
            "medium",
            "curated_exact",
            source_url="https://www.netify.ai/resources/domains/tiktokv.us",
            notes="TikTok first-party aggregation hostname observed repeatedly in dynamic captures.",
        ),
        DomainReference(
            "com.zhiliaoapp.musically",
            "tnc16-normal-useast5.tiktokv.us",
            "EXACT",
            "first_party",
            "sdk_configuration",
            "medium",
            "curated_exact",
            source_url="https://www.netify.ai/resources/domains/tiktokv.us",
            notes="TikTok first-party config/control hostname observed in dynamic captures.",
        ),
        DomainReference(
            "com.zhiliaoapp.musically",
            "ug-attribution.tiktokv.us",
            "EXACT",
            "first_party",
            "attribution_measurement",
            "medium",
            "curated_exact",
            source_url="https://www.netify.ai/resources/domains/tiktokv.us",
            notes="TikTok first-party attribution hostname observed in dynamic captures.",
        ),
        DomainReference(
            "com.zhiliaoapp.musically",
            "tiktok.adsmeasurement.com",
            "EXACT",
            "first_party",
            "ad_measurement",
            "medium",
            "curated_exact",
            source_url="https://ads.tiktok.com/business/en-US/products/measurement",
            notes="Package-scoped TikTok ads-measurement hostname observed in TikTok runtime traffic.",
        ),
        DomainReference(
            "com.zhiliaoapp.musically",
            "tiktokv.us",
            "SUFFIX",
            "first_party",
            "first_party_misc",
            "medium",
            "package_root_hint",
        ),
        DomainReference(
            "com.zhiliaoapp.musically",
            "ibyteimg.com",
            "SUFFIX",
            "first_party",
            "content_delivery",
            "medium",
            "package_root_hint",
        ),
    )


def classify_domain(
    domain: str,
    *,
    package_name: str,
    references: tuple[DomainReference, ...] | None = None,
) -> dict[str, str | bool]:
    domain_lc = normalize_domain(domain)
    root = root_domain(domain_lc)
    refs = references or default_domain_references()
    package_key = _norm_text(package_name).lower()

    exact_matches = [
        ref
        for ref in refs
        if ref.match_type.upper() == "EXACT"
        and normalize_domain(ref.domain_pattern) == domain_lc
        and (not ref.package_name_scope or ref.package_name_scope.lower() == package_key)
    ]
    exact_matches.sort(key=lambda ref: (0 if ref.package_name_scope else 1, len(ref.domain_pattern) * -1))
    if exact_matches:
        ref = exact_matches[0]
        return {
            "domain": domain_lc,
            "root_domain": root,
            "owner_class": ref.owner_class,
            "role_class": ref.role_class,
            "confidence": ref.confidence,
            "basis": ref.classification_basis,
            "match_type": ref.match_type.upper(),
            "package_name_scope": ref.package_name_scope,
            "first_party": ref.owner_class == "first_party",
        }

    suffix_refs = [
        ref
        for ref in refs
        if ref.match_type.upper() == "SUFFIX"
        and suffix_match(domain_lc, normalize_domain(ref.domain_pattern))
        and (not ref.package_name_scope or ref.package_name_scope.lower() == package_key)
    ]
    suffix_refs.sort(key=lambda ref: (0 if ref.package_name_scope else 1, len(ref.domain_pattern) * -1))
    if suffix_refs:
        ref = suffix_refs[0]
        role_class = ref.role_class
        if ref.classification_basis == "package_root_hint":
            if ".api." in domain_lc or domain_lc.startswith("api."):
                role_class = "publisher_api"
            elif "cdn" in domain_lc or "image" in domain_lc or "media" in domain_lc:
                role_class = "content_delivery"
        return {
            "domain": domain_lc,
            "root_domain": root,
            "owner_class": ref.owner_class,
            "role_class": role_class,
            "confidence": ref.confidence,
            "basis": ref.classification_basis,
            "match_type": ref.match_type.upper(),
            "package_name_scope": ref.package_name_scope,
            "first_party": ref.owner_class == "first_party",
        }

    return {
        "domain": domain_lc,
        "root_domain": root,
        "owner_class": "unknown",
        "role_class": "unknown",
        "confidence": "low",
        "basis": "unclassified",
        "match_type": "",
        "package_name_scope": "",
        "first_party": False,
    }


def default_domain_reference_seed_rows() -> list[dict[str, str | None]]:
    rows: list[dict[str, str | None]] = []
    for ref in default_domain_references():
        rows.append(
            {
                "package_name_scope": ref.package_name_scope,
                "domain_pattern": normalize_domain(ref.domain_pattern),
                "match_type": ref.match_type.upper(),
                "owner_class": ref.owner_class,
                "role_class": ref.role_class,
                "confidence": ref.confidence,
                "classification_basis": ref.classification_basis,
                "source_label": ref.source_label,
                "source_url": ref.source_url,
                "notes": ref.notes,
            }
        )
    return rows


__all__ = [
    "COMMON_TWO_PART_SUFFIXES",
    "DomainReference",
    "classify_domain",
    "default_domain_reference_seed_rows",
    "default_domain_references",
    "normalize_domain",
    "root_domain",
    "suffix_match",
]
