"""Shared service/provider context rules for dynamic network interpretation."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from scytaledroid.DynamicAnalysis.domain_context import normalize_domain, root_domain, suffix_match


@dataclass(frozen=True)
class ServiceCatalogEntry:
    service_key: str
    display_name: str
    owner_name: str
    owner_class: str
    service_category: str
    primary_use_case: str | None
    documentation_url: str | None = None
    privacy_policy_url: str | None = None
    source_label: str = "repo_seed"
    source_url: str | None = None
    confidence: str = "medium"
    notes: str | None = None


@dataclass(frozen=True)
class ServiceDomainMapEntry:
    service_key: str
    domain_pattern: str
    match_type: str
    package_name_scope: str = ""
    role_class: str | None = None
    source_label: str = "repo_seed"
    source_url: str | None = None
    confidence: str = "medium"
    notes: str | None = None


def _norm_text(value: object) -> str:
    return str(value or "").strip()


def default_service_catalog_entries() -> tuple[ServiceCatalogEntry, ...]:
    return (
        ServiceCatalogEntry(
            service_key="bbc_first_party",
            display_name="BBC First-Party Services",
            owner_name="BBC",
            owner_class="first_party",
            service_category="publisher",
            primary_use_case="news_content_and_api",
            source_url="https://www.bbc.com",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="cnn_first_party",
            display_name="CNN First-Party Services",
            owner_name="CNN",
            owner_class="first_party",
            service_category="publisher",
            primary_use_case="news_content_and_api",
            source_url="https://www.cnn.com",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="espn_first_party",
            display_name="ESPN First-Party Services",
            owner_name="ESPN / Disney",
            owner_class="first_party",
            service_category="publisher",
            primary_use_case="sports_content_and_api",
            source_url="https://www.espn.com/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="urbanairship",
            display_name="Airship",
            owner_name="Airship",
            owner_class="third_party",
            service_category="engagement",
            primary_use_case="push_and_customer_engagement",
            documentation_url="https://www.airship.com/",
            privacy_policy_url="https://www.airship.com/legal/privacy/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="google_ads",
            display_name="Google Ads / DoubleClick",
            owner_name="Google",
            owner_class="third_party",
            service_category="adtech",
            primary_use_case="advertising_and_monetization",
            documentation_url="https://support.google.com/admanager/",
            privacy_policy_url="https://policies.google.com/privacy",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="google_platform",
            display_name="Google Platform Infrastructure",
            owner_name="Google",
            owner_class="third_party",
            service_category="platform_infrastructure",
            primary_use_case="shared_platform_delivery",
            documentation_url="https://developers.google.com/",
            privacy_policy_url="https://policies.google.com/privacy",
            confidence="medium",
        ),
        ServiceCatalogEntry(
            service_key="akamai_diagnostics",
            display_name="Akamai Edge Diagnostics",
            owner_name="Akamai",
            owner_class="third_party",
            service_category="platform_infrastructure",
            primary_use_case="edge_resolution_and_network_diagnostics",
            documentation_url="https://www.akamai.com/blog/developers/introducing-new-whoami-tool-dns-resolver-information",
            source_url="https://www.akamai.com/blog/developers/introducing-new-whoami-tool-dns-resolver-information",
            confidence="medium",
            notes="Curated for Akamai diagnostic hostnames observed in dynamic traffic; treat as infrastructure/diagnostic context rather than app first-party service traffic.",
        ),
        ServiceCatalogEntry(
            service_key="chartbeat",
            display_name="Chartbeat",
            owner_name="Chartbeat",
            owner_class="third_party",
            service_category="analytics",
            primary_use_case="audience_measurement",
            documentation_url="https://chartbeat.com/",
            privacy_policy_url="https://chartbeat.com/privacy/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="doubleverify",
            display_name="DoubleVerify",
            owner_name="DoubleVerify",
            owner_class="third_party",
            service_category="ad_verification",
            primary_use_case="media_quality_and_ad_verification",
            documentation_url="https://doubleverify.com/company/about",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="dianomi",
            display_name="Dianomi",
            owner_name="Dianomi",
            owner_class="third_party",
            service_category="adtech",
            primary_use_case="native_advertising_and_publisher_monetization",
            documentation_url="https://www.dianomi.com/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="permutive",
            display_name="Permutive",
            owner_name="Permutive",
            owner_class="third_party",
            service_category="audience_personalization",
            primary_use_case="publisher_audience_activation",
            documentation_url="https://permutive.com/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="appsflyer",
            display_name="AppsFlyer",
            owner_name="AppsFlyer",
            owner_class="third_party",
            service_category="attribution",
            primary_use_case="install_attribution_and_engagement_measurement",
            documentation_url="https://www.appsflyer.com/",
            privacy_policy_url="https://www.appsflyer.com/legal/services-privacy-policy/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="liveramp",
            display_name="LiveRamp",
            owner_name="LiveRamp",
            owner_class="third_party",
            service_category="identity_and_adtech",
            primary_use_case="identity_resolution_and_cookie_sync",
            documentation_url="https://docs.liveramp.com/identity/en/implementing-liveramp-s-cookie-sync-tag.html",
            privacy_policy_url="https://liveramp.com/privacy/service-privacy-policy",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="flashtalking",
            display_name="Flashtalking / Innovid",
            owner_name="Innovid",
            owner_class="third_party",
            service_category="adtech",
            primary_use_case="ad_serving_and_creative_delivery",
            documentation_url="https://www.flashtalking.com/",
            privacy_policy_url="https://www.flashtalking.com/consumer-privacy",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="optimizely",
            display_name="Optimizely",
            owner_name="Optimizely",
            owner_class="third_party",
            service_category="experimentation",
            primary_use_case="experimentation_and_personalization",
            documentation_url="https://www.optimizely.com/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="piano",
            display_name="Piano",
            owner_name="Piano",
            owner_class="third_party",
            service_category="analytics",
            primary_use_case="analytics_and_customer_experience",
            documentation_url="https://www.piano.io/",
            confidence="medium",
        ),
        ServiceCatalogEntry(
            service_key="adobe_experience_cloud",
            display_name="Adobe Experience Cloud",
            owner_name="Adobe",
            owner_class="third_party",
            service_category="identity_and_tag_management",
            primary_use_case="identity_service_and_tag_delivery",
            documentation_url="https://experienceleague.adobe.com/en/docs/id-service/using/intro/cookies",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="integral_ad_science",
            display_name="Integral Ad Science",
            owner_name="Integral Ad Science",
            owner_class="third_party",
            service_category="ad_verification",
            primary_use_case="media_quality_and_brand_safety",
            documentation_url="https://integralads.com/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="amazon_ads",
            display_name="Amazon Ads",
            owner_name="Amazon",
            owner_class="third_party",
            service_category="adtech",
            primary_use_case="advertising_and_measurement",
            documentation_url="https://advertising.amazon.com/",
            confidence="medium",
        ),
        ServiceCatalogEntry(
            service_key="admaster",
            display_name="AdMaster",
            owner_name="AdMaster",
            owner_class="third_party",
            service_category="ad_measurement",
            primary_use_case="advertising_measurement_and_verification",
            documentation_url="https://www.admaster.com.cn/",
            confidence="medium",
        ),
        ServiceCatalogEntry(
            service_key="scorecardresearch",
            display_name="ScorecardResearch",
            owner_name="Comscore",
            owner_class="third_party",
            service_category="analytics",
            primary_use_case="audience_measurement",
            documentation_url="https://www.comscore.com/",
            privacy_policy_url="https://www.comscore.com/About/Privacy-Policy",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="new_relic",
            display_name="New Relic Mobile Monitoring",
            owner_name="New Relic",
            owner_class="third_party",
            service_category="analytics",
            primary_use_case="mobile_telemetry_and_monitoring",
            documentation_url="https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/configure-settings/",
            confidence="medium",
        ),
        ServiceCatalogEntry(
            service_key="nielsen_dcr",
            display_name="Nielsen Digital Content Ratings",
            owner_name="Nielsen",
            owner_class="third_party",
            service_category="analytics",
            primary_use_case="digital_audience_measurement",
            documentation_url="https://learning.nielsen.com/page/digital-content-ratings-dcr",
            source_url="https://www.netify.ai/resources/domains/vtwenty.com",
            confidence="medium",
            notes="Service association uses a secondary hostname source and should be treated as curated but reviewable.",
        ),
        ServiceCatalogEntry(
            service_key="ozone_project",
            display_name="The Ozone Project",
            owner_name="The Ozone Project",
            owner_class="third_party",
            service_category="adtech",
            primary_use_case="publisher_ad_exchange",
            documentation_url="https://www.theozoneproject.com/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="facebook_platform",
            display_name="Facebook / Meta Platform",
            owner_name="Meta",
            owner_class="first_party",
            service_category="social_platform",
            primary_use_case="social_graph_and_messaging",
            documentation_url="https://developers.facebook.com/",
            privacy_policy_url="https://www.facebook.com/privacy/policy/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="whatsapp_platform",
            display_name="WhatsApp / Meta Messaging Platform",
            owner_name="Meta",
            owner_class="first_party",
            service_category="social_platform",
            primary_use_case="messaging_calls_and_media_delivery",
            documentation_url="https://developers.facebook.com/docs/whatsapp/cloud-api/",
            privacy_policy_url="https://www.whatsapp.com/legal/privacy-policy",
            source_url="https://www.whatsapp.com/security/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="meta_sdk",
            display_name="Meta Platform SDK / APIs",
            owner_name="Meta",
            owner_class="third_party",
            service_category="social_platform",
            primary_use_case="social_graph_sdk_and_identity",
            documentation_url="https://developers.facebook.com/",
            privacy_policy_url="https://www.facebook.com/privacy/policy/",
            confidence="medium",
        ),
        ServiceCatalogEntry(
            service_key="x_platform",
            display_name="X / Twitter Platform",
            owner_name="X",
            owner_class="first_party",
            service_category="social_platform",
            primary_use_case="social_graph_and_platform_api",
            documentation_url="https://docs.x.com/x-api/introduction",
            source_url="https://developer.x.com/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="x_media_cdn",
            display_name="X / Twitter Media Delivery",
            owner_name="X",
            owner_class="first_party",
            service_category="content_delivery",
            primary_use_case="media_and_static_asset_delivery",
            documentation_url="https://developer.x.com/",
            source_url="https://devcommunity.x.com/t/pbs-twimg-com-cdn-problems/92623",
            confidence="medium",
            notes="Used for twimg-hosted media and static asset delivery observed during X/Twitter app runtime traffic.",
        ),
        ServiceCatalogEntry(
            service_key="x_ads_platform",
            display_name="X / Twitter Advertising Platform",
            owner_name="X",
            owner_class="first_party",
            service_category="adtech",
            primary_use_case="advertising_api_and_measurement",
            documentation_url="https://docs.x.com/x-api/introduction",
            source_url="https://developer.x.com/",
            confidence="medium",
            notes="Used for X/Twitter-owned advertising endpoints; treat as first-party ad/measurement context rather than third-party tracker by default.",
        ),
        ServiceCatalogEntry(
            service_key="guardian_first_party",
            display_name="Guardian First-Party Services",
            owner_name="Guardian News & Media",
            owner_class="first_party",
            service_category="publisher",
            primary_use_case="news_content_and_api",
            documentation_url="https://open-platform.theguardian.com/",
            source_url="https://open-platform.theguardian.com/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="onetrust_cmp",
            display_name="OneTrust Consent Management",
            owner_name="OneTrust",
            owner_class="third_party",
            service_category="consent_and_privacy",
            primary_use_case="consent_management_and_privacy_preferences",
            documentation_url="https://developer.onetrust.com/onetrust/docs/introduction-to-cmp",
            privacy_policy_url="https://www.onetrust.com/privacy-notice/",
            source_url="https://developer.onetrust.com/onetrust/docs/introduction-to-cmp",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="firebase_crashlytics",
            display_name="Firebase Crashlytics",
            owner_name="Google",
            owner_class="third_party",
            service_category="analytics",
            primary_use_case="crash_reporting_and_runtime_telemetry",
            documentation_url="https://firebase.google.com/docs/crashlytics",
            privacy_policy_url="https://firebase.google.com/support/privacy",
            source_url="https://firebase.google.com/docs/crashlytics",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="adjust_attribution",
            display_name="Adjust Attribution",
            owner_name="Adjust",
            owner_class="third_party",
            service_category="attribution",
            primary_use_case="install_attribution_and_reengagement_measurement",
            documentation_url="https://dev.adjust.com/en/sdk/android/",
            privacy_policy_url="https://www.adjust.com/terms/privacy-policy/",
            source_url="https://dev.adjust.com/en/sdk/android/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="microsoft_ads_atlas",
            display_name="Microsoft Advertising / Atlas",
            owner_name="Microsoft",
            owner_class="third_party",
            service_category="adtech",
            primary_use_case="ad_serving_click_tracking_and_measurement",
            documentation_url="https://learn.microsoft.com/en-us/xandr/bidders/creative-macro-check-service",
            confidence="medium",
            notes="Used for ATDMT / Atlas ad-serving and click-tracking infrastructure.",
        ),
        ServiceCatalogEntry(
            service_key="tiktok_platform",
            display_name="TikTok / ByteDance Platform",
            owner_name="ByteDance",
            owner_class="first_party",
            service_category="social_platform",
            primary_use_case="content_delivery_and_platform_control",
            documentation_url="https://developers.tiktok.com/",
            privacy_policy_url="https://www.tiktok.com/legal/privacy-policy",
            source_url="https://developers.tiktok.com/doc/display-api-get-started/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="turner_cnn_legacy",
            display_name="Turner / CNN Legacy Media Infrastructure",
            owner_name="Warner Bros. Discovery",
            owner_class="first_party",
            service_category="publisher",
            primary_use_case="legacy_media_delivery_and_auth",
            documentation_url="https://www.cnn.com",
            confidence="medium",
        ),
        ServiceCatalogEntry(
            service_key="wbd_streaming_platform",
            display_name="Warner Bros. Discovery Streaming Platform",
            owner_name="Warner Bros. Discovery",
            owner_class="first_party",
            service_category="platform_infrastructure",
            primary_use_case="cross_brand_streaming_api_and_delivery",
            documentation_url="https://www.max.com/",
            source_url="https://www.warnermediacdn.com/",
            confidence="medium",
            notes="Package-scoped mapping used for CNN-observed Warner/Max delivery and API domains; treat as curated first-party platform infrastructure rather than generic CDN traffic.",
        ),
        ServiceCatalogEntry(
            service_key="freewheel",
            display_name="FreeWheel",
            owner_name="FreeWheel / Comcast",
            owner_class="third_party",
            service_category="adtech",
            primary_use_case="streaming_video_ad_serving_and_monetization",
            documentation_url="https://www.freewheel.com/",
            privacy_policy_url="https://www.freewheel.com/privacy-policy",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="mux_data",
            display_name="Mux Data / Video Analytics",
            owner_name="Mux",
            owner_class="third_party",
            service_category="analytics",
            primary_use_case="video_playback_analytics_and_delivery_telemetry",
            documentation_url="https://www.mux.com/docs/core.txt",
            source_url="https://www.mux.com/docs/core.txt",
            confidence="medium",
            notes="Mux documentation explicitly references litix.io as part of Mux infrastructure.",
        ),
        ServiceCatalogEntry(
            service_key="brightline_ctv",
            display_name="BrightLine Interactive CTV",
            owner_name="BrightLine",
            owner_class="third_party",
            service_category="adtech",
            primary_use_case="interactive_ctv_advertising",
            documentation_url="https://brightline.tv/",
            source_url="https://brightline.tv/experience-library",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="oracle_cloud",
            display_name="Oracle Cloud Infrastructure",
            owner_name="Oracle",
            owner_class="third_party",
            service_category="platform_infrastructure",
            primary_use_case="cloud_infrastructure_and_hosting",
            documentation_url="https://docs.cloud.oracle.com/",
            source_url="https://www.oracle.com/cloud/",
            confidence="medium",
        ),
        ServiceCatalogEntry(
            service_key="mapbox_platform",
            display_name="Mapbox SDK / Platform",
            owner_name="Mapbox",
            owner_class="third_party",
            service_category="platform_infrastructure",
            primary_use_case="maps_sdk_configuration_and_geospatial_api",
            documentation_url="https://docs.mapbox.com/api/overview/",
            source_url="https://docs.mapbox.com/api/overview/",
            confidence="medium",
        ),
        ServiceCatalogEntry(
            service_key="cloudflare_cdnjs",
            display_name="Cloudflare CDNJS",
            owner_name="Cloudflare",
            owner_class="third_party",
            service_category="content_delivery",
            primary_use_case="static_asset_delivery_for_embedded_libraries",
            documentation_url="https://cdnjs.com/about",
            privacy_policy_url="https://www.cloudflare.com/privacypolicy/",
            source_url="https://cdnjs.com/about",
            confidence="medium",
        ),
        ServiceCatalogEntry(
            service_key="google_amp_cache",
            display_name="Google AMP Cache",
            owner_name="Google",
            owner_class="third_party",
            service_category="content_delivery",
            primary_use_case="amp_content_delivery_and_caching",
            documentation_url="https://developers.google.com/amp/cache/overview",
            privacy_policy_url="https://policies.google.com/privacy",
            source_url="https://developers.google.com/amp/cache/overview",
            confidence="medium",
        ),
        ServiceCatalogEntry(
            service_key="equativ_smartadserver",
            display_name="Equativ / Smart AdServer",
            owner_name="Equativ",
            owner_class="third_party",
            service_category="adtech",
            primary_use_case="ad_serving_and_identity_sync",
            documentation_url="https://equativ.com/",
            privacy_policy_url="https://equativ.com/privacy-policy/",
            source_url="https://equativ.com/",
            confidence="medium",
        ),
    )


def default_service_domain_map_entries() -> tuple[ServiceDomainMapEntry, ...]:
    return (
        ServiceDomainMapEntry("bbc_first_party", "bbc.com", "SUFFIX", "bbc.mobile.news.ww", "publisher_api", confidence="high"),
        ServiceDomainMapEntry("bbc_first_party", "bbc.co.uk", "SUFFIX", "bbc.mobile.news.ww", "identity_api", confidence="medium"),
        ServiceDomainMapEntry("bbc_first_party", "bbci.co.uk", "SUFFIX", "bbc.mobile.news.ww", "content_delivery", confidence="high"),
        ServiceDomainMapEntry(
            "bbc_first_party",
            "bbcx-internal.com",
            "SUFFIX",
            "bbc.mobile.news.ww",
            "publisher_api",
            source_url="https://www.bbc.com/",
            confidence="medium",
            notes="Observed in current BBC News runtime traffic as a likely first-party live/app API endpoint.",
        ),
        ServiceDomainMapEntry("cnn_first_party", "cnn.com", "SUFFIX", "com.cnn.mobile.android.phone", "publisher_content", confidence="high"),
        ServiceDomainMapEntry("cnn_first_party", "cnn.io", "SUFFIX", "com.cnn.mobile.android.phone", "publisher_api", confidence="medium"),
        ServiceDomainMapEntry("urbanairship", "urbanairship.com", "SUFFIX", role_class="engagement_push", confidence="high"),
        ServiceDomainMapEntry("dianomi", "dianomi.com", "SUFFIX", role_class="adtech_monetization", confidence="high"),
        ServiceDomainMapEntry("doubleverify", "doubleverify.com", "SUFFIX", role_class="ad_verification", confidence="high"),
        ServiceDomainMapEntry("permutive", "permutive.app", "SUFFIX", role_class="audience_personalization", confidence="high"),
        ServiceDomainMapEntry("permutive", "permutive.com", "SUFFIX", role_class="audience_personalization", confidence="high"),
        ServiceDomainMapEntry("appsflyer", "appsflyersdk.com", "SUFFIX", role_class="attribution_measurement", confidence="high"),
        ServiceDomainMapEntry("liveramp", "rlcdn.com", "SUFFIX", role_class="identity_sync", confidence="high"),
        ServiceDomainMapEntry("flashtalking", "flashtalking.com", "SUFFIX", role_class="ad_creative_delivery", confidence="high"),
        ServiceDomainMapEntry("optimizely", "optimizely.com", "SUFFIX", role_class="experimentation_personalization", confidence="high"),
        ServiceDomainMapEntry("piano", "piano.io", "SUFFIX", role_class="analytics_measurement", confidence="medium"),
        ServiceDomainMapEntry("adobe_experience_cloud", "adobedtm.com", "SUFFIX", role_class="tag_delivery", confidence="high"),
        ServiceDomainMapEntry("adobe_experience_cloud", "demdex.net", "SUFFIX", role_class="audience_identity", confidence="high"),
        ServiceDomainMapEntry("adobe_experience_cloud", "adobe.com", "SUFFIX", "com.cnn.mobile.android.phone", "identity_api", confidence="medium"),
        ServiceDomainMapEntry("integral_ad_science", "adsafeprotected.com", "SUFFIX", role_class="ad_verification", confidence="high"),
        ServiceDomainMapEntry("amazon_ads", "amazon-adsystem.com", "SUFFIX", role_class="adtech_monetization", confidence="medium"),
        ServiceDomainMapEntry("admaster", "admaster.cc", "SUFFIX", role_class="ad_measurement", confidence="medium"),
        ServiceDomainMapEntry("google_ads", "doubleclick.net", "SUFFIX", role_class="adtech_monetization", confidence="high"),
        ServiceDomainMapEntry("google_ads", "googlesyndication.com", "SUFFIX", role_class="adtech_monetization", confidence="high"),
        ServiceDomainMapEntry("google_ads", "2mdn.net", "SUFFIX", role_class="ad_creative_delivery", confidence="high"),
        ServiceDomainMapEntry("google_ads", "googletagservices.com", "SUFFIX", role_class="tag_delivery", confidence="high"),
        ServiceDomainMapEntry("google_ads", "adtrafficquality.google", "SUFFIX", role_class="ad_measurement", confidence="medium"),
        ServiceDomainMapEntry("google_ads", "imasdk.googleapis.com", "EXACT", role_class="adtech_monetization", confidence="medium"),
        ServiceDomainMapEntry("google_platform", "gstatic.com", "SUFFIX", role_class="google_infrastructure", confidence="medium"),
        ServiceDomainMapEntry("google_platform", "googlevideo.com", "SUFFIX", role_class="embedded_media_delivery", confidence="medium"),
        ServiceDomainMapEntry("google_platform", "googleapis.com", "SUFFIX", role_class="google_api_platform", confidence="medium"),
        ServiceDomainMapEntry(
            "akamai_diagnostics",
            "whoami.akamai.net",
            "EXACT",
            role_class="network_diagnostics",
            source_url="https://www.akamai.com/blog/developers/introducing-new-whoami-tool-dns-resolver-information",
            confidence="medium",
            notes="Akamai diagnostic hostname used to reveal resolver/edge information; keep scoped to exact host to avoid overclassifying generic Akamai CDN traffic.",
        ),
        ServiceDomainMapEntry("oracle_cloud", "oraclecloud.com", "SUFFIX", role_class="cloud_infrastructure", confidence="medium"),
        ServiceDomainMapEntry("mapbox_platform", "config.mapbox.com", "EXACT", "com.cnn.mobile.android.phone", "sdk_configuration", source_url="https://docs.mapbox.com/api/overview/", confidence="medium"),
        ServiceDomainMapEntry("cloudflare_cdnjs", "cloudflare.com", "SUFFIX", "com.cnn.mobile.android.phone", "static_asset_delivery", source_url="https://cdnjs.com/about", confidence="medium"),
        ServiceDomainMapEntry("google_amp_cache", "ampproject.org", "SUFFIX", "com.cnn.mobile.android.phone", "content_delivery", source_url="https://developers.google.com/amp/cache/overview", confidence="medium"),
        ServiceDomainMapEntry("equativ_smartadserver", "smartadserver.com", "SUFFIX", "com.cnn.mobile.android.phone", "identity_sync", source_url="https://equativ.com/", confidence="medium"),
        ServiceDomainMapEntry("chartbeat", "chartbeat.net", "SUFFIX", role_class="analytics_measurement", confidence="high"),
        ServiceDomainMapEntry("scorecardresearch", "scorecardresearch.com", "SUFFIX", role_class="audience_measurement", confidence="high"),
        ServiceDomainMapEntry("new_relic", "newrelic.com", "SUFFIX", role_class="analytics_measurement", confidence="medium"),
        ServiceDomainMapEntry("nielsen_dcr", "vtwenty.com", "SUFFIX", role_class="audience_measurement", confidence="medium"),
        ServiceDomainMapEntry("ozone_project", "the-ozone-project.com", "SUFFIX", role_class="adtech_monetization", confidence="high"),
        ServiceDomainMapEntry("turner_cnn_legacy", "turner.com", "SUFFIX", "com.cnn.mobile.android.phone", "content_delivery", confidence="medium"),
        ServiceDomainMapEntry("wbd_streaming_platform", "warnermediacdn.com", "SUFFIX", "com.cnn.mobile.android.phone", "content_delivery", source_url="https://www.max.com/", confidence="medium"),
        ServiceDomainMapEntry("wbd_streaming_platform", "discomax.com", "SUFFIX", "com.cnn.mobile.android.phone", "streaming_platform_api", source_url="https://www.max.com/", confidence="medium", notes="Curated from Warner/Max-branded hostname observed in CNN runtime traffic."),
        ServiceDomainMapEntry("wbd_streaming_platform", "ngtv.io", "SUFFIX", "com.cnn.mobile.android.phone", "streaming_delivery", source_url="https://www.max.com/", confidence="low", notes="Package-scoped curated mapping for CNN-observed streaming delivery hostname; keep reviewable."),
        ServiceDomainMapEntry("freewheel", "fwmrm.net", "SUFFIX", role_class="adtech_video_monetization", source_url="https://www.freewheel.com/", confidence="high"),
        ServiceDomainMapEntry("mux_data", "litix.io", "SUFFIX", role_class="video_analytics_measurement", source_url="https://www.mux.com/docs/core.txt", confidence="medium"),
        ServiceDomainMapEntry("brightline_ctv", "brightline.tv", "SUFFIX", role_class="interactive_ctv_advertising", source_url="https://brightline.tv/", confidence="high"),
        ServiceDomainMapEntry("dianomi", "dianomi.workers.dev", "SUFFIX", "com.cnn.mobile.android.phone", "adtech_monetization", source_url="https://www.dianomi.com/", confidence="medium", notes="Worker-domain suffix retained as a curated Dianomi monetization edge mapping."),
        ServiceDomainMapEntry("guardian_first_party", "theguardian.com", "SUFFIX", "com.guardian", "publisher_content", source_url="https://open-platform.theguardian.com/", confidence="high"),
        ServiceDomainMapEntry("guardian_first_party", "ophan.theguardian.com", "EXACT", "com.guardian", "publisher_collection", source_url="https://open-platform.theguardian.com/", confidence="medium", notes="Guardian-owned Ophan telemetry endpoint observed during app runtime traffic."),
        ServiceDomainMapEntry("guardian_first_party", "guardianapis.com", "SUFFIX", "com.guardian", "publisher_api", source_url="https://open-platform.theguardian.com/", confidence="high"),
        ServiceDomainMapEntry("guardian_first_party", "guim.co.uk", "SUFFIX", "com.guardian", "content_delivery", source_url="https://www.theguardian.com/about", confidence="medium"),
        ServiceDomainMapEntry("onetrust_cmp", "privacy-mgmt.com", "SUFFIX", "com.guardian", "consent_management", source_url="https://developer.onetrust.com/onetrust/docs/introduction-to-cmp", confidence="high"),
        ServiceDomainMapEntry("firebase_crashlytics", "crashlytics.com", "SUFFIX", role_class="crash_reporting", source_url="https://firebase.google.com/docs/crashlytics", confidence="high"),
        ServiceDomainMapEntry("adjust_attribution", "adjust.com", "SUFFIX", role_class="attribution_measurement", source_url="https://dev.adjust.com/en/sdk/android/", confidence="high"),
        ServiceDomainMapEntry("espn_first_party", "fan.api.espn.com", "EXACT", "com.espn.score_center", "publisher_api", confidence="high"),
        ServiceDomainMapEntry("espn_first_party", "pinpoint.espn.com", "EXACT", "com.espn.score_center", "publisher_collection", confidence="medium"),
        ServiceDomainMapEntry("espn_first_party", "espn.api.edge.bamgrid.com", "EXACT", "com.espn.score_center", "publisher_api", confidence="medium"),
        ServiceDomainMapEntry("espn_first_party", "espn.connections.edge.bamgrid.com", "EXACT", "com.espn.score_center", "publisher_api", confidence="medium"),
        ServiceDomainMapEntry("espn_first_party", "espn.com", "SUFFIX", "com.espn.score_center", "publisher_api", confidence="medium"),
        ServiceDomainMapEntry("espn_first_party", "bamgrid.com", "SUFFIX", "com.espn.score_center", "publisher_api", confidence="medium"),
        ServiceDomainMapEntry("facebook_platform", "b-graph.facebook.com", "EXACT", "com.facebook.katana", "social_graph_api", confidence="medium"),
        ServiceDomainMapEntry("facebook_platform", "connect.facebook.net", "EXACT", "com.facebook.katana", "identity_api", confidence="medium"),
        ServiceDomainMapEntry("facebook_platform", "facebook.com", "SUFFIX", "com.facebook.katana", "social_graph_api", confidence="high"),
        ServiceDomainMapEntry("facebook_platform", "facebook.com", "SUFFIX", "com.facebook.orca", "social_graph_api", confidence="high"),
        ServiceDomainMapEntry("facebook_platform", "facebook.com", "SUFFIX", "com.instagram.android", "social_graph_api", confidence="high"),
        ServiceDomainMapEntry("facebook_platform", "facebook.net", "SUFFIX", "com.facebook.katana", "social_graph_api", confidence="medium"),
        ServiceDomainMapEntry("facebook_platform", "facebook.net", "SUFFIX", "com.facebook.orca", "social_graph_api", confidence="medium"),
        ServiceDomainMapEntry("facebook_platform", "facebook.net", "SUFFIX", "com.instagram.android", "social_graph_api", confidence="medium"),
        ServiceDomainMapEntry("facebook_platform", "fbcdn.net", "SUFFIX", "com.facebook.katana", "content_delivery", confidence="medium"),
        ServiceDomainMapEntry("facebook_platform", "fbcdn.net", "SUFFIX", "com.facebook.orca", "content_delivery", confidence="medium"),
        ServiceDomainMapEntry("facebook_platform", "fbcdn.net", "SUFFIX", "com.instagram.android", "content_delivery", confidence="medium"),
        ServiceDomainMapEntry("whatsapp_platform", "graph.whatsapp.com", "EXACT", "com.whatsapp", "messaging_platform_api", source_url="https://developers.facebook.com/docs/whatsapp/cloud-api/", confidence="high"),
        ServiceDomainMapEntry("whatsapp_platform", "api.whatsapp.net", "EXACT", "com.whatsapp", "messaging_platform_api", source_url="https://developers.facebook.com/docs/whatsapp/cloud-api/", confidence="high"),
        ServiceDomainMapEntry("whatsapp_platform", "v.whatsapp.net", "EXACT", "com.whatsapp", "realtime_call_transport", source_url="https://www.whatsapp.com/security/", confidence="medium"),
        ServiceDomainMapEntry("whatsapp_platform", "g.whatsapp.net", "EXACT", "com.whatsapp", "realtime_messaging", source_url="https://www.whatsapp.com/security/", confidence="medium"),
        ServiceDomainMapEntry("whatsapp_platform", "mmg.whatsapp.net", "EXACT", "com.whatsapp", "media_delivery", source_url="https://developers.facebook.com/docs/whatsapp/cloud-api/reference/media", confidence="medium"),
        ServiceDomainMapEntry("whatsapp_platform", "scontent.whatsapp.net", "EXACT", "com.whatsapp", "content_delivery", source_url="https://www.whatsapp.com/security/", confidence="medium"),
        ServiceDomainMapEntry("whatsapp_platform", "static.whatsapp.net", "EXACT", "com.whatsapp", "static_asset_delivery", source_url="https://www.whatsapp.com/security/", confidence="medium"),
        ServiceDomainMapEntry("whatsapp_platform", "cdn.whatsapp.net", "SUFFIX", "com.whatsapp", "content_delivery", source_url="https://www.whatsapp.com/security/", confidence="medium"),
        ServiceDomainMapEntry("whatsapp_platform", "whatsapp.com", "SUFFIX", "com.whatsapp", "first_party_misc", source_url="https://www.whatsapp.com/security/", confidence="medium"),
        ServiceDomainMapEntry("whatsapp_platform", "whatsapp.net", "SUFFIX", "com.whatsapp", "first_party_misc", source_url="https://www.whatsapp.com/security/", confidence="medium"),
        ServiceDomainMapEntry(
            "facebook_platform",
            "cdninstagram.com",
            "SUFFIX",
            "com.facebook.katana",
            "content_delivery",
            source_url="https://developers.facebook.com/docs/instagram-platform/instagram-api-with-instagram-login/get-started",
            confidence="medium",
            notes="Package-scoped first-party content mapping for Instagram CDN traffic observed inside the Facebook app.",
        ),
        ServiceDomainMapEntry("meta_sdk", "b-graph.facebook.com", "EXACT", role_class="social_graph_api", confidence="medium"),
        ServiceDomainMapEntry("meta_sdk", "connect.facebook.net", "EXACT", role_class="identity_api", confidence="medium"),
        ServiceDomainMapEntry("meta_sdk", "facebook.com", "SUFFIX", role_class="social_graph_api", confidence="medium"),
        ServiceDomainMapEntry("meta_sdk", "facebook.net", "SUFFIX", role_class="social_graph_api", confidence="medium"),
        ServiceDomainMapEntry("meta_sdk", "fbcdn.net", "SUFFIX", role_class="content_delivery", confidence="low"),
        ServiceDomainMapEntry("x_platform", "api.twitter.com", "EXACT", "com.twitter.android", "social_graph_api", confidence="high"),
        ServiceDomainMapEntry("x_platform", "api-stream.twitter.com", "EXACT", "com.twitter.android", "social_graph_api", confidence="high"),
        ServiceDomainMapEntry("x_platform", "api.x.com", "EXACT", "com.twitter.android", "social_graph_api", confidence="high"),
        ServiceDomainMapEntry(
            "x_platform",
            "probe.twitter.com",
            "EXACT",
            "com.twitter.android",
            "realtime_engagement",
            source_url="https://www.netify.ai/resources/hostnames/probe.twitter.com",
            confidence="medium",
            notes="Curated from current-build X/Twitter runtime traffic plus external hostname references describing probe/live-engagement behavior.",
        ),
        ServiceDomainMapEntry(
            "x_platform",
            "analytics.twitter.com",
            "EXACT",
            "com.twitter.android",
            "analytics_measurement",
            source_url="https://docs.x.com/x-ads-api/analytics",
            confidence="high",
        ),
        ServiceDomainMapEntry(
            "x_platform",
            "chat-ws.x.com",
            "EXACT",
            "com.twitter.android",
            "realtime_engagement",
            source_url="https://docs.x.com/x-api/introduction",
            confidence="medium",
            notes="Observed current-build X runtime websocket endpoint; treat as first-party realtime engagement infrastructure.",
        ),
        ServiceDomainMapEntry("x_platform", "x.com", "EXACT", "com.twitter.android", "social_graph_api", confidence="medium"),
        ServiceDomainMapEntry("x_media_cdn", "pbs.twimg.com", "EXACT", "com.twitter.android", "content_delivery", confidence="high"),
        ServiceDomainMapEntry("x_media_cdn", "video.twimg.com", "EXACT", "com.twitter.android", "content_delivery", confidence="high"),
        ServiceDomainMapEntry(
            "x_media_cdn",
            "video-s.twimg.com",
            "EXACT",
            "com.twitter.android",
            "content_delivery",
            source_url="https://bugzilla.mozilla.org/show_bug.cgi?id=1977810",
            confidence="high",
            notes="Curated from current-build X/Twitter runtime traffic and external webcompat evidence tying the hostname to Twitter/X video delivery.",
        ),
        ServiceDomainMapEntry("x_media_cdn", "abs.twimg.com", "EXACT", "com.twitter.android", "static_asset_delivery", confidence="medium"),
        ServiceDomainMapEntry("x_ads_platform", "ads-api.x.com", "EXACT", "com.twitter.android", "ad_measurement", confidence="medium"),
        ServiceDomainMapEntry("microsoft_ads_atlas", "atdmt.com", "SUFFIX", role_class="adtech_monetization", confidence="medium"),
        ServiceDomainMapEntry("google_platform", "time.google.com", "EXACT", role_class="google_infrastructure", confidence="medium"),
        ServiceDomainMapEntry("tiktok_platform", "tiktokcdn-us.com", "SUFFIX", "com.zhiliaoapp.musically", "content_delivery", confidence="high"),
        ServiceDomainMapEntry("tiktok_platform", "tiktokv.us", "SUFFIX", "com.zhiliaoapp.musically", "first_party_misc", confidence="high"),
        ServiceDomainMapEntry("tiktok_platform", "ibyteimg.com", "SUFFIX", "com.zhiliaoapp.musically", "content_delivery", confidence="medium"),
    )


def default_service_catalog_seed_rows() -> list[dict[str, str | None]]:
    return [
        {
            "service_key": entry.service_key,
            "display_name": entry.display_name,
            "owner_name": entry.owner_name,
            "owner_class": entry.owner_class,
            "service_category": entry.service_category,
            "primary_use_case": entry.primary_use_case,
            "documentation_url": entry.documentation_url,
            "privacy_policy_url": entry.privacy_policy_url,
            "source_label": entry.source_label,
            "source_url": entry.source_url,
            "confidence": entry.confidence,
            "notes": entry.notes,
        }
        for entry in default_service_catalog_entries()
    ]


def default_service_domain_map_seed_rows() -> list[dict[str, str | None]]:
    return [
        {
            "service_key": entry.service_key,
            "package_name_scope": entry.package_name_scope,
            "domain_pattern": normalize_domain(entry.domain_pattern),
            "match_type": entry.match_type.upper(),
            "role_class": entry.role_class,
            "source_label": entry.source_label,
            "source_url": entry.source_url,
            "confidence": entry.confidence,
            "notes": entry.notes,
        }
        for entry in default_service_domain_map_entries()
    ]


def resolve_service_for_domain(
    domain: str,
    *,
    package_name: str,
    service_rows: tuple[dict[str, Any], ...],
    map_rows: tuple[dict[str, Any], ...],
) -> dict[str, Any]:
    normalized = normalize_domain(domain)
    normalized_package = _norm_text(package_name).lower()
    root = root_domain(normalized)
    if not normalized:
        return {
            "domain": "",
            "root_domain": "",
            "service_key": None,
            "service_display_name": None,
            "owner_name": None,
            "owner_class": None,
            "service_category": None,
            "primary_use_case": None,
            "role_class": None,
            "confidence": None,
            "match_type": None,
            "package_name_scope": None,
            "source_url": None,
        }

    by_key = {str(row.get("service_key") or ""): row for row in service_rows}
    candidates: list[dict[str, Any]] = []
    for row in map_rows:
        pattern = normalize_domain(row.get("domain_pattern"))
        match_type = str(row.get("match_type") or "").upper()
        scope = _norm_text(row.get("package_name_scope")).lower()
        if scope and scope != normalized_package:
            continue
        matched = False
        if match_type == "EXACT":
            matched = pattern == normalized
        elif match_type == "SUFFIX":
            matched = suffix_match(normalized, pattern)
        if matched:
            score = (0 if scope else 1, 0 if match_type == "EXACT" else 1, -len(pattern))
            candidates.append({"row": row, "score": score})
    candidates.sort(key=lambda item: item["score"])
    if not candidates:
        return {
            "domain": normalized,
            "root_domain": root,
            "service_key": None,
            "service_display_name": None,
            "owner_name": None,
            "owner_class": None,
            "service_category": None,
            "primary_use_case": None,
            "role_class": None,
            "confidence": None,
            "match_type": None,
            "package_name_scope": None,
            "source_url": None,
        }
    chosen = candidates[0]["row"]
    service = by_key.get(str(chosen.get("service_key") or ""), {})
    return {
        "domain": normalized,
        "root_domain": root,
        "service_key": service.get("service_key"),
        "service_display_name": service.get("display_name"),
        "owner_name": service.get("owner_name"),
        "owner_class": service.get("owner_class"),
        "service_category": service.get("service_category"),
        "primary_use_case": service.get("primary_use_case"),
        "role_class": chosen.get("role_class"),
        "confidence": chosen.get("confidence") or service.get("confidence"),
        "match_type": chosen.get("match_type"),
        "package_name_scope": chosen.get("package_name_scope"),
        "source_url": chosen.get("source_url") or service.get("source_url") or service.get("documentation_url"),
    }


__all__ = [
    "ServiceCatalogEntry",
    "ServiceDomainMapEntry",
    "default_service_catalog_entries",
    "default_service_catalog_seed_rows",
    "default_service_domain_map_entries",
    "default_service_domain_map_seed_rows",
    "resolve_service_for_domain",
]
