"""Shared service/provider context rules for dynamic network interpretation."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from scytaledroid.DynamicAnalysis.domain_context import normalize_domain, root_domain, suffix_match


@dataclass(frozen=True)
class ServiceCatalogEntry:
    service_key: str
    display_name: str
    owner_name: str
    owner_class: str
    service_category: str
    primary_use_case: str | None
    documentation_url: str | None = None
    privacy_policy_url: str | None = None
    source_label: str = "repo_seed"
    source_url: str | None = None
    confidence: str = "medium"
    notes: str | None = None


@dataclass(frozen=True)
class ServiceDomainMapEntry:
    service_key: str
    domain_pattern: str
    match_type: str
    package_name_scope: str = ""
    role_class: str | None = None
    source_label: str = "repo_seed"
    source_url: str | None = None
    confidence: str = "medium"
    notes: str | None = None


def _norm_text(value: object) -> str:
    return str(value or "").strip()


def default_service_catalog_entries() -> tuple[ServiceCatalogEntry, ...]:
    return (
        ServiceCatalogEntry(
            service_key="bbc_first_party",
            display_name="BBC First-Party Services",
            owner_name="BBC",
            owner_class="first_party",
            service_category="publisher",
            primary_use_case="news_content_and_api",
            source_url="https://www.bbc.com",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="cnn_first_party",
            display_name="CNN First-Party Services",
            owner_name="CNN",
            owner_class="first_party",
            service_category="publisher",
            primary_use_case="news_content_and_api",
            source_url="https://www.cnn.com",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="espn_first_party",
            display_name="ESPN First-Party Services",
            owner_name="ESPN / Disney",
            owner_class="first_party",
            service_category="publisher",
            primary_use_case="sports_content_and_api",
            source_url="https://www.espn.com/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="urbanairship",
            display_name="Airship",
            owner_name="Airship",
            owner_class="third_party",
            service_category="engagement",
            primary_use_case="push_and_customer_engagement",
            documentation_url="https://www.airship.com/",
            privacy_policy_url="https://www.airship.com/legal/privacy/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="google_ads",
            display_name="Google Ads / DoubleClick",
            owner_name="Google",
            owner_class="third_party",
            service_category="adtech",
            primary_use_case="advertising_and_monetization",
            documentation_url="https://support.google.com/admanager/",
            privacy_policy_url="https://policies.google.com/privacy",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="google_platform",
            display_name="Google Platform Infrastructure",
            owner_name="Google",
            owner_class="third_party",
            service_category="platform_infrastructure",
            primary_use_case="shared_platform_delivery",
            documentation_url="https://developers.google.com/",
            privacy_policy_url="https://policies.google.com/privacy",
            confidence="medium",
        ),
        ServiceCatalogEntry(
            service_key="akamai_diagnostics",
            display_name="Akamai Edge Diagnostics",
            owner_name="Akamai",
            owner_class="third_party",
            service_category="platform_infrastructure",
            primary_use_case="edge_resolution_and_network_diagnostics",
            documentation_url="https://www.akamai.com/blog/developers/introducing-new-whoami-tool-dns-resolver-information",
            source_url="https://www.akamai.com/blog/developers/introducing-new-whoami-tool-dns-resolver-information",
            confidence="medium",
            notes="Curated for Akamai diagnostic hostnames observed in dynamic traffic; treat as infrastructure/diagnostic context rather than app first-party service traffic.",
        ),
        ServiceCatalogEntry(
            service_key="chartbeat",
            display_name="Chartbeat",
            owner_name="Chartbeat",
            owner_class="third_party",
            service_category="analytics",
            primary_use_case="audience_measurement",
            documentation_url="https://chartbeat.com/",
            privacy_policy_url="https://chartbeat.com/privacy/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="doubleverify",
            display_name="DoubleVerify",
            owner_name="DoubleVerify",
            owner_class="third_party",
            service_category="ad_verification",
            primary_use_case="media_quality_and_ad_verification",
            documentation_url="https://doubleverify.com/company/about",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="dianomi",
            display_name="Dianomi",
            owner_name="Dianomi",
            owner_class="third_party",
            service_category="adtech",
            primary_use_case="native_advertising_and_publisher_monetization",
            documentation_url="https://www.dianomi.com/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="permutive",
            display_name="Permutive",
            owner_name="Permutive",
            owner_class="third_party",
            service_category="audience_personalization",
            primary_use_case="publisher_audience_activation",
            documentation_url="https://permutive.com/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="appsflyer",
            display_name="AppsFlyer",
            owner_name="AppsFlyer",
            owner_class="third_party",
            service_category="attribution",
            primary_use_case="install_attribution_and_engagement_measurement",
            documentation_url="https://www.appsflyer.com/",
            privacy_policy_url="https://www.appsflyer.com/legal/services-privacy-policy/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="liveramp",
            display_name="LiveRamp",
            owner_name="LiveRamp",
            owner_class="third_party",
            service_category="identity_and_adtech",
            primary_use_case="identity_resolution_and_cookie_sync",
            documentation_url="https://docs.liveramp.com/identity/en/implementing-liveramp-s-cookie-sync-tag.html",
            privacy_policy_url="https://liveramp.com/privacy/service-privacy-policy",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="flashtalking",
            display_name="Flashtalking / Innovid",
            owner_name="Innovid",
            owner_class="third_party",
            service_category="adtech",
            primary_use_case="ad_serving_and_creative_delivery",
            documentation_url="https://www.flashtalking.com/",
            privacy_policy_url="https://www.flashtalking.com/consumer-privacy",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="optimizely",
            display_name="Optimizely",
            owner_name="Optimizely",
            owner_class="third_party",
            service_category="experimentation",
            primary_use_case="experimentation_and_personalization",
            documentation_url="https://www.optimizely.com/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="piano",
            display_name="Piano",
            owner_name="Piano",
            owner_class="third_party",
            service_category="subscription_paywall",
            primary_use_case="publisher_subscription_paywall_and_customer_experience",
            documentation_url="https://www.piano.io/industry/media",
            source_url="https://piano.io/marketing/product/ad-revenue-insights-dynamic-paywall",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="adobe_experience_cloud",
            display_name="Adobe Experience Cloud",
            owner_name="Adobe",
            owner_class="third_party",
            service_category="identity_and_tag_management",
            primary_use_case="identity_service_and_tag_delivery",
            documentation_url="https://experienceleague.adobe.com/en/docs/id-service/using/intro/cookies",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="adobe_advertising",
            display_name="Adobe Advertising",
            owner_name="Adobe",
            owner_class="third_party",
            service_category="adtech",
            primary_use_case="advertising_measurement_and_creative_delivery",
            documentation_url="https://experienceleague.adobe.com/en/docs/advertising/",
            source_url="https://experienceleague.adobe.com/en/docs/core-services/interface/data-collection/cookies/advertising",
            confidence="medium",
        ),
        ServiceCatalogEntry(
            service_key="integral_ad_science",
            display_name="Integral Ad Science",
            owner_name="Integral Ad Science",
            owner_class="third_party",
            service_category="ad_verification",
            primary_use_case="media_quality_and_brand_safety",
            documentation_url="https://integralads.com/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="amazon_ads",
            display_name="Amazon Ads",
            owner_name="Amazon",
            owner_class="third_party",
            service_category="adtech",
            primary_use_case="advertising_and_measurement",
            documentation_url="https://advertising.amazon.com/",
            confidence="medium",
        ),
        ServiceCatalogEntry(
            service_key="amazon_media_cdn",
            display_name="Amazon Media CDN",
            owner_name="Amazon",
            owner_class="third_party",
            service_category="content_delivery",
            primary_use_case="amazon_hosted_media_and_static_asset_delivery",
            documentation_url="https://webservices.amazon.com/paapi5/documentation/images.html",
            confidence="medium",
            notes="Generic media-amazon.com attribution for embedded media assets outside package-specific ad-tech mappings.",
        ),
        ServiceCatalogEntry(
            service_key="infosec_world_event_site",
            display_name="InfoSec World Event Site",
            owner_name="CyberRisk Alliance / InfoSec World",
            owner_class="third_party",
            service_category="external_content",
            primary_use_case="conference_site_content_and_registration",
            documentation_url="https://www.infosecworldusa.com/",
            confidence="medium",
            notes="Observed from Facebook external navigation; treat as third-party web/content traffic.",
        ),
        ServiceCatalogEntry(
            service_key="swoogo_event_platform",
            display_name="Swoogo Event Platform",
            owner_name="Swoogo",
            owner_class="third_party",
            service_category="event_management",
            primary_use_case="event_site_registration_and_static_asset_delivery",
            documentation_url="https://swoogo.events/platform/",
            confidence="medium",
            notes="Observed as event-platform asset delivery alongside InfoSec World external-page traffic.",
        ),
        ServiceCatalogEntry(
            service_key="steam_storefront",
            display_name="Steam Storefront",
            owner_name="Valve",
            owner_class="third_party",
            service_category="external_content",
            primary_use_case="game_storefront_page_content",
            documentation_url="https://store.steampowered.com/about/",
            privacy_policy_url="https://store.steampowered.com/privacy_agreement/",
            confidence="high",
            notes="Observed from Facebook external navigation to Steam web/store content.",
        ),
        ServiceCatalogEntry(
            service_key="steam_media_cdn",
            display_name="Steam Static Media Delivery",
            owner_name="Valve",
            owner_class="third_party",
            service_category="content_delivery",
            primary_use_case="steam_store_static_asset_delivery",
            documentation_url="https://store.steampowered.com/about/",
            privacy_policy_url="https://store.steampowered.com/privacy_agreement/",
            confidence="medium",
            notes="Steam static/CDN host observed with Steam storefront traffic.",
        ),
        ServiceCatalogEntry(
            service_key="admaster",
            display_name="AdMaster",
            owner_name="AdMaster",
            owner_class="third_party",
            service_category="ad_measurement",
            primary_use_case="advertising_measurement_and_verification",
            documentation_url="https://www.admaster.com.cn/",
            confidence="medium",
        ),
        ServiceCatalogEntry(
            service_key="mainroll_pixel",
            display_name="Mainroll Tracking Pixel",
            owner_name="Mainroll",
            owner_class="third_party",
            service_category="adtech",
            primary_use_case="advertising_measurement_pixel",
            source_label="repo_seed_public_filter_list",
            source_url="https://easylist.to/easylist/easylist.txt",
            confidence="medium",
            notes="Guardian-observed stats.mainroll.com returns a small image/gif via CloudFront and mainroll.com is listed by EasyList; retain as a conservative ad-measurement pixel classification rather than a named vendor relationship.",
        ),
        ServiceCatalogEntry(
            service_key="scorecardresearch",
            display_name="ScorecardResearch",
            owner_name="Comscore",
            owner_class="third_party",
            service_category="analytics",
            primary_use_case="audience_measurement",
            documentation_url="https://www.comscore.com/",
            privacy_policy_url="https://www.comscore.com/About/Privacy-Policy",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="new_relic",
            display_name="New Relic Mobile Monitoring",
            owner_name="New Relic",
            owner_class="third_party",
            service_category="analytics",
            primary_use_case="mobile_telemetry_and_monitoring",
            documentation_url="https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/configure-settings/",
            confidence="medium",
        ),
        ServiceCatalogEntry(
            service_key="nielsen_dcr",
            display_name="Nielsen Digital Content Ratings",
            owner_name="Nielsen",
            owner_class="third_party",
            service_category="analytics",
            primary_use_case="digital_audience_measurement",
            documentation_url="https://learning.nielsen.com/page/digital-content-ratings-dcr",
            source_url="https://www.netify.ai/resources/domains/vtwenty.com",
            confidence="medium",
            notes="Service association uses a secondary hostname source and should be treated as curated but reviewable.",
        ),
        ServiceCatalogEntry(
            service_key="ozone_project",
            display_name="The Ozone Project",
            owner_name="The Ozone Project",
            owner_class="third_party",
            service_category="adtech",
            primary_use_case="publisher_ad_exchange",
            documentation_url="https://www.theozoneproject.com/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="facebook_platform",
            display_name="Facebook / Meta Platform",
            owner_name="Meta",
            owner_class="first_party",
            service_category="social_platform",
            primary_use_case="social_graph_and_messaging",
            documentation_url="https://developers.facebook.com/",
            privacy_policy_url="https://www.facebook.com/privacy/policy/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="zoom_platform",
            display_name="Zoom Meeting Platform",
            owner_name="Zoom",
            owner_class="third_party",
            service_category="rtc_collaboration",
            primary_use_case="meeting_and_webinar_transport",
            documentation_url="https://developers.zoom.us/docs/meeting-sdk/",
            source_url="https://developers.zoom.us/",
            confidence="medium",
            notes="Used for Zoom-hosted meeting surfaces opened from other apps such as social-network outbound meeting links.",
        ),
        ServiceCatalogEntry(
            service_key="whatsapp_platform",
            display_name="WhatsApp / Meta Messaging Platform",
            owner_name="Meta",
            owner_class="first_party",
            service_category="social_platform",
            primary_use_case="messaging_calls_and_media_delivery",
            documentation_url="https://developers.facebook.com/docs/whatsapp/cloud-api/",
            privacy_policy_url="https://www.whatsapp.com/legal/privacy-policy",
            source_url="https://www.whatsapp.com/security/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="telegram_platform",
            display_name="Telegram Messaging Platform",
            owner_name="Telegram Messenger Inc",
            owner_class="first_party",
            service_category="messaging_platform",
            primary_use_case="encrypted_messaging_datacenter_transport",
            documentation_url="https://core.telegram.org/mtproto",
            privacy_policy_url="https://telegram.org/privacy",
            source_url="https://core.telegram.org/resources/cidr.txt",
            confidence="high",
            notes="Telegram Android traffic can use direct data-center IP transport with sparse DNS/SNI.",
        ),
        ServiceCatalogEntry(
            service_key="instagram_platform",
            display_name="Instagram / Meta Platform",
            owner_name="Meta",
            owner_class="first_party",
            service_category="social_platform",
            primary_use_case="social_graph_media_and_platform_api",
            documentation_url="https://developers.facebook.com/docs/instagram-platform/",
            privacy_policy_url="https://privacycenter.instagram.com/policy/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="instagram_media_cdn",
            display_name="Instagram Media Delivery",
            owner_name="Meta",
            owner_class="first_party",
            service_category="content_delivery",
            primary_use_case="photo_video_and_static_media_delivery",
            documentation_url="https://developers.facebook.com/docs/instagram-platform/",
            privacy_policy_url="https://privacycenter.instagram.com/policy/",
            confidence="medium",
            notes="Package-scoped to Instagram-observed CDN traffic so Facebook-owned CDN hostnames remain reviewable in other apps.",
        ),
        ServiceCatalogEntry(
            service_key="giphy_media",
            display_name="GIPHY Media Delivery",
            owner_name="GIPHY",
            owner_class="third_party",
            service_category="content_delivery",
            primary_use_case="gif_sticker_and_short_media_delivery",
            documentation_url="https://developers.giphy.com/docs/",
            source_url="https://developers.giphy.com/docs/api/",
            confidence="medium",
            notes="Third-party GIF and sticker library delivery observed inside social app runtime traffic.",
        ),
        ServiceCatalogEntry(
            service_key="meta_sdk",
            display_name="Meta Platform SDK / APIs",
            owner_name="Meta",
            owner_class="third_party",
            service_category="social_platform",
            primary_use_case="social_graph_sdk_and_identity",
            documentation_url="https://developers.facebook.com/",
            privacy_policy_url="https://www.facebook.com/privacy/policy/",
            confidence="medium",
        ),
        ServiceCatalogEntry(
            service_key="x_platform",
            display_name="X / Twitter Platform",
            owner_name="X",
            owner_class="first_party",
            service_category="social_platform",
            primary_use_case="social_graph_and_platform_api",
            documentation_url="https://docs.x.com/x-api/introduction",
            source_url="https://developer.x.com/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="x_media_cdn",
            display_name="X / Twitter Media Delivery",
            owner_name="X",
            owner_class="first_party",
            service_category="content_delivery",
            primary_use_case="media_and_static_asset_delivery",
            documentation_url="https://developer.x.com/",
            source_url="https://devcommunity.x.com/t/pbs-twimg-com-cdn-problems/92623",
            confidence="medium",
            notes="Used for twimg-hosted media and static asset delivery observed during X/Twitter app runtime traffic.",
        ),
        ServiceCatalogEntry(
            service_key="x_ads_platform",
            display_name="X / Twitter Advertising Platform",
            owner_name="X",
            owner_class="first_party",
            service_category="adtech",
            primary_use_case="advertising_api_and_measurement",
            documentation_url="https://docs.x.com/x-api/introduction",
            source_url="https://developer.x.com/",
            confidence="medium",
            notes="Used for X/Twitter-owned advertising endpoints; treat as first-party ad/measurement context rather than third-party tracker by default.",
        ),
        ServiceCatalogEntry(
            service_key="linkedin_platform",
            display_name="LinkedIn Platform",
            owner_name="LinkedIn / Microsoft",
            owner_class="first_party",
            service_category="social_platform",
            primary_use_case="professional_social_graph_and_platform_api",
            documentation_url="https://learn.microsoft.com/en-us/linkedin/",
            privacy_policy_url="https://www.linkedin.com/legal/privacy-policy",
            source_url="https://www.linkedin.com/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="linkedin_cdn",
            display_name="LinkedIn Media and Static Delivery",
            owner_name="LinkedIn / Microsoft",
            owner_class="first_party",
            service_category="content_delivery",
            primary_use_case="profile_media_document_and_static_asset_delivery",
            documentation_url="https://learn.microsoft.com/en-us/linkedin/",
            privacy_policy_url="https://www.linkedin.com/legal/privacy-policy",
            source_url="https://www.linkedin.com/",
            confidence="medium",
        ),
        ServiceCatalogEntry(
            service_key="human_security_bot_defense",
            display_name="HUMAN Security Bot Defense",
            owner_name="HUMAN Security",
            owner_class="third_party",
            service_category="security_or_bot_defense",
            primary_use_case="bot_detection_and_abuse_prevention",
            documentation_url="https://www.humansecurity.com/",
            privacy_policy_url="https://www.humansecurity.com/privacy-notice/",
            source_url="https://www.humansecurity.com/",
            confidence="medium",
            notes="Package-scoped for LinkedIn-observed Protechts/HUMAN traffic; keep reviewable if new apps observe the same host family.",
        ),
        ServiceCatalogEntry(
            service_key="ns1_connect",
            display_name="IBM NS1 Connect",
            owner_name="IBM",
            owner_class="third_party",
            service_category="platform_infrastructure",
            primary_use_case="managed_dns_and_edge_connectivity",
            documentation_url="https://www.ibm.com/products/ns1-connect",
            privacy_policy_url="https://www.ibm.com/privacy",
            source_url="https://www.ibm.com/products/ns1-connect",
            confidence="medium",
            notes="Package-scoped for LinkedIn-observed ns1p.net DNS/edge hostnames.",
        ),
        ServiceCatalogEntry(
            service_key="pinterest_platform",
            display_name="Pinterest Platform",
            owner_name="Pinterest",
            owner_class="first_party",
            service_category="social_platform",
            primary_use_case="visual_discovery_social_graph_and_platform_api",
            documentation_url="https://developers.pinterest.com/",
            privacy_policy_url="https://policy.pinterest.com/privacy-policy",
            source_url="https://www.pinterest.com/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="pinterest_media_cdn",
            display_name="Pinterest Media Delivery",
            owner_name="Pinterest",
            owner_class="first_party",
            service_category="content_delivery",
            primary_use_case="image_video_and_static_asset_delivery",
            documentation_url="https://developers.pinterest.com/",
            privacy_policy_url="https://policy.pinterest.com/privacy-policy",
            source_url="https://www.pinterest.com/",
            confidence="medium",
        ),
        ServiceCatalogEntry(
            service_key="reddit_platform",
            display_name="Reddit Platform",
            owner_name="Reddit",
            owner_class="first_party",
            service_category="social_platform",
            primary_use_case="community_content_social_graph_and_platform_api",
            documentation_url="https://developers.reddit.com/docs/capabilities/server/reddit-api",
            privacy_policy_url="https://www.reddit.com/policies/privacy-policy",
            source_url="https://developers.reddit.com/docs/capabilities/server/reddit-api",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="reddit_media_cdn",
            display_name="Reddit Media and Static Delivery",
            owner_name="Reddit",
            owner_class="first_party",
            service_category="content_delivery",
            primary_use_case="media_preview_static_asset_and_content_delivery",
            documentation_url="https://developers.reddit.com/docs/capabilities/server/reddit-api",
            privacy_policy_url="https://www.reddit.com/policies/privacy-policy",
            source_url="https://www.netify.ai/resources/applications/reddit",
            confidence="medium",
            notes="Curated from Reddit-observed runtime hostnames plus secondary domain inventory; package-scoped to the Reddit app.",
        ),
        ServiceCatalogEntry(
            service_key="snapchat_platform",
            display_name="Snapchat Platform",
            owner_name="Snap Inc.",
            owner_class="first_party",
            service_category="social_platform",
            primary_use_case="messaging_camera_social_graph_and_platform_api",
            documentation_url="https://developers.snap.com/",
            privacy_policy_url="https://values.snap.com/privacy/privacy-policy",
            source_url="https://developers.snap.com/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="snapchat_cdn",
            display_name="Snapchat Media Delivery",
            owner_name="Snap Inc.",
            owner_class="first_party",
            service_category="content_delivery",
            primary_use_case="camera_media_static_asset_and_content_delivery",
            documentation_url="https://developers.snap.com/",
            privacy_policy_url="https://values.snap.com/privacy/privacy-policy",
            source_url="https://developers.snap.com/",
            confidence="medium",
        ),
        ServiceCatalogEntry(
            service_key="signal_platform",
            display_name="Signal Messaging Platform",
            owner_name="Signal Messenger LLC",
            owner_class="first_party",
            service_category="messaging_platform",
            primary_use_case="encrypted_messaging_calls_and_storage",
            documentation_url="https://signal.org/docs/",
            privacy_policy_url="https://signal.org/legal/",
            source_url="https://signal.org/legal/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="guardian_first_party",
            display_name="Guardian First-Party Services",
            owner_name="Guardian News & Media",
            owner_class="first_party",
            service_category="publisher",
            primary_use_case="news_content_and_api",
            documentation_url="https://open-platform.theguardian.com/",
            source_url="https://open-platform.theguardian.com/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="onetrust_cmp",
            display_name="OneTrust Consent Management",
            owner_name="OneTrust",
            owner_class="third_party",
            service_category="consent_and_privacy",
            primary_use_case="consent_management_and_privacy_preferences",
            documentation_url="https://developer.onetrust.com/onetrust/docs/introduction-to-cmp",
            privacy_policy_url="https://www.onetrust.com/privacy-notice/",
            source_url="https://developer.onetrust.com/onetrust/docs/introduction-to-cmp",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="sourcepoint_cmp",
            display_name="Sourcepoint Consent Management",
            owner_name="Sourcepoint",
            owner_class="third_party",
            service_category="consent_and_privacy",
            primary_use_case="consent_management_and_privacy_preferences",
            documentation_url="https://sourcepoint.com/",
            privacy_policy_url="https://sourcepoint.com/privacy-policy/",
            source_url="https://sourcepoint.com/",
            confidence="medium",
            notes="Package-scoped for BBC-observed privacy-mgmt.com traffic; existing Guardian mapping remains OneTrust-scoped until separately reviewed.",
        ),
        ServiceCatalogEntry(
            service_key="braze_sdk",
            display_name="Braze Customer Engagement",
            owner_name="Braze",
            owner_class="third_party",
            service_category="engagement",
            primary_use_case="customer_engagement_push_and_messaging",
            documentation_url="https://www.braze.com/docs/developer_guide/platform_integration_guides/android/",
            privacy_policy_url="https://www.braze.com/company/legal/privacy",
            source_url="https://www.braze.com/docs/developer_guide/platform_integration_guides/android/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="confiant_ad_security",
            display_name="Confiant Ad Security",
            owner_name="Confiant",
            owner_class="third_party",
            service_category="ad_verification",
            primary_use_case="ad_quality_malvertising_detection_and_security",
            documentation_url="https://www.confiant.com/",
            privacy_policy_url="https://www.confiant.com/privacy-policy",
            source_url="https://www.confiant.com/",
            confidence="medium",
        ),
        ServiceCatalogEntry(
            service_key="cloudflare_privacy_gateway",
            display_name="Cloudflare Privacy Gateway",
            owner_name="Cloudflare",
            owner_class="third_party",
            service_category="platform_infrastructure",
            primary_use_case="privacy_gateway_and_secure_proxy_infrastructure",
            documentation_url="https://developers.cloudflare.com/privacy-gateway/",
            privacy_policy_url="https://www.cloudflare.com/privacypolicy/",
            source_url="https://developers.cloudflare.com/privacy-gateway/",
            confidence="medium",
            notes="Package-scoped to Messenger-observed Meta privacy gateway hostnames; do not treat as generic Cloudflare CDN traffic.",
        ),
        ServiceCatalogEntry(
            service_key="google_recaptcha",
            display_name="Google reCAPTCHA",
            owner_name="Google",
            owner_class="third_party",
            service_category="security_or_bot_defense",
            primary_use_case="bot_detection_and_abuse_prevention",
            documentation_url="https://developers.google.com/recaptcha",
            privacy_policy_url="https://policies.google.com/privacy",
            source_url="https://developers.google.com/recaptcha",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="microsoft_fraud_protection",
            display_name="Microsoft Dynamics 365 Fraud Protection",
            owner_name="Microsoft",
            owner_class="third_party",
            service_category="security_or_bot_defense",
            primary_use_case="device_fingerprinting_and_fraud_protection",
            documentation_url="https://learn.microsoft.com/en-us/dynamics365/fraud-protection/df-web",
            privacy_policy_url="https://privacy.microsoft.com/privacystatement",
            source_url="https://learn.microsoft.com/en-us/dynamics365/fraud-protection/df-web",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="firebase_crashlytics",
            display_name="Firebase Crashlytics",
            owner_name="Google",
            owner_class="third_party",
            service_category="analytics",
            primary_use_case="crash_reporting_and_runtime_telemetry",
            documentation_url="https://firebase.google.com/docs/crashlytics",
            privacy_policy_url="https://firebase.google.com/support/privacy",
            source_url="https://firebase.google.com/docs/crashlytics",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="firebase_installations",
            display_name="Firebase Installations",
            owner_name="Google",
            owner_class="third_party",
            service_category="identity_and_tag_management",
            primary_use_case="firebase_installation_identity_and_auth_tokens",
            documentation_url="https://firebase.google.com/docs/projects/manage-installations",
            privacy_policy_url="https://firebase.google.com/support/privacy",
            source_url="https://firebase.google.com/docs/projects/manage-installations",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="adjust_attribution",
            display_name="Adjust Attribution",
            owner_name="Adjust",
            owner_class="third_party",
            service_category="attribution",
            primary_use_case="install_attribution_and_reengagement_measurement",
            documentation_url="https://dev.adjust.com/en/sdk/android/",
            privacy_policy_url="https://www.adjust.com/terms/privacy-policy/",
            source_url="https://dev.adjust.com/en/sdk/android/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="microsoft_ads_atlas",
            display_name="Microsoft Advertising / Atlas",
            owner_name="Microsoft",
            owner_class="third_party",
            service_category="adtech",
            primary_use_case="ad_serving_click_tracking_and_measurement",
            documentation_url="https://learn.microsoft.com/en-us/xandr/bidders/creative-macro-check-service",
            confidence="medium",
            notes="Used for ATDMT / Atlas ad-serving and click-tracking infrastructure.",
        ),
        ServiceCatalogEntry(
            service_key="tiktok_platform",
            display_name="TikTok / ByteDance Platform",
            owner_name="ByteDance",
            owner_class="first_party",
            service_category="social_platform",
            primary_use_case="content_delivery_and_platform_control",
            documentation_url="https://developers.tiktok.com/",
            privacy_policy_url="https://www.tiktok.com/legal/privacy-policy",
            source_url="https://developers.tiktok.com/doc/display-api-get-started/",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="tiktok_ads_measurement",
            display_name="TikTok Ads Measurement",
            owner_name="ByteDance",
            owner_class="first_party",
            service_category="adtech",
            primary_use_case="advertising_measurement_and_attribution",
            documentation_url="https://ads.tiktok.com/business/en-US/products/measurement",
            privacy_policy_url="https://www.tiktok.com/legal/privacy-policy",
            source_url="https://ads.tiktok.com/business/en-US/products/measurement",
            confidence="medium",
            notes="Package-scoped for tiktok.adsmeasurement.com observed in TikTok runtime traffic.",
        ),
        ServiceCatalogEntry(
            service_key="turner_cnn_legacy",
            display_name="Turner / CNN Legacy Media Infrastructure",
            owner_name="Warner Bros. Discovery",
            owner_class="first_party",
            service_category="publisher",
            primary_use_case="legacy_media_delivery_and_auth",
            documentation_url="https://www.cnn.com",
            confidence="medium",
        ),
        ServiceCatalogEntry(
            service_key="wbd_streaming_platform",
            display_name="Warner Bros. Discovery Streaming Platform",
            owner_name="Warner Bros. Discovery",
            owner_class="first_party",
            service_category="platform_infrastructure",
            primary_use_case="cross_brand_streaming_api_and_delivery",
            documentation_url="https://www.max.com/",
            source_url="https://www.warnermediacdn.com/",
            confidence="medium",
            notes="Package-scoped mapping used for CNN-observed Warner/Max delivery and API domains; treat as curated first-party platform infrastructure rather than generic CDN traffic.",
        ),
        ServiceCatalogEntry(
            service_key="freewheel",
            display_name="FreeWheel",
            owner_name="FreeWheel / Comcast",
            owner_class="third_party",
            service_category="adtech",
            primary_use_case="streaming_video_ad_serving_and_monetization",
            documentation_url="https://www.freewheel.com/",
            privacy_policy_url="https://www.freewheel.com/privacy-policy",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="mux_data",
            display_name="Mux Data / Video Analytics",
            owner_name="Mux",
            owner_class="third_party",
            service_category="analytics",
            primary_use_case="video_playback_analytics_and_delivery_telemetry",
            documentation_url="https://www.mux.com/docs/core.txt",
            source_url="https://www.mux.com/docs/core.txt",
            confidence="medium",
            notes="Mux documentation explicitly references litix.io as part of Mux infrastructure.",
        ),
        ServiceCatalogEntry(
            service_key="brightline_ctv",
            display_name="BrightLine Interactive CTV",
            owner_name="BrightLine",
            owner_class="third_party",
            service_category="adtech",
            primary_use_case="interactive_ctv_advertising",
            documentation_url="https://brightline.tv/",
            source_url="https://brightline.tv/experience-library",
            confidence="high",
        ),
        ServiceCatalogEntry(
            service_key="oracle_cloud",
            display_name="Oracle Cloud Infrastructure",
            owner_name="Oracle",
            owner_class="third_party",
            service_category="platform_infrastructure",
            primary_use_case="cloud_infrastructure_and_hosting",
            documentation_url="https://docs.cloud.oracle.com/",
            source_url="https://www.oracle.com/cloud/",
            confidence="medium",
        ),
        ServiceCatalogEntry(
            service_key="mapbox_platform",
            display_name="Mapbox SDK / Platform",
            owner_name="Mapbox",
            owner_class="third_party",
            service_category="platform_infrastructure",
            primary_use_case="maps_sdk_configuration_and_geospatial_api",
            documentation_url="https://docs.mapbox.com/api/overview/",
            source_url="https://docs.mapbox.com/api/overview/",
            confidence="medium",
        ),
        ServiceCatalogEntry(
            service_key="cloudflare_cdnjs",
            display_name="Cloudflare CDNJS",
            owner_name="Cloudflare",
            owner_class="third_party",
            service_category="content_delivery",
            primary_use_case="static_asset_delivery_for_embedded_libraries",
            documentation_url="https://cdnjs.com/about",
            privacy_policy_url="https://www.cloudflare.com/privacypolicy/",
            source_url="https://cdnjs.com/about",
            confidence="medium",
        ),
        ServiceCatalogEntry(
            service_key="cloudflare_realtime_relay",
            display_name="Cloudflare Realtime Relay",
            owner_name="Cloudflare",
            owner_class="third_party",
            service_category="platform_infrastructure",
            primary_use_case="stun_turn_and_realtime_media_relay",
            documentation_url="https://developers.cloudflare.com/realtime/turn/",
            privacy_policy_url="https://www.cloudflare.com/privacypolicy/",
            source_url="https://developers.cloudflare.com/realtime/turn/",
            confidence="medium",
        ),
        ServiceCatalogEntry(
            service_key="google_amp_cache",
            display_name="Google AMP Cache",
            owner_name="Google",
            owner_class="third_party",
            service_category="content_delivery",
            primary_use_case="amp_content_delivery_and_caching",
            documentation_url="https://developers.google.com/amp/cache/overview",
            privacy_policy_url="https://policies.google.com/privacy",
            source_url="https://developers.google.com/amp/cache/overview",
            confidence="medium",
        ),
        ServiceCatalogEntry(
            service_key="equativ_smartadserver",
            display_name="Equativ / Smart AdServer",
            owner_name="Equativ",
            owner_class="third_party",
            service_category="adtech",
            primary_use_case="ad_serving_and_identity_sync",
            documentation_url="https://equativ.com/",
            privacy_policy_url="https://equativ.com/privacy-policy/",
            source_url="https://equativ.com/",
            confidence="medium",
        ),
    )


def default_service_domain_map_entries() -> tuple[ServiceDomainMapEntry, ...]:
    return (
        ServiceDomainMapEntry("bbc_first_party", "bbc.com", "SUFFIX", "bbc.mobile.news.ww", "publisher_api", confidence="high"),
        ServiceDomainMapEntry("bbc_first_party", "bbc.co.uk", "SUFFIX", "bbc.mobile.news.ww", "identity_api", confidence="medium"),
        ServiceDomainMapEntry("bbc_first_party", "bbci.co.uk", "SUFFIX", "bbc.mobile.news.ww", "content_delivery", confidence="high"),
        ServiceDomainMapEntry(
            "bbc_first_party",
            "www.bbc.com",
            "EXACT",
            "bbc.mobile.news.ww",
            "publisher_content",
            source_url="https://www.bbc.com/",
            confidence="high",
        ),
        ServiceDomainMapEntry(
            "bbc_first_party",
            "mybbc-analytics.files.bbci.co.uk",
            "EXACT",
            "bbc.mobile.news.ww",
            "publisher_collection",
            source_url="https://bbc.github.io/echo-docs/",
            confidence="high",
            notes="BBC Echo analytics assets are served from this hostname; retain as first-party analytics/publisher collection context.",
        ),
        ServiceDomainMapEntry(
            "bbc_first_party",
            "map-remote-config.files.bbci.co.uk",
            "EXACT",
            "bbc.mobile.news.ww",
            "sdk_configuration",
            source_url="https://www.bbc.com/",
            confidence="medium",
            notes="BBC-observed remote-config hostname retained as package-scoped configuration delivery.",
        ),
        ServiceDomainMapEntry(
            "bbc_first_party",
            "static.files.bbci.co.uk",
            "EXACT",
            "bbc.mobile.news.ww",
            "static_asset_delivery",
            source_url="https://www.bbc.com/",
            confidence="medium",
        ),
        ServiceDomainMapEntry(
            "bbc_first_party",
            "bbcx-internal.com",
            "SUFFIX",
            "bbc.mobile.news.ww",
            "publisher_api",
            source_url="https://www.bbc.com/",
            confidence="medium",
            notes="Observed in current BBC News runtime traffic as a likely first-party live/app API endpoint.",
        ),
        ServiceDomainMapEntry("cnn_first_party", "cnn.com", "SUFFIX", "com.cnn.mobile.android.phone", "publisher_content", confidence="high"),
        ServiceDomainMapEntry("cnn_first_party", "cnn.io", "SUFFIX", "com.cnn.mobile.android.phone", "publisher_api", confidence="medium"),
        ServiceDomainMapEntry(
            "cnn_first_party",
            "politics-explorer-tiles-static.cnn.io",
            "EXACT",
            "com.cnn.mobile.android.phone",
            "content_delivery",
            source_url="https://www.codeandtheory.com/things-we-make/cnn-magic-wall-reinventing-an-iconic-media-star",
            confidence="medium",
            notes="CNN-observed static tile hostname retained as first-party politics asset delivery.",
        ),
        ServiceDomainMapEntry(
            "cnn_first_party",
            "ix.cnn.io",
            "EXACT",
            "com.cnn.mobile.android.phone",
            "content_delivery",
            source_url="https://ix.cnn.io/dailygraphics/graphics/20200306-us-covid19/parent.html",
            confidence="medium",
            notes="CNN-owned interactive/dailygraphics hostname observed in current runtime traffic; treat as first-party content delivery for embedded interactive assets.",
        ),
        ServiceDomainMapEntry(
            "cnn_first_party",
            "audience.cnn.com",
            "EXACT",
            "com.cnn.mobile.android.phone",
            "publisher_collection",
            source_url="https://commercial.cnn.com/our-solutions/audience-insights/",
            confidence="medium",
            notes="CNN first-party audience/insights hostname observed during app runtime traffic.",
        ),
        ServiceDomainMapEntry(
            "cnn_first_party",
            "smetrics.cnn.com",
            "EXACT",
            "com.cnn.mobile.android.phone",
            "publisher_collection",
            source_url="https://experienceleague.adobe.com/en/docs/analytics/implementation/vars/config-vars/trackingserver",
            confidence="medium",
            notes="CNN first-party metrics hostname; smetrics-style hosts are commonly used as first-party analytics collection endpoints.",
        ),
        ServiceDomainMapEntry("urbanairship", "urbanairship.com", "SUFFIX", role_class="engagement_push", confidence="high"),
        ServiceDomainMapEntry("dianomi", "dianomi.com", "SUFFIX", role_class="adtech_monetization", confidence="high"),
        ServiceDomainMapEntry("doubleverify", "doubleverify.com", "SUFFIX", role_class="ad_verification", confidence="high"),
        ServiceDomainMapEntry("permutive", "permutive.app", "SUFFIX", role_class="audience_personalization", confidence="high"),
        ServiceDomainMapEntry("permutive", "permutive.com", "SUFFIX", role_class="audience_personalization", confidence="high"),
        ServiceDomainMapEntry("appsflyer", "appsflyersdk.com", "SUFFIX", role_class="attribution_measurement", confidence="high"),
        ServiceDomainMapEntry("liveramp", "rlcdn.com", "SUFFIX", role_class="identity_sync", confidence="high"),
        ServiceDomainMapEntry("flashtalking", "flashtalking.com", "SUFFIX", role_class="ad_creative_delivery", confidence="high"),
        ServiceDomainMapEntry("optimizely", "optimizely.com", "SUFFIX", role_class="experimentation_personalization", confidence="high"),
        ServiceDomainMapEntry(
            "piano",
            "piano.io",
            "SUFFIX",
            role_class="subscription_paywall",
            source_url="https://piano.io/marketing/product/ad-revenue-insights-dynamic-paywall",
            confidence="high",
        ),
        ServiceDomainMapEntry("adobe_experience_cloud", "adobedtm.com", "SUFFIX", role_class="tag_delivery", confidence="high"),
        ServiceDomainMapEntry("adobe_experience_cloud", "demdex.net", "SUFFIX", role_class="audience_identity", confidence="high"),
        ServiceDomainMapEntry("adobe_experience_cloud", "adobe.com", "SUFFIX", "com.cnn.mobile.android.phone", "identity_api", confidence="medium"),
        ServiceDomainMapEntry(
            "adobe_advertising",
            "creative-assets.everesttech.net",
            "EXACT",
            "bbc.mobile.news.ww",
            "ad_creative_delivery",
            source_url="https://experienceleague.adobe.com/en/docs/core-services/interface/data-collection/cookies/advertising",
            confidence="medium",
            notes="BBC-observed Adobe Advertising asset hostname retained as ad creative delivery.",
        ),
        ServiceDomainMapEntry("integral_ad_science", "adsafeprotected.com", "SUFFIX", role_class="ad_verification", confidence="high"),
        ServiceDomainMapEntry("amazon_ads", "amazon-adsystem.com", "SUFFIX", role_class="adtech_monetization", confidence="medium"),
        ServiceDomainMapEntry(
            "amazon_media_cdn",
            "media-amazon.com",
            "SUFFIX",
            role_class="content_delivery",
            source_url="https://webservices.amazon.com/paapi5/documentation/images.html",
            confidence="medium",
            notes="Generic Amazon-hosted media asset delivery; package-scoped ad-tech mappings take precedence when present.",
        ),
        ServiceDomainMapEntry(
            "infosec_world_event_site",
            "infosecworldusa.com",
            "SUFFIX",
            role_class="conference_site_content",
            source_url="https://www.infosecworldusa.com/",
            confidence="medium",
            notes="Facebook-observed external event site content; not Facebook infrastructure.",
        ),
        ServiceDomainMapEntry(
            "swoogo_event_platform",
            "swoogo.com",
            "SUFFIX",
            role_class="event_platform_assets",
            source_url="https://swoogo.events/platform/",
            confidence="medium",
            notes="Event-platform asset delivery observed alongside InfoSec World external-page traffic.",
        ),
        ServiceDomainMapEntry(
            "steam_storefront",
            "steampowered.com",
            "SUFFIX",
            role_class="external_storefront_content",
            source_url="https://store.steampowered.com/about/",
            confidence="high",
            notes="Facebook-observed external Steam storefront content; not Facebook infrastructure.",
        ),
        ServiceDomainMapEntry(
            "steam_media_cdn",
            "steamstatic.com",
            "SUFFIX",
            role_class="static_asset_delivery",
            source_url="https://store.steampowered.com/privacy_agreement/",
            confidence="medium",
            notes="Steam static/CDN host observed with Steam storefront traffic.",
        ),
        ServiceDomainMapEntry(
            "amazon_ads",
            "media-amazon.com",
            "SUFFIX",
            "com.guardian",
            "ad_creative_delivery",
            source_url="https://advertising.amazon.com/solutions/products/sponsored-products-across-retailers",
            confidence="medium",
            notes="Guardian-observed Amazon-hosted media asset delivery in the same ad-tech cluster as Tungsten endpoints.",
        ),
        ServiceDomainMapEntry(
            "amazon_ads",
            "a9.amazon.dev",
            "SUFFIX",
            "com.guardian",
            "adtech_monetization",
            source_url="https://advertising.amazon.com/",
            confidence="medium",
            notes="Guardian-observed adsqtungsten.a9.amazon.dev host retained as Amazon ad-tech infrastructure.",
        ),
        ServiceDomainMapEntry(
            "amazon_ads",
            "unagi-na.amazon.com",
            "EXACT",
            "com.guardian",
            "ad_measurement",
            source_url="https://advertising.amazon.com/",
            confidence="low",
            notes="Guardian-observed Amazon edge host retained conservatively as advertising measurement context.",
        ),
        ServiceDomainMapEntry(
            "amazon_ads",
            "tq-tungsten.com",
            "SUFFIX",
            "com.guardian",
            "ad_measurement",
            source_url="https://advertising.amazon.com/",
            confidence="medium",
            notes="Guardian-observed Tungsten host retained as Amazon advertising measurement edge context.",
        ),
        ServiceDomainMapEntry("admaster", "admaster.cc", "SUFFIX", role_class="ad_measurement", confidence="medium"),
        ServiceDomainMapEntry("google_ads", "doubleclick.net", "SUFFIX", role_class="adtech_monetization", confidence="high"),
        ServiceDomainMapEntry("google_ads", "googlesyndication.com", "SUFFIX", role_class="adtech_monetization", confidence="high"),
        ServiceDomainMapEntry("google_ads", "2mdn.net", "SUFFIX", role_class="ad_creative_delivery", confidence="high"),
        ServiceDomainMapEntry("google_ads", "googletagservices.com", "SUFFIX", role_class="tag_delivery", confidence="high"),
        ServiceDomainMapEntry("google_ads", "adtrafficquality.google", "SUFFIX", role_class="ad_measurement", confidence="medium"),
        ServiceDomainMapEntry("google_ads", "imasdk.googleapis.com", "EXACT", role_class="adtech_monetization", confidence="medium"),
        ServiceDomainMapEntry("google_platform", "gstatic.com", "SUFFIX", role_class="google_infrastructure", confidence="medium"),
        ServiceDomainMapEntry("google_platform", "googlevideo.com", "SUFFIX", role_class="embedded_media_delivery", confidence="medium"),
        ServiceDomainMapEntry("google_platform", "googleapis.com", "SUFFIX", role_class="google_api_platform", confidence="medium"),
        ServiceDomainMapEntry(
            "akamai_diagnostics",
            "whoami.akamai.net",
            "EXACT",
            role_class="network_diagnostics",
            source_url="https://www.akamai.com/blog/developers/introducing-new-whoami-tool-dns-resolver-information",
            confidence="medium",
            notes="Akamai diagnostic hostname used to reveal resolver/edge information; keep scoped to exact host to avoid overclassifying generic Akamai CDN traffic.",
        ),
        ServiceDomainMapEntry(
            "oracle_cloud",
            "config.mtp.sag.us-ashburn-1.oci.oraclecloud.com",
            "EXACT",
            "com.zhiliaoapp.musically",
            "hosted_backend_infrastructure",
            source_url="https://newsroom.tiktok.com/en-us/delivering-on-our-us-data-governance",
            confidence="medium",
            notes="TikTok-observed OCI hostname. Public TikTok guidance describes routing US user traffic to Oracle Cloud Infrastructure; classify as third-party hosted backend infrastructure.",
        ),
        ServiceDomainMapEntry("oracle_cloud", "oraclecloud.com", "SUFFIX", role_class="cloud_infrastructure", confidence="medium"),
        ServiceDomainMapEntry(
            "mapbox_platform",
            "config.mapbox.com",
            "EXACT",
            "com.cnn.mobile.android.phone",
            "sdk_configuration",
            source_url="https://docs.mapbox.com/api/guides/",
            confidence="medium",
        ),
        ServiceDomainMapEntry(
            "mapbox_platform",
            "api.mapbox.com",
            "EXACT",
            "com.cnn.mobile.android.phone",
            "geospatial_api",
            source_url="https://docs.mapbox.com/api/guides/",
            confidence="medium",
            notes="Mapbox documents api.mapbox.com as the base path for its web services APIs; retain as package-scoped third-party geospatial API context for CNN runtime traffic.",
        ),
        ServiceDomainMapEntry("cloudflare_cdnjs", "cloudflare.com", "SUFFIX", "com.cnn.mobile.android.phone", "static_asset_delivery", source_url="https://cdnjs.com/about", confidence="medium"),
        ServiceDomainMapEntry("google_amp_cache", "ampproject.org", "SUFFIX", "com.cnn.mobile.android.phone", "content_delivery", source_url="https://developers.google.com/amp/cache/overview", confidence="medium"),
        ServiceDomainMapEntry("equativ_smartadserver", "smartadserver.com", "SUFFIX", "com.cnn.mobile.android.phone", "identity_sync", source_url="https://equativ.com/", confidence="medium"),
        ServiceDomainMapEntry("chartbeat", "chartbeat.net", "SUFFIX", role_class="analytics_measurement", confidence="high"),
        ServiceDomainMapEntry("scorecardresearch", "scorecardresearch.com", "SUFFIX", role_class="audience_measurement", confidence="high"),
        ServiceDomainMapEntry("new_relic", "newrelic.com", "SUFFIX", role_class="analytics_measurement", confidence="medium"),
        ServiceDomainMapEntry("nielsen_dcr", "vtwenty.com", "SUFFIX", role_class="audience_measurement", confidence="medium"),
        ServiceDomainMapEntry("ozone_project", "the-ozone-project.com", "SUFFIX", role_class="adtech_monetization", confidence="high"),
        ServiceDomainMapEntry("turner_cnn_legacy", "turner.com", "SUFFIX", "com.cnn.mobile.android.phone", "content_delivery", confidence="medium"),
        ServiceDomainMapEntry("wbd_streaming_platform", "warnermediacdn.com", "SUFFIX", "com.cnn.mobile.android.phone", "content_delivery", source_url="https://www.max.com/", confidence="medium"),
        ServiceDomainMapEntry("wbd_streaming_platform", "discomax.com", "SUFFIX", "com.cnn.mobile.android.phone", "streaming_platform_api", source_url="https://www.max.com/", confidence="medium", notes="Curated from Warner/Max-branded hostname observed in CNN runtime traffic."),
        ServiceDomainMapEntry(
            "wbd_streaming_platform",
            "ngtv.io",
            "SUFFIX",
            "com.cnn.mobile.android.phone",
            "streaming_delivery",
            source_url="https://www.netify.ai/resources/hostnames/freeview.ngtv.io",
            confidence="medium",
            notes="Package-scoped CNN/WB Discovery streaming-delivery hostname observed during app runtime traffic.",
        ),
        ServiceDomainMapEntry("freewheel", "fwmrm.net", "SUFFIX", role_class="adtech_video_monetization", source_url="https://www.freewheel.com/", confidence="high"),
        ServiceDomainMapEntry("mux_data", "litix.io", "SUFFIX", role_class="video_analytics_measurement", source_url="https://www.mux.com/docs/core.txt", confidence="medium"),
        ServiceDomainMapEntry("brightline_ctv", "brightline.tv", "SUFFIX", role_class="interactive_ctv_advertising", source_url="https://brightline.tv/", confidence="high"),
        ServiceDomainMapEntry("dianomi", "dianomi.workers.dev", "SUFFIX", "com.cnn.mobile.android.phone", "adtech_monetization", source_url="https://www.dianomi.com/", confidence="medium", notes="Worker-domain suffix retained as a curated Dianomi monetization edge mapping."),
        ServiceDomainMapEntry("guardian_first_party", "theguardian.com", "SUFFIX", "com.guardian", "publisher_content", source_url="https://open-platform.theguardian.com/", confidence="high"),
        ServiceDomainMapEntry(
            "guardian_first_party",
            "guardianapps.co.uk",
            "SUFFIX",
            "com.guardian",
            "publisher_api",
            source_url="https://github.com/guardian/frontend",
            confidence="high",
            notes="The Guardian frontend repository documents api.nextgen.guardianapps.co.uk as the app Ajax URL.",
        ),
        ServiceDomainMapEntry("guardian_first_party", "ophan.theguardian.com", "EXACT", "com.guardian", "publisher_collection", source_url="https://open-platform.theguardian.com/", confidence="medium", notes="Guardian-owned Ophan telemetry endpoint observed during app runtime traffic."),
        ServiceDomainMapEntry("guardian_first_party", "ophan.co.uk", "SUFFIX", "com.guardian", "publisher_collection", source_url="https://open-platform.theguardian.com/", confidence="medium", notes="Package-scoped Guardian Ophan telemetry alias observed as j.ophan.co.uk during app runtime traffic."),
        ServiceDomainMapEntry("guardian_first_party", "guardianapis.com", "SUFFIX", "com.guardian", "publisher_api", source_url="https://open-platform.theguardian.com/", confidence="high"),
        ServiceDomainMapEntry("guardian_first_party", "guim.co.uk", "SUFFIX", "com.guardian", "content_delivery", source_url="https://www.theguardian.com/about", confidence="medium"),
        ServiceDomainMapEntry("onetrust_cmp", "privacy-mgmt.com", "SUFFIX", "com.guardian", "consent_management", source_url="https://developer.onetrust.com/onetrust/docs/introduction-to-cmp", confidence="high"),
        ServiceDomainMapEntry("sourcepoint_cmp", "privacy-mgmt.com", "SUFFIX", "bbc.mobile.news.ww", "consent_management", source_url="https://sourcepoint.com/", confidence="medium"),
        ServiceDomainMapEntry("braze_sdk", "braze.eu", "SUFFIX", "com.guardian", "engagement_sdk", source_url="https://www.braze.com/docs/developer_guide/platform_integration_guides/android/", confidence="high"),
        ServiceDomainMapEntry("confiant_ad_security", "confiant-integrations.net", "SUFFIX", "com.guardian", "ad_security", source_url="https://www.confiant.com/", confidence="medium"),
        ServiceDomainMapEntry(
            "mainroll_pixel",
            "stats.mainroll.com",
            "EXACT",
            "com.guardian",
            "ad_measurement",
            source_label="repo_seed_public_filter_list",
            source_url="https://easylist.to/easylist/easylist.txt",
            confidence="medium",
            notes="Observed once in Guardian as SNI-only traffic; DNS resolves to CloudFront and live HTTP(S) returns a 43-byte image/gif, consistent with pixel-style measurement.",
        ),
        ServiceDomainMapEntry("firebase_crashlytics", "crashlytics.com", "SUFFIX", role_class="crash_reporting", source_url="https://firebase.google.com/docs/crashlytics", confidence="high"),
        ServiceDomainMapEntry("adjust_attribution", "adjust.com", "SUFFIX", role_class="attribution_measurement", source_url="https://dev.adjust.com/en/sdk/android/", confidence="high"),
        ServiceDomainMapEntry("espn_first_party", "fan.api.espn.com", "EXACT", "com.espn.score_center", "publisher_api", confidence="high"),
        ServiceDomainMapEntry("espn_first_party", "pinpoint.espn.com", "EXACT", "com.espn.score_center", "publisher_collection", confidence="medium"),
        ServiceDomainMapEntry("espn_first_party", "espn.api.edge.bamgrid.com", "EXACT", "com.espn.score_center", "publisher_api", confidence="medium"),
        ServiceDomainMapEntry("espn_first_party", "espn.connections.edge.bamgrid.com", "EXACT", "com.espn.score_center", "publisher_api", confidence="medium"),
        ServiceDomainMapEntry("espn_first_party", "espn.com", "SUFFIX", "com.espn.score_center", "publisher_api", confidence="medium"),
        ServiceDomainMapEntry("espn_first_party", "bamgrid.com", "SUFFIX", "com.espn.score_center", "publisher_api", confidence="medium"),
        ServiceDomainMapEntry("facebook_platform", "b-graph.facebook.com", "EXACT", "com.facebook.katana", "social_graph_api", confidence="medium"),
        ServiceDomainMapEntry(
            "facebook_platform",
            "b-api.facebook.com",
            "EXACT",
            "com.facebook.katana",
            "social_graph_api",
            source_url="https://developers.facebook.com/docs/graph-api/",
            confidence="medium",
            notes="Package-scoped Facebook API hostname observed in current app runtime traffic.",
        ),
        ServiceDomainMapEntry("facebook_platform", "connect.facebook.net", "EXACT", "com.facebook.katana", "identity_api", confidence="medium"),
        ServiceDomainMapEntry(
            "facebook_platform",
            "lookaside.facebook.com",
            "EXACT",
            "com.facebook.katana",
            "content_delivery",
            source_url="https://developers.facebook.com/docs/games/instant-games/sdk/fbinstant8.0/",
            confidence="medium",
            notes="Meta developer docs reference lookaside.facebook.com for hosted resources; observed in current Facebook runtime traffic as content/resource delivery.",
        ),
        ServiceDomainMapEntry(
            "facebook_platform",
            "mobile.facebook.com",
            "EXACT",
            "com.facebook.katana",
            "social_graph_api",
            source_url="https://developers.facebook.com/documentation/development/terms-and-policies/automated-data-collection",
            confidence="medium",
            notes="Package-scoped Facebook application/web surface observed in current runtime traffic; treat as first-party social graph access for the Facebook app.",
        ),
        ServiceDomainMapEntry(
            "facebook_platform",
            "web.facebook.com",
            "EXACT",
            "com.facebook.katana",
            "social_graph_api",
            source_url="https://developers.facebook.com/documentation/development/terms-and-policies/automated-data-collection",
            confidence="medium",
            notes="Package-scoped Facebook application/web surface observed in current runtime traffic; treat as first-party social graph access for the Facebook app.",
        ),
        ServiceDomainMapEntry(
            "facebook_platform",
            "www.facebook.com",
            "EXACT",
            "com.facebook.katana",
            "social_graph_api",
            source_url="https://developers.facebook.com/documentation/development/terms-and-policies/automated-data-collection",
            confidence="medium",
            notes="Package-scoped Facebook application/web surface observed in current runtime traffic; treat as first-party social graph access for the Facebook app.",
        ),
        ServiceDomainMapEntry(
            "facebook_platform",
            "b-www.facebook.com",
            "EXACT",
            "com.facebook.katana",
            "social_graph_api",
            source_url="https://developers.facebook.com/documentation/development/terms-and-policies/automated-data-collection",
            confidence="medium",
            notes="Package-scoped Facebook web-surface hostname observed in current runtime traffic; retained as first-party social graph/web access for the Facebook app.",
        ),
        ServiceDomainMapEntry(
            "facebook_platform",
            "gateway.facebook.com",
            "EXACT",
            "com.facebook.katana",
            "social_graph_api",
            source_url="https://developers.facebook.com/docs/graph-api/",
            confidence="medium",
            notes="Package-scoped Facebook gateway hostname observed in current runtime traffic; retained as first-party social graph/platform control traffic.",
        ),
        ServiceDomainMapEntry(
            "facebook_platform",
            "genai-graph.facebook.com",
            "EXACT",
            "com.facebook.katana",
            "social_graph_api",
            source_url="https://developers.facebook.com/documentation/ads-commerce/marketing-api/creative/generative-ai-features",
            confidence="medium",
            notes="Package-scoped Meta generative-AI graph hostname observed in current runtime traffic; retained under first-party social graph/platform API semantics.",
        ),
        ServiceDomainMapEntry(
            "facebook_platform",
            "z-m-gateway.facebook.com",
            "EXACT",
            "com.facebook.katana",
            "social_graph_api",
            source_url="https://developers.facebook.com/docs/graph-api/",
            confidence="medium",
            notes="Package-scoped Facebook gateway hostname observed in current runtime traffic; retained as first-party social graph/platform control traffic.",
        ),
        ServiceDomainMapEntry(
            "facebook_platform",
            "graph-fallback.facebook.com",
            "EXACT",
            "com.facebook.katana",
            "social_graph_api",
            source_url="https://developers.facebook.com/docs/graph-api/",
            confidence="medium",
            notes="Package-scoped Facebook fallback graph hostname observed in current runtime traffic; retained as first-party social graph access.",
        ),
        ServiceDomainMapEntry(
            "facebook_platform",
            "mqtt-mini.facebook.com",
            "EXACT",
            "com.facebook.katana",
            "realtime_messaging",
            source_url="https://developers.facebook.com/docs/messenger-platform/",
            confidence="medium",
            notes="Package-scoped Facebook realtime transport hostname observed in current app runtime traffic.",
        ),
        ServiceDomainMapEntry(
            "facebook_platform",
            "edge-mqtt.facebook.com",
            "EXACT",
            "com.facebook.katana",
            "realtime_messaging",
            source_url="https://developers.facebook.com/docs/messenger-platform/",
            confidence="medium",
            notes="Package-scoped Facebook realtime messaging hostname observed during current Facebook runtime captures.",
        ),
        ServiceDomainMapEntry(
            "facebook_platform",
            "chat-e2ee-mini.facebook.com",
            "EXACT",
            "com.facebook.katana",
            "messaging_e2ee",
            source_url="https://www.facebook.com/help/messenger-app/786613221989782",
            confidence="medium",
            notes="Package-scoped Meta messaging/E2EE hostname observed during current Facebook runtime captures.",
        ),
        ServiceDomainMapEntry(
            "facebook_platform",
            "payments-graph.facebook.com",
            "EXACT",
            "com.facebook.katana",
            "payments_api",
            source_url="https://developers.facebook.com/docs/graph-api/",
            confidence="medium",
            notes="Package-scoped Facebook payments graph hostname observed during current Facebook runtime captures.",
        ),
        ServiceDomainMapEntry("facebook_platform", "facebook.com", "SUFFIX", "com.facebook.katana", "social_graph_api", confidence="high"),
        ServiceDomainMapEntry("facebook_platform", "facebook.com", "SUFFIX", "com.facebook.orca", "social_graph_api", confidence="high"),
        ServiceDomainMapEntry(
            "facebook_platform",
            "messenger.com",
            "SUFFIX",
            "com.facebook.orca",
            "messaging_platform_api",
            source_url="https://www.messenger.com/",
            confidence="high",
        ),
        ServiceDomainMapEntry("facebook_platform", "facebook.com", "SUFFIX", "com.instagram.android", "social_graph_api", confidence="high"),
        ServiceDomainMapEntry("facebook_platform", "facebook.net", "SUFFIX", "com.facebook.katana", "social_graph_api", confidence="medium"),
        ServiceDomainMapEntry("facebook_platform", "facebook.net", "SUFFIX", "com.facebook.orca", "social_graph_api", confidence="medium"),
        ServiceDomainMapEntry("facebook_platform", "facebook.net", "SUFFIX", "com.instagram.android", "social_graph_api", confidence="medium"),
        ServiceDomainMapEntry("facebook_platform", "fbcdn.net", "SUFFIX", "com.facebook.katana", "content_delivery", confidence="medium"),
        ServiceDomainMapEntry("facebook_platform", "fbcdn.net", "SUFFIX", "com.facebook.orca", "content_delivery", confidence="medium"),
        ServiceDomainMapEntry("facebook_platform", "fbcdn.net", "SUFFIX", "com.instagram.android", "content_delivery", confidence="medium"),
        ServiceDomainMapEntry(
            "zoom_platform",
            "zoom.us",
            "SUFFIX",
            role_class="realtime_call_transport",
            source_url="https://developers.zoom.us/docs/meeting-sdk/",
            confidence="medium",
            notes="Covers Zoom meeting/webinar hostnames observed when social apps launch external meeting links.",
        ),
        ServiceDomainMapEntry(
            "giphy_media",
            "giphy.com",
            "SUFFIX",
            role_class="content_delivery",
            source_url="https://developers.giphy.com/docs/api/",
            confidence="medium",
        ),
        ServiceDomainMapEntry("cloudflare_privacy_gateway", "privacy-gateway.cloudflare.com", "SUFFIX", "com.facebook.orca", "privacy_gateway", source_url="https://developers.cloudflare.com/privacy-gateway/", confidence="medium"),
        ServiceDomainMapEntry("whatsapp_platform", "graph.whatsapp.com", "EXACT", "com.whatsapp", "messaging_platform_api", source_url="https://developers.facebook.com/docs/whatsapp/cloud-api/", confidence="high"),
        ServiceDomainMapEntry("whatsapp_platform", "api.whatsapp.net", "EXACT", "com.whatsapp", "messaging_platform_api", source_url="https://developers.facebook.com/docs/whatsapp/cloud-api/", confidence="high"),
        ServiceDomainMapEntry("whatsapp_platform", "acs.whatsapp.com", "EXACT", "com.whatsapp", "messaging_platform_api", source_url="https://developers.facebook.com/documentation/business-messaging/whatsapp/overview", confidence="medium"),
        ServiceDomainMapEntry("whatsapp_platform", "v.whatsapp.net", "EXACT", "com.whatsapp", "realtime_call_transport", source_url="https://www.whatsapp.com/security/", confidence="medium"),
        ServiceDomainMapEntry("whatsapp_platform", "g.whatsapp.net", "EXACT", "com.whatsapp", "realtime_messaging", source_url="https://www.whatsapp.com/security/", confidence="medium"),
        ServiceDomainMapEntry("whatsapp_platform", "mmg.whatsapp.net", "EXACT", "com.whatsapp", "media_delivery", source_url="https://developers.facebook.com/docs/whatsapp/cloud-api/reference/media", confidence="medium"),
        ServiceDomainMapEntry("whatsapp_platform", "scontent.whatsapp.net", "EXACT", "com.whatsapp", "content_delivery", source_url="https://www.whatsapp.com/security/", confidence="medium"),
        ServiceDomainMapEntry("whatsapp_platform", "static.whatsapp.net", "EXACT", "com.whatsapp", "static_asset_delivery", source_url="https://www.whatsapp.com/security/", confidence="medium"),
        ServiceDomainMapEntry("whatsapp_platform", "cdn.whatsapp.net", "SUFFIX", "com.whatsapp", "content_delivery", source_url="https://www.whatsapp.com/security/", confidence="medium"),
        ServiceDomainMapEntry("whatsapp_platform", "whatsapp.com", "SUFFIX", "com.whatsapp", "first_party_misc", source_url="https://www.whatsapp.com/security/", confidence="medium"),
        ServiceDomainMapEntry("whatsapp_platform", "whatsapp.net", "SUFFIX", "com.whatsapp", "first_party_misc", source_url="https://www.whatsapp.com/security/", confidence="medium"),
        ServiceDomainMapEntry("whatsapp_platform", "v.whatsapp.net", "EXACT", "com.facebook.orca", "realtime_call_transport", source_url="https://www.whatsapp.com/security/", confidence="medium"),
        ServiceDomainMapEntry("whatsapp_platform", "v.whatsapp.net", "EXACT", "com.instagram.android", "realtime_call_transport", source_url="https://www.whatsapp.com/security/", confidence="medium"),
        ServiceDomainMapEntry("telegram_platform", "telegram.org", "SUFFIX", "org.telegram.messenger", "encrypted_messaging_api", source_url="https://core.telegram.org/", confidence="high"),
        ServiceDomainMapEntry("telegram_platform", "t.me", "SUFFIX", "org.telegram.messenger", "telegram_deep_link", source_url="https://telegram.org/faq", confidence="high"),
        ServiceDomainMapEntry("instagram_platform", "instagram.com", "SUFFIX", "com.instagram.android", "social_graph_api", source_url="https://developers.facebook.com/docs/instagram-platform/", confidence="high"),
        ServiceDomainMapEntry("instagram_media_cdn", "cdninstagram.com", "SUFFIX", "com.instagram.android", "content_delivery", source_url="https://developers.facebook.com/docs/instagram-platform/", confidence="medium"),
        ServiceDomainMapEntry(
            "facebook_platform",
            "cdninstagram.com",
            "SUFFIX",
            "com.facebook.katana",
            "content_delivery",
            source_url="https://developers.facebook.com/docs/instagram-platform/instagram-api-with-instagram-login/get-started",
            confidence="medium",
            notes="Package-scoped first-party content mapping for Instagram CDN traffic observed inside the Facebook app.",
        ),
        ServiceDomainMapEntry("meta_sdk", "b-graph.facebook.com", "EXACT", role_class="social_graph_api", confidence="medium"),
        ServiceDomainMapEntry("meta_sdk", "connect.facebook.net", "EXACT", role_class="identity_api", confidence="medium"),
        ServiceDomainMapEntry("meta_sdk", "facebook.com", "SUFFIX", role_class="social_graph_api", confidence="medium"),
        ServiceDomainMapEntry("meta_sdk", "facebook.net", "SUFFIX", role_class="social_graph_api", confidence="medium"),
        ServiceDomainMapEntry("meta_sdk", "fbcdn.net", "SUFFIX", role_class="content_delivery", confidence="low"),
        ServiceDomainMapEntry("x_platform", "api.twitter.com", "EXACT", "com.twitter.android", "social_graph_api", confidence="high"),
        ServiceDomainMapEntry("x_platform", "api-stream.twitter.com", "EXACT", "com.twitter.android", "social_graph_api", confidence="high"),
        ServiceDomainMapEntry("x_platform", "api.x.com", "EXACT", "com.twitter.android", "social_graph_api", confidence="high"),
        ServiceDomainMapEntry(
            "x_platform",
            "probe.twitter.com",
            "EXACT",
            "com.twitter.android",
            "realtime_engagement",
            source_url="https://www.netify.ai/resources/hostnames/probe.twitter.com",
            confidence="medium",
            notes="Curated from current-build X/Twitter runtime traffic plus external hostname references describing probe/live-engagement behavior.",
        ),
        ServiceDomainMapEntry(
            "x_platform",
            "analytics.twitter.com",
            "EXACT",
            "com.twitter.android",
            "analytics_measurement",
            source_url="https://docs.x.com/x-ads-api/analytics",
            confidence="high",
        ),
        ServiceDomainMapEntry(
            "x_platform",
            "chat-ws.x.com",
            "EXACT",
            "com.twitter.android",
            "realtime_engagement",
            source_url="https://docs.x.com/x-api/introduction",
            confidence="medium",
            notes="Observed current-build X runtime websocket endpoint; treat as first-party realtime engagement infrastructure.",
        ),
        ServiceDomainMapEntry("x_platform", "x.com", "EXACT", "com.twitter.android", "social_graph_api", confidence="medium"),
        ServiceDomainMapEntry("x_media_cdn", "pbs.twimg.com", "EXACT", "com.twitter.android", "content_delivery", confidence="high"),
        ServiceDomainMapEntry("x_media_cdn", "video.twimg.com", "EXACT", "com.twitter.android", "content_delivery", confidence="high"),
        ServiceDomainMapEntry(
            "x_media_cdn",
            "video-s.twimg.com",
            "EXACT",
            "com.twitter.android",
            "content_delivery",
            source_url="https://bugzilla.mozilla.org/show_bug.cgi?id=1977810",
            confidence="high",
            notes="Curated from current-build X/Twitter runtime traffic and external webcompat evidence tying the hostname to Twitter/X video delivery.",
        ),
        ServiceDomainMapEntry("x_media_cdn", "abs.twimg.com", "EXACT", "com.twitter.android", "static_asset_delivery", confidence="medium"),
        ServiceDomainMapEntry("x_ads_platform", "ads-api.x.com", "EXACT", "com.twitter.android", "ad_measurement", confidence="medium"),
        ServiceDomainMapEntry("linkedin_platform", "linkedin.com", "SUFFIX", "com.linkedin.android", "professional_social_graph_api", source_url="https://www.linkedin.com/", confidence="high"),
        ServiceDomainMapEntry("linkedin_platform", "perf.linkedin.com", "SUFFIX", "com.linkedin.android", "performance_telemetry", source_url="https://www.linkedin.com/", confidence="medium"),
        ServiceDomainMapEntry("linkedin_platform", "perf.linkedin-ei.com", "SUFFIX", "com.linkedin.android", "performance_telemetry", source_url="https://www.linkedin.com/", confidence="medium"),
        ServiceDomainMapEntry("linkedin_cdn", "media.licdn.com", "EXACT", "com.linkedin.android", "media_delivery", source_url="https://www.linkedin.com/", confidence="high"),
        ServiceDomainMapEntry("linkedin_cdn", "static-akam.licdn.com", "EXACT", "com.linkedin.android", "static_asset_delivery", source_url="https://www.linkedin.com/", confidence="high"),
        ServiceDomainMapEntry("linkedin_cdn", "dms.licdn.com", "EXACT", "com.linkedin.android", "document_media_delivery", source_url="https://www.linkedin.com/", confidence="medium"),
        ServiceDomainMapEntry("linkedin_cdn", "dms-akam.licdn.com", "EXACT", "com.linkedin.android", "document_media_delivery", source_url="https://www.linkedin.com/", confidence="medium"),
        ServiceDomainMapEntry("linkedin_cdn", "static-cflr.licdn.com", "EXACT", "com.linkedin.android", "static_asset_delivery", source_url="https://www.linkedin.com/", confidence="medium"),
        ServiceDomainMapEntry("linkedin_cdn", "static-fsly.licdn.com", "EXACT", "com.linkedin.android", "static_asset_delivery", source_url="https://www.linkedin.com/", confidence="medium"),
        ServiceDomainMapEntry("linkedin_cdn", "pop-ltx1-lx.www.linkedin.com", "EXACT", "com.linkedin.android", "content_delivery", source_url="https://www.linkedin.com/", confidence="medium"),
        ServiceDomainMapEntry("linkedin_cdn", "pop-lva1-lx.www.linkedin.com", "EXACT", "com.linkedin.android", "content_delivery", source_url="https://www.linkedin.com/", confidence="medium"),
        ServiceDomainMapEntry("linkedin_cdn", "pop-lor1-lx.www.linkedin.com", "EXACT", "com.linkedin.android", "content_delivery", source_url="https://www.linkedin.com/", confidence="medium"),
        ServiceDomainMapEntry("linkedin_cdn", "licdn.com", "SUFFIX", "com.linkedin.android", "content_delivery", source_url="https://www.linkedin.com/", confidence="medium"),
        ServiceDomainMapEntry("human_security_bot_defense", "protechts.net", "SUFFIX", "com.linkedin.android", "bot_defense", source_url="https://www.humansecurity.com/", confidence="medium"),
        ServiceDomainMapEntry("human_security_bot_defense", "xlgmedia.com", "SUFFIX", "com.linkedin.android", "bot_defense", source_url="https://www.netify.ai/resources/domains/xlgmedia.com", confidence="medium"),
        ServiceDomainMapEntry("ns1_connect", "ns1p.net", "SUFFIX", "com.linkedin.android", "managed_dns_edge", source_url="https://www.ibm.com/products/ns1-connect", confidence="medium"),
        ServiceDomainMapEntry("pinterest_platform", "pinterest.com", "SUFFIX", "com.pinterest", "visual_discovery_api", source_url="https://developers.pinterest.com/", confidence="high"),
        ServiceDomainMapEntry("pinterest_media_cdn", "pinimg.com", "SUFFIX", "com.pinterest", "content_delivery", source_url="https://developers.pinterest.com/", confidence="medium"),
        ServiceDomainMapEntry("google_recaptcha", "recaptcha.net", "SUFFIX", "com.pinterest", "bot_defense", source_url="https://developers.google.com/recaptcha", confidence="high"),
        ServiceDomainMapEntry("google_recaptcha", "recaptcha.net", "SUFFIX", role_class="bot_defense", source_url="https://developers.google.com/recaptcha", confidence="high"),
        ServiceDomainMapEntry("reddit_platform", "reddit.com", "SUFFIX", "com.reddit.frontpage", "community_platform_api", source_url="https://developers.reddit.com/docs/capabilities/server/reddit-api", confidence="high"),
        ServiceDomainMapEntry("reddit_platform", "redditspace.com", "SUFFIX", "com.reddit.frontpage", "realtime_platform", source_url="https://www.netify.ai/resources/applications/reddit", confidence="medium"),
        ServiceDomainMapEntry("reddit_media_cdn", "redd.it", "SUFFIX", "com.reddit.frontpage", "content_delivery", source_url="https://www.netify.ai/resources/applications/reddit", confidence="medium"),
        ServiceDomainMapEntry("reddit_media_cdn", "redditmedia.com", "SUFFIX", "com.reddit.frontpage", "content_delivery", source_url="https://www.netify.ai/resources/applications/reddit", confidence="medium"),
        ServiceDomainMapEntry("reddit_media_cdn", "redditstatic.com", "SUFFIX", "com.reddit.frontpage", "static_asset_delivery", source_url="https://www.netify.ai/resources/applications/reddit", confidence="medium"),
        ServiceDomainMapEntry("appsflyer", "sng.link", "SUFFIX", role_class="attribution_deep_link", source_url="https://support.appsflyer.com/hc/en-us/articles/115005248543-OneLink-guide", confidence="medium"),
        ServiceDomainMapEntry("appsflyer", "appsflyer.com", "SUFFIX", role_class="attribution_measurement", source_url="https://www.appsflyer.com/", confidence="high"),
        ServiceDomainMapEntry("snapchat_platform", "snapchat.com", "SUFFIX", "com.snapchat.android", "messaging_platform_api", source_url="https://developers.snap.com/", confidence="high"),
        ServiceDomainMapEntry("snapchat_cdn", "sc-cdn.net", "SUFFIX", "com.snapchat.android", "content_delivery", source_url="https://developers.snap.com/", confidence="medium"),
        ServiceDomainMapEntry("signal_platform", "signal.org", "SUFFIX", "org.thoughtcrime.securesms", "encrypted_messaging_api", source_url="https://signal.org/legal/", confidence="high"),
        ServiceDomainMapEntry("cloudflare_realtime_relay", "stun.cloudflare.com", "EXACT", "org.thoughtcrime.securesms", "stun_relay", source_url="https://developers.cloudflare.com/realtime/turn/", confidence="medium"),
        ServiceDomainMapEntry("cloudflare_realtime_relay", "turn.cloudflare.com", "EXACT", "org.thoughtcrime.securesms", "turn_relay", source_url="https://developers.cloudflare.com/realtime/turn/", confidence="medium"),
        ServiceDomainMapEntry("firebase_installations", "firebaseinstallations.googleapis.com", "EXACT", role_class="installation_identity", source_url="https://firebase.google.com/docs/projects/manage-installations", confidence="high"),
        ServiceDomainMapEntry("google_platform", "stun.l.google.com", "EXACT", role_class="stun_relay", source_url="https://groups.google.com/g/discuss-webrtc/c/b-5alYpbxXw", confidence="medium"),
        ServiceDomainMapEntry("google_platform", "www.google.com", "EXACT", role_class="google_web", source_url="https://www.google.com/", confidence="medium"),
        ServiceDomainMapEntry("google_platform", "googleusercontent.com", "SUFFIX", role_class="content_delivery", source_url="https://www.netify.ai/resources/hostnames/play-lh.googleusercontent.com", confidence="medium"),
        ServiceDomainMapEntry("microsoft_fraud_protection", "fpt.dfp.microsoft.com", "EXACT", role_class="device_fingerprinting", source_url="https://learn.microsoft.com/en-us/dynamics365/fraud-protection/df-web", confidence="high"),
        ServiceDomainMapEntry("microsoft_ads_atlas", "atdmt.com", "SUFFIX", role_class="adtech_monetization", confidence="medium"),
        ServiceDomainMapEntry("google_platform", "time.google.com", "EXACT", role_class="google_infrastructure", confidence="medium"),
        ServiceDomainMapEntry("tiktok_platform", "tiktokcdn.com", "SUFFIX", "com.zhiliaoapp.musically", "content_delivery", confidence="medium"),
        ServiceDomainMapEntry("tiktok_platform", "tiktokcdn-us.com", "SUFFIX", "com.zhiliaoapp.musically", "content_delivery", confidence="high"),
        ServiceDomainMapEntry(
            "tiktok_platform",
            "api16-normal-useast5.tiktokv.us",
            "EXACT",
            "com.zhiliaoapp.musically",
            "social_graph_api",
            source_url="https://www.netify.ai/resources/domains/tiktokv.us",
            confidence="high",
            notes="TikTok first-party API hostname observed in current dynamic captures.",
        ),
        ServiceDomainMapEntry(
            "tiktok_platform",
            "aggr16-normal.tiktokv.us",
            "EXACT",
            "com.zhiliaoapp.musically",
            "performance_telemetry",
            source_url="https://www.netify.ai/resources/domains/tiktokv.us",
            confidence="medium",
            notes="TikTok first-party aggregation hostname observed repeatedly in dynamic captures.",
        ),
        ServiceDomainMapEntry(
            "tiktok_platform",
            "aggr19-normal.tiktokv.us",
            "EXACT",
            "com.zhiliaoapp.musically",
            "performance_telemetry",
            source_url="https://www.netify.ai/resources/domains/tiktokv.us",
            confidence="medium",
            notes="TikTok first-party aggregation hostname observed repeatedly in dynamic captures.",
        ),
        ServiceDomainMapEntry(
            "tiktok_platform",
            "tnc16-normal-useast5.tiktokv.us",
            "EXACT",
            "com.zhiliaoapp.musically",
            "sdk_configuration",
            source_url="https://www.netify.ai/resources/domains/tiktokv.us",
            confidence="medium",
            notes="TikTok first-party config/control hostname observed in dynamic captures.",
        ),
        ServiceDomainMapEntry(
            "tiktok_platform",
            "ug-attribution.tiktokv.us",
            "EXACT",
            "com.zhiliaoapp.musically",
            "attribution_measurement",
            source_url="https://www.netify.ai/resources/domains/tiktokv.us",
            confidence="medium",
            notes="TikTok first-party attribution hostname observed in dynamic captures.",
        ),
        ServiceDomainMapEntry(
            "tiktok_ads_measurement",
            "tiktok.adsmeasurement.com",
            "EXACT",
            "com.zhiliaoapp.musically",
            "ad_measurement",
            source_url="https://ads.tiktok.com/business/en-US/products/measurement",
            confidence="medium",
            notes="Package-scoped TikTok ads-measurement hostname observed in TikTok runtime traffic.",
        ),
        ServiceDomainMapEntry("tiktok_platform", "tiktokv.us", "SUFFIX", "com.zhiliaoapp.musically", "first_party_misc", confidence="high"),
        ServiceDomainMapEntry("tiktok_platform", "ibyteimg.com", "SUFFIX", "com.zhiliaoapp.musically", "content_delivery", confidence="medium"),
    )


def default_service_catalog_seed_rows() -> list[dict[str, str | None]]:
    return [
        {
            "service_key": entry.service_key,
            "display_name": entry.display_name,
            "owner_name": entry.owner_name,
            "owner_class": entry.owner_class,
            "service_category": entry.service_category,
            "primary_use_case": entry.primary_use_case,
            "documentation_url": entry.documentation_url,
            "privacy_policy_url": entry.privacy_policy_url,
            "source_label": entry.source_label,
            "source_url": entry.source_url,
            "confidence": entry.confidence,
            "notes": entry.notes,
        }
        for entry in default_service_catalog_entries()
    ]


def default_service_domain_map_seed_rows() -> list[dict[str, str | None]]:
    return [
        {
            "service_key": entry.service_key,
            "package_name_scope": entry.package_name_scope,
            "domain_pattern": normalize_domain(entry.domain_pattern),
            "match_type": entry.match_type.upper(),
            "role_class": entry.role_class,
            "source_label": entry.source_label,
            "source_url": entry.source_url,
            "confidence": entry.confidence,
            "notes": entry.notes,
        }
        for entry in default_service_domain_map_entries()
    ]


def resolve_service_for_domain(
    domain: str,
    *,
    package_name: str,
    service_rows: tuple[dict[str, Any], ...],
    map_rows: tuple[dict[str, Any], ...],
) -> dict[str, Any]:
    normalized = normalize_domain(domain)
    normalized_package = _norm_text(package_name).lower()
    root = root_domain(normalized)
    if not normalized:
        return {
            "domain": "",
            "root_domain": "",
            "service_key": None,
            "service_display_name": None,
            "owner_name": None,
            "owner_class": None,
            "service_category": None,
            "primary_use_case": None,
            "role_class": None,
            "confidence": None,
            "match_type": None,
            "package_name_scope": None,
            "source_url": None,
        }

    by_key = {str(row.get("service_key") or ""): row for row in service_rows}
    candidates: list[dict[str, Any]] = []
    for row in map_rows:
        pattern = normalize_domain(row.get("domain_pattern"))
        match_type = str(row.get("match_type") or "").upper()
        scope = _norm_text(row.get("package_name_scope")).lower()
        if scope and scope != normalized_package:
            continue
        matched = False
        if match_type == "EXACT":
            matched = pattern == normalized
        elif match_type == "SUFFIX":
            matched = suffix_match(normalized, pattern)
        if matched:
            score = (0 if scope else 1, 0 if match_type == "EXACT" else 1, -len(pattern))
            candidates.append({"row": row, "score": score})
    candidates.sort(key=lambda item: item["score"])
    if not candidates:
        return {
            "domain": normalized,
            "root_domain": root,
            "service_key": None,
            "service_display_name": None,
            "owner_name": None,
            "owner_class": None,
            "service_category": None,
            "primary_use_case": None,
            "role_class": None,
            "confidence": None,
            "match_type": None,
            "package_name_scope": None,
            "source_url": None,
        }
    chosen = candidates[0]["row"]
    service = by_key.get(str(chosen.get("service_key") or ""), {})
    return {
        "domain": normalized,
        "root_domain": root,
        "service_key": service.get("service_key"),
        "service_display_name": service.get("display_name"),
        "owner_name": service.get("owner_name"),
        "owner_class": service.get("owner_class"),
        "service_category": service.get("service_category"),
        "primary_use_case": service.get("primary_use_case"),
        "role_class": chosen.get("role_class"),
        "confidence": chosen.get("confidence") or service.get("confidence"),
        "match_type": chosen.get("match_type"),
        "package_name_scope": chosen.get("package_name_scope"),
        "source_url": chosen.get("source_url") or service.get("source_url") or service.get("documentation_url"),
    }


__all__ = [
    "ServiceCatalogEntry",
    "ServiceDomainMapEntry",
    "default_service_catalog_entries",
    "default_service_catalog_seed_rows",
    "default_service_domain_map_entries",
    "default_service_domain_map_seed_rows",
    "resolve_service_for_domain",
]
