"""Scan-oriented command definitions."""

from __future__ import annotations

from .models import Command

SCAN_COMMANDS: tuple[Command, ...] = (
    Command(
        id="1",
        title="Full analysis",
        description="Run complete static analysis with full detector coverage",
        kind="scan",
        profile="full",
        section="workflow",
        auto_verify=True,
        prompt_reset=True,
    ),
    Command(
        id="2",
        title="Lightweight scan",
        description="Run core detectors for quick MASVS/risk coverage",
        kind="scan",
        profile="lightweight",
        section="workflow",
        auto_verify=True,
    ),
    Command(
        id="3",
        title="Re-analyze last APK",
        description="Re-run analysis for the most recent static run (fallback to latest harvest)",
        kind="scan",
        profile="full",
        section="workflow",
        auto_verify=True,
    ),
    Command(
        id="4",
        title="Diff two versions",
        description="Compare the latest two versions for the most recent package",
        kind="scan",
        profile="full",
        section="workflow",
    ),
    Command(
        id="5",
        title="Diagnostic scan",
        description="Run analysis without persisting; surface warnings/errors for debugging",
        kind="scan",
        profile="full",
        section="workflow",
        persist=False,
        dry_run=True,
        auto_verify=False,
        prompt_reset=False,
    ),
    Command(
        id="D",
        title="Single APK drilldown (read-only)",
        description="Inspect a single APK without writing to the database",
        kind="scan",
        profile="full",
        section="tools",
        persist=False,
        dry_run=True,
        force_app_scope=True,
    ),
    # Developer shortcuts (only shown when SCYTALEDROID_DEV_SHORTCUTS=1)
    Command(
        id="C",
        title="CNN — baseline regression",
        description="Stable app used to verify detector outputs",
        kind="scan",
        profile="full",
        section="dev",
        auto_verify=True,
        force_app_scope=True,
        prompt_reset=False,
    ),
    Command(
        id="T",
        title="TikTok — stress / edge-case",
        description="Complex app to stress components, strings, and permissions",
        kind="scan",
        profile="full",
        section="dev",
        auto_verify=True,
        force_app_scope=True,
        prompt_reset=False,
    ),
    Command(
        id="G",
        title="Gmail — Google reference",
        description="Well-engineered baseline for best-practice comparisons",
        kind="scan",
        profile="full",
        section="dev",
        auto_verify=True,
        force_app_scope=True,
        prompt_reset=False,
    ),
    Command(
        id="W",
        title="WhatsApp — messaging / IPC stress",
        description="Messaging-heavy app to stress IPC and permissions",
        kind="scan",
        profile="full",
        section="dev",
        auto_verify=True,
        force_app_scope=True,
        prompt_reset=False,
    ),
)

__all__ = ["SCAN_COMMANDS"]
