"""SQL execution helper used by database query modules."""

from __future__ import annotations

from typing import Any, Iterable, Mapping, Optional, Sequence, Union

from .db_engine import DatabaseEngine
from .session import database_session, get_current_engine

ParamsType = Optional[Union[Sequence[Any], Mapping[str, Any]]]


def _normalise_params(params: ParamsType) -> Union[tuple[Any, ...], Mapping[str, Any]]:
    if params is None:
        return ()
    if isinstance(params, Mapping):
        return params
    if isinstance(params, tuple):
        return params
    if isinstance(params, list):
        return tuple(params)
    return (params,)  # single positional value


def run_sql(
    query: str,
    params: ParamsType = None,
    *,
    fetch: str = "none",
    dictionary: bool = False,
    return_lastrowid: bool = False,
) -> Any:
    """Execute SQL and return results based on the requested fetch mode.

    Args:
        query: The SQL statement to execute.
        params: Optional parameters for the query. Accepts sequence or mapping.
        fetch: One of "none", "one", "all". Append "_dict" or set dictionary=True for dict results.
        dictionary: If True, results are returned as dictionaries when fetching.
        return_lastrowid: When fetch="none", return the lastrowid generated by the insert.

    Returns:
        Query result depending on the fetch mode or lastrowid for inserts.
    """
    normalised_params = _normalise_params(params)
    fetch_mode = fetch.lower()
    if dictionary:
        if fetch_mode == "none":
            raise ValueError("dictionary results require fetch='one' or 'all'")
        if not fetch_mode.endswith("_dict"):
            fetch_mode = f"{fetch_mode}_dict"

    engine = get_current_engine()

    def _execute(db: DatabaseEngine) -> Any:
        if fetch_mode in {"one", "one_tuple"}:
            return db.fetch_one(query, normalised_params)  # type: ignore[arg-type]
        if fetch_mode in {"one_dict"}:
            return db.fetch_one_dict(query, normalised_params)  # type: ignore[arg-type]
        if fetch_mode in {"all", "all_tuple"}:
            return db.fetch_all(query, normalised_params)  # type: ignore[arg-type]
        if fetch_mode in {"all_dict"}:
            return db.fetch_all_dict(query, normalised_params)  # type: ignore[arg-type]

        if return_lastrowid:
            return db.execute_with_lastrowid(query, normalised_params)  # type: ignore[arg-type]
        db.execute(query, normalised_params)  # type: ignore[arg-type]
        return None

    if engine is not None:
        return _execute(engine)

    with database_session() as session:
        return _execute(session)


__all__ = ["run_sql"]
